### ISSUE TITLE
Revit units problem from Analytical properties

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#1053]

**Comment by teocomi** [comment]
Please add some details

**Comment by Reynold-Chan** [comment]
exporting revit analytical elements results in wrong units being exported for section profiles

**Comment by Reynold-Chan** [comment]
![image](https://user-images.githubusercontent.com/29717150/197293476-275382b2-f99b-4875-a4ee-aa015f2a3d1e.png)

**Comment by paloknapo** [comment]
fixed
