### ISSUE TITLE
Revit: Parameter values not being updated

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1059]
Described in detail here: https://speckle.community/t/parameter-updater-to-revit-area-number-parameters-issue/2413

Text value parameters seem to be updated fine, but number/area parameters are not.

**Comment by AlanRynne** [comment]
I just tested and cannot replicate either. I'm closing this since the user hasn't come back with more information about the specific case where it happened.

We can re-open if needed in the future 👍🏻

**Comment by AlanRynne** [comment]
😅  We're back up with some test files so I'm reopening it while I check them.

**Comment by teocomi** [comment]
Copied the file in here fyi: https://drive.google.com/drive/folders/1Om8w2vEVs__JPuRkQBjuI1L68i7yDm1k
