### ISSUE TITLE
🎥 Better `View` and `Camera` Support

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#1088]
as discussed with @clairekuang & @JR-Morgan, views and cameras are due for a bit of a proper rethink as they are a bit too revit / rhino centric

the working solution is to 
- simplify the `View` class into a single class in objects that can generally support apps like revit and rhino
- add an additional `Camera` class that inherits from view - this will add additional properties that are relevant to software like unreal, unity, and blender 

additional note: several props will remain as computed properties to avoid confusion (making ppl think they are editable) which in the (hopefully near) future should also be computed on viewer side

related to specklesystems/speckle-blender#84

**Comment by AlanRynne** [comment]
Must have a chat with @JR-Morgan  about this one 🙂

**Comment by paloknapo** [comment]
Closing as stale.
