### ISSUE TITLE
Material in Revit for MEP objects

### ISSUE THREAD

**Issue by thoffeller** [specklesystems/speckle-sharp#1099]
Hi specklers!
the new support for materials in connectors is fantastic! Thanks to @JR-Morgan and all in the team!
We need something similar for MEP elements. MEP elements itselve has no material. They end up in speckle in fatastic grey, regardless of the medium inside. Typically a freshwater supply pipe is green, a supply air duct is blue (all german standars, sorry) and so.
Currently most design compynies I knew implement this via display filters applied to specific views. I'm not sure if this is accessible via the api in revit.
The other option is the applied system. All MEP elements (except cable trays) have a system. This has a material. So we can suggest the MEP users to add valid materials to their models and they will end up with perfectly collored models in speckle.

Option 2, the system material approach, needs the modification for pipes, pipefittings, ducts, ductfittings, accessory and so to fetch the material from the system.

Now the question, do you want to implement it or shall we do it on our side and create a pull request?

Many greetings from sunny Germany,
Tim

**Comment by teocomi** [comment]
Hi Tim! 

This is not an area I have much experience with, but it sounds like picking the system material would be a safer option?

Happy for you to make a PR, and thanks for the suggestion!

**Comment by teocomi** [comment]
Thanks, we'll check in the next few days!
