### ISSUE TITLE
Repalace GetDynamicMembers and GetInstanceMembers methods

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#112]
**Brief intro to the problem:**

The Expand Speckle Object is not picking up instance fields because it's only looking for dynamic members: https://github.com/specklesystems/speckle-sharp/blob/master/ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObject.cs#L79

This is an issue with BuiltElement schema classes (img at the bottom). A similar issue appeared in Dynamo when receiveing an unknown object and its properties are expanded in a dictionary.

**Proposed solution:**  

I'd suggest introducing an `[SchemaVisibility(Enum.Visibility)]` attribute with a couple of values eg:
- Enum.Visibility.Hidden
- Enum.Visibility.Internal
- Enum.Visibility.Visible

This attribute would replace  the `[SchemaBuilderIgnore]` attribute I just created. And to add it to various sensitive fields eg `speckle_type`, `id` etc...

Then we can repalace the `GetDynamicMembers` and `GetInstanceMembers` methods with a `GetMembers(Enum.Visibility)`, so that we have more flexibility when requesting the members of an object (by default visibility would be `visible`).

Thoughts?

![image](https://user-images.githubusercontent.com/2679513/99284799-a06c7080-282e-11eb-9875-734aedddba73.png)

**Comment by didimitrie** [comment]
I need to get my head around the implications first as the changes proposed would affect a few things in core. First impression: it sounds more of an expand speckle object problem (first fix should be on the expand speckle object to take into account typed props too) rather than a core problem, albeit there might be bonuses re #102.

**Comment by teocomi** [comment]
We agreed to add an "ingore attribute" in a few places in Base already, so this new method would allow us to filter the props by that attribute before getting them rather than after. Agree the issue is mostly relevant to expand speckle object and the dynamo receiver.

**Comment by didimitrie** [comment]
@AlanRynne , if the expand object components do the dynamic props too, feel free to close this issue!

**Comment by AlanRynne** [comment]
It does! I think this was flagged in issue #121 and fixed.
