### ISSUE TITLE
[Archicad] Roof Support

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#1125]
would like to have a quick chat w perhaps @teocomi re how it is in revit
- kinda secret dynamic fields on the roof outline segments for `isSloped`, `slopeAngle`, `offset`
- need to be `RevitXRoof` to convert into revit - we prob needa generalise these conversions or archi roofs will needa inherit from revit roofs which is weird n smelly

**Comment by paloknapo** [comment]
https://github.com/specklesystems/speckle-sharp/issues/2278
