### ISSUE TITLE
Rhino: investigate layer filter updating and refresh in DUI2

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1141]
As reported in the community here: https://speckle.community/t/difficult-to-update-layer-list-in-connector-filter-by-layer/2557

**Comment by DuncanLithgow** [comment]
Thanks for opening this Claire. Here's an example

1. Set up a stream sending by layers
2. Select some sub layers, save, close
3. Rename the parent layer
4. reopen the stream for editing 

Note: the previously selected layers are not renamed
The previously selected layers cannot be un-selected (as currently named they don't exist)
