### ISSUE TITLE
Rhino: Conversion of PBR properties leads to very different looking materials.

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#1145]
Current implementation of Rhino material conversion is very lossy and often leads 
to materials looking very different in the viewer, particularly with Reflectivity --> metallic conversion.

We may need to rethink how we define Render Materials to better support Metallic and Specular workflows https://marmoset.co/posts/pbr-texture-conversion/

- [x] ToSpeckle - https://github.com/specklesystems/speckle-sharp/pull/1180
- [ ] ToNative -

**Comment by paloknapo** [comment]
Closing as stale.
