### ISSUE TITLE
Bug: Synchronous Receiver throws null reference exception on Grasshopper 2.4.2

### ISSUE THREAD

**Issue by secretlyagoblin** [specklesystems/speckle-sharp#1148]
![image](https://user-images.githubusercontent.com/13952064/160723530-e587f6ba-420c-48a0-be24-a5cb2400710d.png)

Using https://speckle.xyz/streams/a632e7a784/commits/6003488892

**Comment by teocomi** [comment]
Thanks @secretlyagoblin ! Quick ping to @psarras, as he's the author, to see if he has time to look into it.

**Comment by AlanRynne** [comment]
Had a quick peek and it was a no-brainer fix so i just went and made it since I had Grasshopper open.

It was also my changes to the conversion routine for the variable output receiver that broke it, so it's only fair  I fix it too! 👍🏻 

Thanks for reaching out on this @secretlyagoblin

**Comment by secretlyagoblin** [comment]
Cheers Alan!
