### ISSUE TITLE
Revit Performance Checklist

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#1153]
ToSpeckle
- [x] #1154
    - Frequent resizing of faces/vertices lists leads to **horrendous** performance.
- [ ] Views - P2
    - Creating a Revit plane in BoxToSpeckle is super slow for some reason (slow revit api),
    - We can implement something much faster!
    - We should address this when we reimplement View/Cameras #1088
- [ ] `GetHostedElements` kinda needlessly slow - P3
    - `GetHostedElements ` Requires two list searches which are super slow.
    - We could maybe minimise this down to 1.
    - or even better, use something that can be indexed by ID in constant time.

**Comment by paloknapo** [comment]
closing as stale, @JR-Morgan feel free to reopen if you plan to tackle this
