### ISSUE TITLE
JSON Schema generation from Object Kit classes

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#117]
@izzylys already started working on this, so she gets the hot potato! Ideally, we'd have a separate project next to objects that would allow us to automatically generate clean json schemas from all the classes in the Objects Kit. 

This is important as in the future we'll want to publish these schemas online, and rely on them for all the classes in other sdks (python, js/typescript, etc.).

**Comment by daviddekoning** [comment]
@izzylys - Hugh Groves has done this for the [Speckle 1.0 structural schema](https://arup-group.github.io/speckleGSA/docs/schema). Feel free to reach out to him if you'd like to compare notes.

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
