### ISSUE TITLE
Make units non-optional in object constructors

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#118]
The `units` parameter in the constructors of our geometry and built elem classes is currently optional, we have discussed making it mandatory to prevent possible unit mis-matches when forgetting to pass it.

The downside is a less pleasant programmatic creation of objects in a unitless environment, but this should be a quite contained use case.

This issue is a placeholder for a discussion more than anything!

**Comment by didimitrie** [comment]
AFAIK this was discussed in a standup last year; we decided to default to `meters`. Can be reopened if i'm wrong.
