### ISSUE TITLE
Revit: preview data to be received

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1182]
As a user I would like to:
- preview the geometry that will be generated before it is actually received
- know how many and what elements will be created/deleted/updated during the receive operation

**Comment by RobClaessensRHDHV** [comment]
Sounds good!
For our workflows, I think we would especially benefit from the second point; being able to see which objects are created/updated etc. Of course it would be nice to also see the actual updates within an object, e.g. changes of attributes and/or parameters.

**Comment by teocomi** [comment]
This method seems to be used to generate previews in Rhino Inside and other tools: https://www.revitapidocs.com/2021.1/7709521d-9954-ef80-1f13-3bc6ee660d5d.htm

We can also look at how Dynamo does it.

Txs @AlanRynne

**Comment by AlanRynne** [comment]
Here's the abstract implementation of Rhino.Inside:

https://github.com/mcneel/rhino.inside-revit/blob/888d322491fe59568ca11be27a5c33b327edb90f/src/RhinoInside.Revit/DirectContext3DServer.cs

And it's actual implemented class:

https://github.com/mcneel/rhino.inside-revit/blob/888d322491fe59568ca11be27a5c33b327edb90f/src/RhinoInside.Revit/GH/PreviewServer.cs

**Comment by RobClaessensRHDHV** [comment]
This implementation seems to only be aimed at previewing the 3D geometry within Revit.
I believe that this would already be a cool addition.

However, in our current workflow that we're trying to streamline, we're focussing a lot on updating parameters of Rooms/Spaces etc., based on calculations that are done outside Revit. For this purpose, it would be really nice to get a preview of parameter changes within Rooms/Spaces or essentially any object in the model. This would probably require quite some additional coding compared to the 3D rendering only, or it could be totally separate functionality of the connector.

I can imagine that a preview of the 3D model is more interesting for the majority of the users though, would be nice to hear some more opinions on this!

**Comment by teocomi** [comment]
@RobClaessensRHDHV thanks for this, @clairekuang is indeed working on an updated report that should help you better understand the changes in a "written" from as well.

**Comment by teocomi** [comment]
Spoke with a user today (Jabari) who mentioned the need to diff stuff in Revit, I guess the preview mode could also serve this need very well as we can use it to show elements that will be created, edited, deleted etc...
