### ISSUE TITLE
Revit '22 stream receive: Conversion error: Room boundary line creation failed

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-sharp#1193]
Revit '22 RAC Basic Sample streamed to Revit '22 as a test gives some errors I think would be worth looking into. I understand this example is a narrow use cases but still a problem worth handling - for example if we want to be able to create Room Separation Lines from other software - this is for example useful if room planing is done in other software and geometry is then built in Revit based on that.

Conversion errors
Room boundary line creation failed
View is not valid for room boundary creation failed

The problem here is that Room Separation Lines (the correct name for them in Revit) cannot be created if the active view is anything other than a plan.

Suggestion:
Usually there will already be levels for the inbound stream, usually these levels will have at least one Floor Plan. I suggest Speckle always open the appropriate view before adding the Room Separation Lines. If the level does not exist I understand Speckle already handles this, I suggest that in this case a new views is created from the appropriate view and used to create the Room Separation Lines. The view can safely be deleted afterwards. Here's the basic version

- need to create a room separation line
- check if level exists
- - yes: check if Floor Plan view exists for level
- - - yes: open and use floor plan view for creation of separation lines.
- - - no: create new Floor Plan view on level. Delete view after use
- -no: create level and view, use as above (delete speckle-created view)

I hope this is useful

**Comment by teocomi** [comment]
> The problem here is that Room Separation Lines (the correct name for them in Revit) cannot be created if the active view is anything other than a plan.

I think we missed this detail! And thanks Autodesk 😣

**Comment by Mehdi-Lucas** [comment]
Hello, I can take this. I have a WIP fix that will do what was suggested by @DuncanLithgow. 
✔️ = followed this instruction
ℹ️ = modified this instruction

    need to create a room separation line
    check if level exists ✔️
        yes: check if Floor Plan view exists for level ✔️
            yes: open and use floor plan view for creation of separation lines. ℹ️ No need to open the floor plan view, just pass it as a param to the creation method
            no: create new Floor Plan view on level. Delete view after use ✔️
    -no: create level and view, use as above (delete speckle-created view) ℹ️ in this case the view isn't deleted after drawing as this seems to be the Speckle receive operation logic (if level doesn't exist when receiving, create it and create a permanent view for it)

Here is a gif that show a receive operation for seprations lines for 5 floors, the file contain only 1 floor view (the needed addtional view are created and deleted but they never show up in the project browser). As you can see no need to change view (creation  is done from the 3d view):
![boundaryLinesViewFix2](https://user-images.githubusercontent.com/71726210/218441110-03611d97-b82e-4fe6-8643-0eaa16c3c178.gif)

If the team is ok with this I can open a PR (just let me know what branch to target). 
PS: I'll do it after https://github.com/specklesystems/speckle-sharp/pull/2136 is merged as this fix is required for this to work

**Comment by teocomi** [comment]
Awesome, thanks @Mehdi-Lucas ! You can branch off from `main` and then target the (yet to be created) `dev` branch when the PR is ready :)

**Comment by paloknapo** [comment]
fixed
