### ISSUE TITLE
Please add an option to export conversion error (and other errors)

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-sharp#1194]
Please add an option to export conversion error (and other errors). I suggest an option to export to .csv & .ods

If the log is already saved somewhere please add a button to "open the log file"

**Comment by teocomi** [comment]
We're planning a revamp of our "report" feature and will make sure to include your suggestions.
Thanks! Cc @clairekuang

**Comment by teocomi** [comment]
We have added a copy to clipboard option, closing for now!
