### ISSUE TITLE
Revit receive stream - test for conversion errors without receiving

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-sharp#1195]
Revit receive stream - test for conversion errors without receiving

It would be great if there was a way to test a stream for error rather than speckle aggressively creating objects it already knows are going to be incorrect.

Then a user can go through creating missing types of objects before testing the stream again.

Here I am assuming the same problem will (eventually) also arise when trying to create defined families and types from other software.

If this is only ever relevant as a Revit-Revit problem then I suggest this is a very low priority for core-devs.

**Comment by teocomi** [comment]
Definitely agree! This is actually part of https://github.com/specklesystems/speckle-sharp/issues/1182
So I'll close this issue and you can keep following the other one ;)
