### ISSUE TITLE
RevitConverter expects RevitWallOpening´s outline to be of type Polyline

### ISSUE THREAD

**Issue by tlmnrnhrdt** [specklesystems/speckle-sharp#1199]
`ConvertOpening` complains when the outline of a `RevitWallOpening` is not of type `Polyline`, but the constructor allows any kind of `ICurve`. I guess that is not intended behavior?!

**Comment by teocomi** [comment]
Hey @tlmnrnhrdt thanks for spotting it, we could actually update that to be a `Polyline`. The Revit API actually expects a rectangle, but we haven't rectangles that in our schema.

Cc @AlanRynne who has worked on openings recently, he'll pick it up after the holidays :)

**Comment by tlmnrnhrdt** [comment]
Hi @teocomi, great!

What is with https://github.com/specklesystems/speckle-sharp/issues/1200, which would be more important for our Openbuildings to Revit workflow ;)

**Comment by AlanRynne** [comment]
Hey @tlmnrnhrdt,

I'm working on a quick fix for this but it's giving me more trouble than I initially anticipated, so it may not make it for the next release.

I'll definitely try to get it working so we'd enforce this in both sides (grasshopper on this issue, and revit on #1200 )

**Comment by tlmnrnhrdt** [comment]
Hey @AlanRynne,
no worries, it´s not that urgent ;)
We just use 5 points for a rectangle for the time being..

**Comment by AlanRynne** [comment]
The 5 point check in Revit reported in #1200 will be fixed though. Just the GH side that's not liking me today. 👍🏻  So you could send your normal Speckle rectangles and have them work :)
