### ISSUE TITLE
SAP2000  vs Rhino Problem 

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#1201]
Installing both connectors will break SAP2000, (CSI products which run as a seperate process , ETABS used to be here but changed for now)

Something not loading correctly with default kits

**Comment by teocomi** [comment]
Is this still a valid issue?

**Comment by Reynold-Chan** [comment]
need testing to see if it is , but most likely yes unless something changed with the way kits are loaded
