### ISSUE TITLE
Breps: possible serialisation issues when encoding from Grasshopper?

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#1210]
Might not be an issue, but just to check on this:

Received some breps as a json dump and when deserialising in py, I realised some of the brep value property lists / curve value lists were entirely floats when they should be a mix of floats and ints. I needed to cast to int some of the indices being used to step through the list to deserialise. I haven't had this issue with stuff from Rhino, so am not sure if this is known / expected in GH or not.

**Comment by AlanRynne** [comment]
I'm guessing we've fixed this already with the new c#/py Brep alignment!! Going to close it but feel free to reopen if i'm wrong.
