### ISSUE TITLE
GH <> DYN alignment

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#122]
Node names, descriptions, general behaviours etc...

**Comment by AlanRynne** [comment]
After merging in PR #192 this is pretty much done! I'm just keeping it open to do a final review and ensure nothing has diverged.

**Comment by teocomi** [comment]
Sweet, did you also check input names tooltips etc?

**Comment by teocomi** [comment]
I looked a bit into this, here's a few minor outstanding bits:

Grasshopper
- [ ] move local send and receive to the "Speckle 2 Dev" ribbon under a "Local" tab
- [ ] add "Account Details" node
- [ ] rename input ports of serialization and conversion nodes. I'd suggest B = base, D = data, J = Json
- [ ] Streams.Get could be changed to work like the Dynamo one: it could accept stream IDs AND StreamWrappers. This would allow users with multiple accounts on a  server to get a stream with a different account
- [ ] Streams.List could by default return streams of the default account and not require that input


Dynamo
- [ ] add scheme builder component, see #205
- [ ] rename "Stream.GetWithAccoubnt" to just "Stream.Get"
- [ ]  Streams.Get doesn't actually work as I expected, should support both StreamIDs and Stream Wrappers
- [ ] rename input to just "Stream" in ServerTransport
- [ ] "MemoryTransport" the name input should be optional



![image](https://user-images.githubusercontent.com/2679513/106590615-3453fb80-6545-11eb-8d0e-a07a25841a93.png)
![image](https://user-images.githubusercontent.com/2679513/106590694-4b92e900-6545-11eb-8990-d1301037e1a0.png)

**Comment by AlanRynne** [comment]
Merged in #217 with all the GH side stuff

**Comment by teocomi** [comment]
Closing as the schema builder stuff has its own issue!

**Comment by teocomi** [comment]
Reopening this as I think the account details got lost @AlanRynne :/

**Comment by AlanRynne** [comment]
🤔 It is there! Apparently the next merge replaced that line in the csproj 🤷🏻 Doing a quick PR to close this

https://github.com/specklesystems/speckle-sharp/commit/2ba7f827f8940f72ba4c435f530e4dab3844497a#diff-dff20b243514d6c12f91b7010ce4c6891b6fb7135461b2aa9697847bfc6e2d9e
