### ISSUE TITLE
Grasshopper is still sending `displayMesh` instead of `displayValue` on Breps

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#1223]
`displayMesh` has been depreciated, so this should be reflected in grasshopper

**Comment by AlanRynne** [comment]
Ok got it! This is not an issue with the GH conversions, but with the `ExpandSpeckleObject` not ignoring the properties that have been flagged as `Obsolete` such as `DisplayMesh`.

https://github.com/specklesystems/speckle-sharp/blob/ccad89d4b636521a4c1b1bc11df65fbc3d830602/Objects/Objects/Geometry/Brep.cs#L366-L373

![Screenshot 2022-04-27 at 11 48 48](https://user-images.githubusercontent.com/2316535/165491610-38acc5d4-4310-42ab-a0ff-c1d0c9526f5e.png)

**Comment by AlanRynne** [comment]
Minor blocker on this, as the best solution would be to modify `GetMemberNames()` In dynamic base to exclude obsolete members.

Alternative would be to also attach the `SchemaInfo` attribute to all `displayMesh` props in every object that has it.

I'd vote for modifying `GetMemberNames()` as there is no reason to return obsolete members.

Result should look like so 👇🏼
![Screenshot 2022-04-27 at 12 08 44](https://user-images.githubusercontent.com/2316535/165497812-ccc50aa8-0af6-4f71-906a-1292fd92fb8c.png)
