### ISSUE TITLE
Core: __closure table inside the object is not an elegant solution

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#1225]
Larger structural issue around all SDKs & Server: 

__closure table inside the object can be a major limitation: if you have an object with 83k children in the closure table, just the __closure: ... occupies 83638 * 38 = 3 MB of storage (10 MB is the object limit).  Some objects can have orders of magnitude more children, for large streams (copy pasted from @cristi8's discord message). 

No easy fix, but logging so we're aware.

**Comment by AlanRynne** [comment]
Closing, we "fixed" this by bumping the object limit.
