### ISSUE TITLE
Core: optimize the serialization of the same instances

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#1226]
we should definitely optimize the serialization of the same instances, to use the previously computed id instead of re-serializing. 

Possibly using `.GetHashCode()` to identify wether it's the same object reference. Digging needed as IIRC this method would get the same hash code for different objects pointing to the same instance, but unsure how this _actually_ works.

**Comment by AlanRynne** [comment]
Leaving this open to verify the new Instancing implementation (which may not optimise on serialisation, just on conversion)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
