### ISSUE TITLE
Add support for proxy entities in Acad

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1228]
https://speckle.community/t/acad-proxy-entity-not-being-sent-to-speckle/2818/2

**Comment by clairekuang** [comment]
Personally I don't think we should support this anytime soon - it opens a whole can of worms for supporting imported geometry authored in other applications or plugins

**Comment by teocomi** [comment]
Should we maybe add support for sending at least?
I have no clue how proxy entities work but, sending their geometry and metadata should be pretty straightforward?
