### ISSUE TITLE
Dynamo transport nodes not working on receive

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1229]
It seems like the logic to handle transports other than Server is missing in the receive node.
Ref: https://speckle.community/t/dynamo-transport-nodes/2816/4

**Comment by AlanRynne** [comment]
![Screenshot 2022-05-05 at 11 38 33](https://user-images.githubusercontent.com/2316535/166898089-dcde1c2a-ed07-4a1e-b4a1-f410bc1c49fc.png)

This is what I'm getting on Safari. Not sure what to make of it yet

**Comment by paloknapo** [comment]
Closing as stale.
