### ISSUE TITLE
Duct Insulations category not supported

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-sharp#1233]
Please consider adding the Duct Insulations Category to supported categories in the connector.

Duct Insulations are important for being able to run meaningful collision control in other software. They also often allow for easy application of materials to whole ventilation duct systems without catching each category separately.

**Comment by teocomi** [comment]
Added support for this and the other missing categories!
I have also made a pre-release called `2.5.3-categories` that you can use to test it, it should be available soon.

Thanks for reporting!
