### ISSUE TITLE
Connector Releases website doesn't appear to work in Safari/Webkit

### ISSUE THREAD

**Issue by philipbelesky** [specklesystems/speckle-sharp#1237]
Hey, sorry if this is the wrong repo - I couldn't find anything specific to the netlify app that distributes downloads.

Anyway, when accessing speckle-releases.netlify.app from Safari 15.4 I get a `SyntaxError: Invalid regular expression: invalid group specifier name` and this seemingly prevents any content loading (the page ends up blank). The same blank page behaviour shows up when accessed on iOS, but the same page works fine on anything Chromium based. I'm 80% sure this isn't related to any kind of content blocker or extensions on my end. 

Unfortunately, I don't use Safari for web dev, so I'm not immediately sure how to un-minify `app.js` into a form where I could pinpoint what is actually causing the throw. If this is non-trivial to debug on your end, let me know and I should be able to find some time to look into it.

**Comment by teocomi** [comment]
Thanks for the report! @AlanRynne or I will investigate :)

**Comment by AlanRynne** [comment]
![image](https://user-images.githubusercontent.com/2316535/166898241-429a4af3-9478-46b2-a927-f1b5f2dd75c3.png)

This is what I'm getting on my side. Not sure what to make of it yet but I'll investigate what could be causing it.

**Comment by teocomi** [comment]
Turns out Safari does not support lookbehind regular expressions 🤦‍♂️, it's been fixed!
