### ISSUE TITLE
Revit Connector 2.5.2 crashed my Revit '22

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-sharp#1253]
I have Revit Connector 2.5.2 and Revit 2022 bim360. I was trying to send "everything to main" and Revit hard crashed.

I have a Revit journal file which might to show some problems, but not sure how to get it to you.

The send was nothing special, see attached image:
![billede](https://user-images.githubusercontent.com/3223028/168596662-150f5366-deee-455e-81ca-f051df232bbd.png)

:...(

**Comment by DuncanLithgow** [comment]
Actually pretty much every stream i try and send is crashing at the moment.

**Comment by didimitrie** [comment]
As well a minimally file where this happens would help if it's easy!

**Comment by DuncanLithgow** [comment]
The 'Objects' folder is attached.
My SSUID is 24ee0a37-dd98-46e2-b87a-683e62506681
[Objects.zip](https://github.com/specklesystems/speckle-sharp/files/8702205/Objects.zip)

Revit is not always crashing sending the stream now that I have fewer elements in the selection. A minimal Revit file would not be so easy unless we can isolate the problem to a limited aspect. What do you think about me trying to export one Revit category at a time to see if there's an object in Revit causing the problem? Is that something that could be a problem?

**Comment by teocomi** [comment]
Thanks for sharing @DuncanLithgow !

If the revit file doesn not contain sensitive data you can send it all, and we'll take care of nailing down the problematic elements while debugging. Alternatively yes, using the catagory or manual selection filter to isolate elements might help us get closer to a solution too!

**Comment by DuncanLithgow** [comment]
@teocomi I could send the file to you, but not publicly on github. How would you like me to send the file? Would be great if you could debug it, I really don't have time and am trying to impress my colleagues :-)

**Comment by teocomi** [comment]
Email with a link to a google drive/dropbox or similar works great, thanks!

**Comment by DuncanLithgow** [comment]
I don't know what caused this, but it has stopped once I started sending much smaller packets of objects from Revit, which is a perfectly fine workaround for me. I'll test this again when the next version of the Revit connector is released and see if there is a problem.

**Comment by teocomi** [comment]
Thanks, yes let's keep an eye on it, we should definitely be supporting larger packets too!
