### ISSUE TITLE
Issues receiving IFC in Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1261]
See: https://speckle.community/t/ifc-to-revit-family/2919

I've debugged the stream and found two issues:

- the material is coming through without a name - @JR-Morgan not sure if we can enforce this or should handle materials without a name gracefully ([see](https://github.com/specklesystems/speckle-sharp/blob/869dcbde46c915b51e2ba717241277bd4293d039/Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs#L912))
- the mesh conversion seems to fail [here](https://github.com/specklesystems/speckle-sharp/blob/869dcbde46c915b51e2ba717241277bd4293d039/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertGeometry.cs#L556) with a fatal error :( we should see if it's just a Revit thing or a malformatted IFC mesh

**Comment by paloknapo** [comment]
Closing as stale.
