### ISSUE TITLE
GH connector 2.5.2 - cannot find entry point in dll

### ISSUE THREAD

**Issue by weitingkong** [specklesystems/speckle-sharp#1265]
Connector was working fine before update... Now send / Receive nodes are throwing up errors saying cannot find entry point in dll:

![image](https://user-images.githubusercontent.com/44775273/169341875-f108baed-2dd3-4831-b68f-899c30d6748b.png)

**Comment by teocomi** [comment]
Can you please confirm if you have the following dll in your machine:

`%appdata%\Grasshopper\Libraries\SpeckleGrasshopper2\x64\SQLite.Interop.dll` ?

![image](https://user-images.githubusercontent.com/2679513/169353611-053ea5eb-2a6d-4d57-9f4e-511a579bfc05.png)


Have you installed any other GH plugin using SQLite?

**Comment by weitingkong** [comment]
yes:
![image](https://user-images.githubusercontent.com/44775273/169363510-872386b5-a49d-40a3-96c3-5795a8a3edb5.png)

and no not aware of any other GH plugin using SQLite

**Comment by teocomi** [comment]
Did some googling and it could be an issue in the updated version of SQlite...! https://stackoverflow.com/a/70152956
We'll downgrade and make a beta release for you to test if that's fine?

**Comment by weitingkong** [comment]
sure, that'll be great!

**Comment by teocomi** [comment]
Thanks @weitingkong ! You can get the pre-release called `2.5.3-sqlite` from manager or our release page

![image](https://user-images.githubusercontent.com/2679513/169496606-e09f6e26-85b8-42f6-904a-2ed8aaa4fb0c.png)

**Comment by weitingkong** [comment]
thanks, I think that's done the trick! 😃

**Comment by teocomi** [comment]
Great! Will ship the fix in the next stable release :)
