### ISSUE TITLE
TSEP Tekla installer

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1268]
Investigate how the Tekla installer can be improved to be following more of the usual conventions, eg [Tekla-TSEP](https://developer.tekla.com/tekla-structures/documentation/working-tsep). See also [Tekla-TSEP-extension-builder](https://github.com/PetteriVilla/Tekla-TSEP-extension-builder).

It currently throws an error (after install or on startup) which makes a lot of users believe it's not working correctly.

**Comment by Reynold-Chan** [comment]
working on with TSEP and xml generation

**Comment by teocomi** [comment]
Can this be closed now?

**Comment by teocomi** [comment]
@Reynold-Chan it seems we are still shipping the inno setup version of the Tekla installer, let's keep this open until the TSEP is officially supported.

**Comment by paloknapo** [comment]
closing as stale
