### ISSUE TITLE
Any plan for .NET6 SDK Style ? 

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1273]
Dear @teocomi, 
I have a question, we have any plan to update use NET6- visual studio 2022 with target framework .net48 for Revit or not ? 
I want colab something to improve structural Revit project and some process use CI/CD. Is your team willing to let me improve this and will it affect your team's workflow? 
This is a sample project developed: https://github.com/chuongmep/RevitAddInManager
![image](https://user-images.githubusercontent.com/31106432/170010320-dfdc7927-4038-4ecc-80af-ccce5d29d429.png)

**Comment by chuongmep** [comment]
> 
It still is net 4.6 or 4.8 but in file config is net6 style, it shorter and easier for expand product in future.

**Comment by chuongmep** [comment]
@teocomi see example in my branch : https://github.com/chuongmep/speckle-sharp/blob/d1e9796e9e86ac4d2fabfa9ec200519f2e495cb9/ConnectorRevit/ConnectorRevit/ConnectorRevit.csproj#L4-L49

**Comment by teocomi** [comment]
Ah, thanks! This is actually how we had the multiple projects set up in the past, with multiple build configs, but we decided to move and use the shared projects instead as it gives us a bit more control and it's easier to work within our CI/CD setup.

**Comment by chuongmep** [comment]
Thanks you @teocomi .
