### ISSUE TITLE
MacOS: Top-menu dropdown's stop working when Speckle loads

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1277]
# Description

This issue is related to the hijacking of the App menu name issue, it may even be the same root cause.

Our Speckle DUI window is somehow hijacking the menu-bar of Rhino somewhere between calling `Start()` and when `CreateOrFocusSpeckle()` is called.

Someone at Avalonia also suggested in the past that we use `SetupWithoutStarting()` instead of `Start()`, but that doesn't seem to have any effect.

This leads to the top-menu's not displaying the dropdown when clicked.

This doesn't seem to affect Rhino at all, all commands and buttons in the main rhino window work.

# How to reproduce

In order to reproduce the issue:

1. Install latest Speckle Rhino for Mac
2. Start Rhino
3. You'll see the Rhinoceros menu is now actually called "Speckle". Click it to open it.
4. Now start Speckle by writing "Speckle" in the Rhino command line.

Once the window opens:
- The app menu is back to being named Rhinoceros
- None of the other top-menu's work.

![2022-05-26 09 15 22](https://user-images.githubusercontent.com/2316535/170439711-6a23c8ac-4323-439d-a3b4-36e0253ffba2.gif)

## How to get the menus to work

To get the menus to work, you just need to open any of the top menus before starting Speckle:

![2022-05-26 09 17 54](https://user-images.githubusercontent.com/2316535/170439793-cf43d8d4-4de7-400c-8e45-7b5f72e43f4e.gif)

**Comment by jsdbroughton** [comment]
This isn't a zero affect other than UI. The speckle for rhino plug-in leaves a process running that causes a crash on quit. Grasshopper is not affected.

**Comment by AlanRynne** [comment]
Latest version seems to have fixed the "locked up menus" problem.

The crash on exit persists, and Avalonia people are looking into it.
