### ISSUE TITLE
Cannot add a dynamic property to Base objects named "Item"

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#1281]
Using: Nuget Speckle.Core 2.5.2
Targetting: .NET 4.7.2

When adding dynamically named properties to a Base, using "Item" as a property name throws an exception regardless of the object added.

**Minimal use case**:
```
Base baseObject = new Base();
baseObject["Item"] = object
```

I'm adding the exception I precis form as largely it is related not to Speckle but to `System.Dynamic` and the trace was long.
```
Exception: SpeckleException "Parameter count mismatch" something something set_Item
```

I'm guessing it is related to the comments in DynamicBase around member names named "Item" but I couldn't see any impediment within the setter specifically.

**Workaround**
Error surfaced as the most primitive object property set for Navisworks is "Item". It isn't crucial to keep the name strict so I've added a conditional that uses "NavisItem" instead of "Item". 

**Proposed Action**
If "Item" is reserved then the docs should point this out and perhaps the `IsPropNameValid` method of DynamicBase include it within the validation.
If it is a bug then ...

**Comment by AlanRynne** [comment]
This has been "fixed" by @dim in https://github.com/specklesystems/speckle-sharp/pull/1422
