### ISSUE TITLE
Dock all the things

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1284]
Since we got dockable panels working in Revit and Rhino let's do so in all other connectors who support 'em:

- [ ] AutoCAD & Civi3d
- [ ] CSI products?
- [ ] Tekla?
- [ ] Bentley?
- [ ] more?

Some internal docs: https://www.notion.so/speckle/Dockable-panel-support-07b5cbfb6909499788f0fb6a27321641

**Comment by bimgeek** [comment]
- [ ] Sketchup

**Comment by teocomi** [comment]
Closing as stale
