### ISSUE TITLE
Rh <> Rh Brep Bugs

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#129]
Found ~~one~~ two issues :) Logging them here as it might be useful for later debugging. 

### 1. Geometry exceptions on weird trim:

![image](https://user-images.githubusercontent.com/7696515/100894623-985e3300-34b4-11eb-8f27-ccddc441fc4f.png)
(top is received, bottom is original)

Attached file: [BrepEdgecase.zip](https://github.com/specklesystems/speckle-sharp/files/5630381/BrepEdgecase.zip)

### 2. Units conversions

When receving a brep in a file with a different unit system, (untrimmed) surfaces go through fine, but breps (&trimmed surfaces) don't seem to like it:

![image](https://user-images.githubusercontent.com/7696515/101021144-6e197d80-3567-11eb-9f3b-cdf476528697.png)

The stream in question is here: https://staging.speckle.dev/streams/5486aa9fc7 I've shared it with you; easiest to reproduce is just pull in the latest commit of the main branch in a new file in which units are **not** meters.

**Comment by AlanRynne** [comment]
Uploading this to keep a log of whats going on with this bug.

First issue was related to us not keeping tabs of the trimmed domain for each BrepEdge. We now have a `Domain` prop in the `BrepEdge` that can be null if the edge represents the entire curve.

Fixing this issue also partially fixed the boat example. Although it still borks, it may be unrelated to the scaling, as I haven't found anything missing on that note. I opened the boat in 'mm' and everything seems to be "in place".

![Screenshot 2020-12-10 at 09 32 50](https://user-images.githubusercontent.com/2316535/101742285-be925d00-3aca-11eb-8e82-2698a45d9b5c.png)

**Comment by AlanRynne** [comment]
Fixed in #154! Forgot to link them
