### ISSUE TITLE
Apply block transforms during conversion in GH and Dynamo

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1296]
Use case: sending block meshes form sketchup or blocks form Acad.

**Comment by AlanRynne** [comment]
To expand on this before I forget, we threw around some ideas and initially i'm leaning towards adding a `geometry` dynamic prop to the `BlockInstance` with the transformed geometry.

Must ping @clairekuang as I have no idea how transforms were implemented though.

**Comment by clairekuang** [comment]
Conclusion from discord convo: this is ok as long as `geometry` is removed from `BlockInstance` before sending to Speckle

**Comment by AlanRynne** [comment]
Ooopsies!! Another one that was not properlly tagged in it's PR... (and yes, it's another one of my issues 🤦🏼‍♂️)

Merged in here: https://github.com/specklesystems/speckle-sharp/pull/1409
