### ISSUE TITLE
RVT: Include project origins in the Project Information class

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1299]
Requested in https://speckle.community/t/new-settings-page-feature-for-desktop-ui-2-test/2365/3

Transforming the geometry without providing the project origin makes it difficult to later federate models.

Adding these would make it easier to re-locate the models as necessary.

**Comment by teocomi** [comment]
Related to: https://github.com/specklesystems/speckle-sharp/issues/1187

**Comment by AlanRynne** [comment]
Added to #1187 as an extra bullet point. Closing this as duplicate.
