### ISSUE TITLE
DUI: Add Kit selection to each stream card

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1301]
Let's support hot-swappable kits in DUI!!

I'm planning some quick improvements for 3rd party developers to be able to create Kits faster, but that doesn't make sense until we allow for Kit selection in our most used Connectors.

Grasshopper already supports this on a per-component basis.

In DUI, it would make sense to add it as a setting of each StreamCard, with a dropdown to select which one to use.

Would be nice to modify the card interface to display (or hint) to what Kit each stream is using.

**Comment by teocomi** [comment]
The settings page would be a good place for this, but we'd need to think if/how to allow setting a default kit as well...

**Comment by AlanRynne** [comment]
Closing this, we can pick it up again once we tackle Kits for real ;)
