### ISSUE TITLE
Enhancement of ConverterRevit: Extracting material quantities and properties (incl. multi-material elements)

### ISSUE THREAD

**Issue by ks-cph** [specklesystems/speckle-sharp#1302]
**Problem:** The current Revit converter does not allow for retrieving quantities from an element consisting of multiple materials.

**Example:** A multi-layered wall does only have 1 Volume. However, for analysing quantities for cost-estimation or LCA we need exact quantities of each material.

**Enhancement:** I propose adding an object to the Base-object generated in *ConvertToSpeckle* in the *ConverterRevit*. It needs to be discussed how this quantity should be structured. It could either have a set of the materials with all their parameters and the quantities (volumes, area). Or - to begin with - just the material-id and quantities.

Please let me know what you think. I would be happy to contribute.

Thanks,
Kilian

**Comment by teocomi** [comment]
Hi Kilian, I'm fully in favor of this!

Ideally, we'd find a way to define the quantities and materials in a way that is not Revit specific so it can be applied also to elements coming from other BIM software.
We'll discuss how to best implement it internally, in the meantime feel free to start looking at what the Revit logic to get this information out would look like :)

@izzylys this could be a valid addition to our object cleanup.
@JR-Morgan would it make any sense to leverage the material properties we are already using for rendering?
