### ISSUE TITLE
Rhino Breps received as Meshes in Revit

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1305]
## Expected Behavior
Expected to receive Rhino breps as breps/freeforms in Revit. Below is created w RhinoInside👇.
![image](https://user-images.githubusercontent.com/51519350/173517807-93d48b06-9dc3-462e-ac62-fe587b944dff.png)

## Current Behavior
Received as meshes. (w ugly triangles)
![image](https://user-images.githubusercontent.com/51519350/173517854-11409043-8ce0-489e-987e-08126180bde6.png)

## Possible Solution
Either receive as breps or hide meshes.

## Files used
https://drive.google.com/drive/folders/1sJarZBggipVYhPkQPjO268BDYoiLRpty?usp=sharing

### Commit
https://latest.speckle.dev/streams/28dd9ad7ba/commits/d2eab77a10

@AlanRynne pinging u as we discussed about this

**Comment by AlanRynne** [comment]
Closing this, as it's related to the fix we're looking into in #1351
