### ISSUE TITLE
[Revit] `Everything` filter doesn't truly grab _everything_

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#1308]
Bit of a papercut, but I think it deserves it's own issue: the `Everything` filter in Revit doesn't truly grab _everything_. In most instances, sending `Everything` will yield different results from selecting everything in a 3D view and sending with a selection filter.

This can be seen in the Revit sample house we all love (stuff inside the house will be missing) and the current built elements test stream.

selection:
https://latest.speckle.dev/streams/c544db35f5/commits/8baaca9662

vs

everything:
https://latest.speckle.dev/streams/c544db35f5/commits/596076a4e6

**Comment by DuncanLithgow** [comment]
I'm not sure I understand this issue. Selecting what is in a view (driven by visibility graphics settings and lots of other things) is completely different from asking Speckle to 'send everything'. I would not expect them to act anything like the same. So if the intention is that they do the same thing then I think either the language or the behavior is confusing.

**Comment by teocomi** [comment]
Maybe we're getting lost in Revit terminology here! @izzylys 's original message was referring to some categories not being included in the `everything` filter, which I think is still an issue.

In regards to design options, I think we could:
- exclude design options from the `everything` filter
- add a new `design option` filter, so you can still send multiple ones at the same time if needed

WDYT @DuncanLithgow @connorivy ?

**Comment by DuncanLithgow** [comment]
If this discussion is about Categories then I would suggest the Design Options issue be separate.

As far as the 'everything' concept goes I still think everything should exclude non-primary design options.

(I think it's a separate discussion how to manage inclusion of Design Options, but something like the categories filters would be nice)

**Comment by bimgeek** [comment]
- [ ]  Audio Visual Devices
- [ ]  Casework
- [ ]  Curtain Panels
- [ ]  Curtain Wall Mullions
- [ ]  Entourage
- [ ]  Fire Protection
- [ ]  Food Service Equipment
- [ ]  Furniture
- [ ]  Furniture Systems
- [ ]  Hardscape
- [ ]  Mechanic Control Devices
- [ ]  Medical Equipment
- [ ]  Planting
- [ ]  Plumbing Equipment
- [ ]  Plumbing Fixtures
- [ ]  Ramps
- [ ]  Signage
- [ ]  Specialty Equipment
- [ ]  Structural Rebar Couplers
- [ ]  Temporary Structures
- [ ]  Vertical Circulation
