### ISSUE TITLE
Rhino: Prevent meshes with no vertices/faces from being sent

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1324]
This is a weird edge case, Namita found it while prepping the City model.

You can send a mesh with 0 vertices and 0 faces, but when receiving it back in Rhino it will fail to convert.

Best way to approach this I think would be to just not send them, and add this to the report.

**Comment by fraguada** [comment]
@AlanRynne @teocomi Seems ok when ui is in "Advanced Mode", but one click UI results in the following (on macos): 
<img width="378" alt="Screenshot 2022-11-23 at 14 47 52" src="https://user-images.githubusercontent.com/1014562/203563536-895f7b3e-5df1-4ae4-8c34-d97f7e436152.png">

Here is the adva
<img width="397" alt="Screenshot 2022-11-23 at 14 47 18" src="https://user-images.githubusercontent.com/1014562/203563581-6b39ec36-50cf-4c8c-baa6-c54ade204d6d.png">
nced UI:

**Comment by teocomi** [comment]
The one click UI mode sends:
- the current selection (if anything is selected)
- OR everything if nothing is selected
The actual sending and conversion logic is the same, so it's probably a matter of understanding what it's attempting to send?

Also, after using the one click, the stream should be saved and available in the advance mode...
