### ISSUE TITLE
[Grasshopper] RevitFamilyInstance - Optional Host Input Needed

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1328]
## Expected Behaviour
---
Some components in Revit (such as doors, windows and wall/face/floor based components) expects a host for placement. Optional input for "Host" needed for this kinda components.

As discussed here👇:
https://speckle.community/t/openings-voids-in-revitfloor-and-revitwall/3005/2

![image](https://user-images.githubusercontent.com/51519350/174237872-529b8710-9737-4284-ae80-e035af8e9c54.png)

## Current Behaviour
---
Currently there is no way to add components that needs a host.

## Current Behaviour
---
Optional input for "Host".

**Comment by bimgeek** [comment]
it works the other way around. you put element into a host as part of its elements list.
![image](https://user-images.githubusercontent.com/51519350/174244441-f2418756-2bb1-443a-ad29-210379427045.png)

**Comment by bimgeek** [comment]
we discussed this w Alan and adding a host input would make sense for adding new host based components to existing objects in Revit. atm you can only add host based families if their host is also created via Grasshopper.

**Comment by teocomi** [comment]
Agree, also, I believe we are not currently supporting all types of "hosted elements" properly!
A useful exercise would be to check which ones we're missing.

This could also be a potentially related issue: https://github.com/specklesystems/speckle-sharp/issues/586

**Comment by AlanRynne** [comment]
Closing, we can reopen when we tackle this back
