### ISSUE TITLE
GH Default Sqlite Transport should default to a different db 

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#133]
Currently the sqlite transport component is lazy and defaults to the local cache db. As this local cache db can grow in size, and thus will need flushing periodically, one cannot rely on it for local sending (causes surprise behaviours). 

We need to make sure the sqlite transport component defaults to a different database.

**Comment by AlanRynne** [comment]
We're settling for `UserLocalDefaultDb` as it seems self-explanatory.
