### ISSUE TITLE
[Rhino] NGon Mesh Faces are broken

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1336]
## Explanation
Imported a sketchup model into Rhino and sent it into Speckleverse. This is the Rhino model sent:
![image](https://user-images.githubusercontent.com/51519350/174565006-9e654398-9e9b-48c5-9f85-7adc470ad239.png)

This is how it looks like in the viewer👇:
![image](https://user-images.githubusercontent.com/51519350/174564795-f21db478-a568-4951-be76-f1101083c233.png)

Its not a viewer issue. When received back in Rhino, they come with broken meshes:
![image](https://user-images.githubusercontent.com/51519350/174565214-feac38fd-9f22-46f0-a800-9ac86ea5472e.png)

## Commits Used
https://latest.speckle.dev/streams/28dd9ad7ba/commits/38e7fbd2b0

## Files
[chair.zip](https://github.com/specklesystems/speckle-sharp/files/8939138/chair.zip)

**Comment by AlanRynne** [comment]
Closing after confirming with Bilal this is no longer an issue.
