### ISSUE TITLE
Gh: do not disable send and recive buttons after sending/receiving

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#135]
Currently the send button is disabled until new data is available to be pushed, but there are situations in which you just want to trigger a new flow upstream and therefore might need to send multiple times the same data.
Same goes for the receive button.

**Comment by didimitrie** [comment]
Agreed! The trick there is to double click that amazing button, and it will (IIRC) send/receive again. Happy to either: 
- document this behaviour and close this issue
- remove the double click behaviour and simply not disable the button, as suggested

**Comment by didimitrie** [comment]
@AlanRynne, you decide on this one ;)

**Comment by AlanRynne** [comment]
I think I'd go for this one 👇🏻  
> * remove the double click behaviour and simply not disable the button, as suggested

**Comment by teocomi** [comment]
Yes I agree, otherwise we'd have to implement a similar bvehaviour and disable the button in all the other connectors :)
