### ISSUE TITLE
Revit connector 2.6 crashed Revit '22

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-sharp#1352]
Just trying to send ''everything' from a view with only doors visible. This was a potentially catastrophic *hard crash* with no possibility to save my work or synchronize to central.

Please advise on how to collect debugging info.

24ee0a37-dd98-46e2-b87a-683e62506681

**Comment by DuncanLithgow** [comment]
See also https://speckle.community/t/speckle-crashing-revit-2020-and-2022/3379

**Comment by teocomi** [comment]
Hi @DuncanLithgow without a sample stream or reproducible steps we will not be able to help on this one.
Does the issue still occur in 2.7?
