### ISSUE TITLE
SpeckleBIM2Revit - Improvements

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1354]
- [ ]  Preserve Assigned Family Types
    
    When user assigns a type to a floor created via SpeckleBIM, we should preserve that type when updating the geometry. Take a look at the GIF below👇
![Revit_qwzY7eYQVz](https://user-images.githubusercontent.com/51519350/175977123-45b8ffc6-f6f9-4b30-8fa5-69c095582c44.gif)
    
- [ ]  Keep Hosted Elements
    
    Some elements in Revit needs a host. It can be a wall, floor, ceiling or a topography. As mentioned [here ](https://speckle.community/t/rhino-revit-for-landscape-architecture/2942/21?u=gokermu)by [mariuszhermansdorfer](https://speckle.community/u/mariuszhermansdorfer), we should keep them hosted while updating the geometry. Take a look at the image below.

Before Updating - Material applied to topography, trees added 
![image](https://user-images.githubusercontent.com/51519350/175977326-e50769de-2b5c-488a-814d-b357d59c1fb7.png)

After Updating - Materials are gone, trees are not hosted anymore.
![image](https://user-images.githubusercontent.com/51519350/175977520-2a5467aa-0171-4031-93ea-38a0e4e129e3.png)

**Comment by paloknapo** [comment]
to be reviewed with the latest Speckle Mapper development

**Comment by teocomi** [comment]
This should has been tackled in 2.14.
