### ISSUE TITLE
add option to toggle on/off sending the analysis object model for CSI and separate the filters

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#1360]

**Comment by Reynold-Chan** [comment]
seperate out the filters for analysis results from geometry

**Comment by teocomi** [comment]
Please add more context

**Comment by Reynold-Chan** [comment]
Need better filters to have more control over analysis results sent rather than just 1D,2D, etc... should be per a list of load combination . Need to scope out this feature more in details because may require additional advanced settings.

**Comment by AlanRynne** [comment]
Closing for now. @connorivy already added a setting to enable/disable sending results.

https://github.com/specklesystems/speckle-sharp/pull/2115
