### ISSUE TITLE
Room boundaries are not affected by Room Area computation

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1383]
## Description
As shown [here ](https://speckle.community/t/rooms-are-not-affected-by-room-area-computation/3133/3?u=gokermu)by MaxT, rooms sent to Speckle doesn't preserve their location /area calculation lines.
![image](https://user-images.githubusercontent.com/51519350/177306649-9250523a-1956-4f38-97d3-6c080fc4817f.png)
![image](https://user-images.githubusercontent.com/51519350/177306665-59b0a4ae-1a63-43a8-804d-d84ee36555b8.png)

## Usecase
For thermal simulations, zones needs to share a common surface and this would be one way to create such a shared surface. Also I need to merge zones into a single volume without walls and to to this I plan to use Topologic (in Blender) and Topologic also needs shared surfaces to do this.

**Comment by teocomi** [comment]
Seems like this setting cannot be retrieved from the API (AFAIK), but we could add it in `Advanced Settings` and then implement it like this:

```
      //see https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/Revit_API_Developers_Guide/Revit_Geometric_Elements/Geometry/Room_and_Space_Geometry.html
      SpatialElementBoundaryOptions spatialElementBoundaryOptions = new SpatialElementBoundaryOptions();
      spatialElementBoundaryOptions.SpatialElementBoundaryLocation = SpatialElementBoundaryLocation.Center;
      SpatialElementGeometryCalculator calculator = new SpatialElementGeometryCalculator(revitRoom.Document);
      SpatialElementGeometryResults results = calculator.CalculateSpatialElementGeometry(revitRoom);
      speckleRoom.displayValue = GetMeshesFromSolids(new List<Solid> { results.GetGeometry() }, revitRoom.Document);
```
