### ISSUE TITLE
Revit-Connector: Integrate conversion of phasing parameters

### ISSUE THREAD

**Issue by ks-cph** [specklesystems/speckle-sharp#1390]
The Revit-Connector misses phasing parameters.
I assume it is because phases aren't implemented in speckle-sharp.

I propose to add  `Objects.Other.Phase`(?) and implement it in the Converters such as `Objects.Other.Revit.RevitPhase`.

I expect that the phasing parameters will be serialized correctly. Or am I missing something?

**Comment by ks-cph** [comment]
Now I found the actual problem: The parameter is skipped as it points to another element. 
Have you put any thoughts on changing that?


https://github.com/specklesystems/speckle-sharp/blob/0b972a1a8425c8abb0f8935fa2abfa58c96f1aa6/Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs#L211-L213

**Comment by teocomi** [comment]
Hey @ks-cph ,

Yes we're doing so to avoid collecting too much "Revit Garbage™", as often it's not stuff the user cares about or that we could consume in Speckle-land easily if it's defined as an `element`.
I brainstormed quickly with @connorivy on this, and maybe we could just store the phase as text in Speckle, would that be enough for you?

**Comment by ks-cph** [comment]
Hey @teocomi ,
thanks for your response. 

From a Revit-perspective there can either just be a "Phase" parameter or a "Phase Created" and "Phase Demolished" parameter.
The phase itself has some parameters of which  the order of the phases may be of interest. 

I am not sure what you mean with:
> store the phase as text in Speckle
Adding the phases as text directly to all elements? or as string-parameters?

We can also create `Phase` in Speckle and add the phases to `element`. For me both works but I think on the long-run it should be better to implement it "properly".

**Comment by teocomi** [comment]
@izzylys are there phases in ArchiCAD too? If so, can you suggest a generic definition we could use here?

**Comment by ks-cph** [comment]
It is probably enough to have it as text. I checked IFC and there they also only have one parameter.

I will implement this in ```Objects.Converter.Revit.ConvertToSpeckle()``` I hope that will work

**Comment by teocomi** [comment]
Done in [#1691](https://github.com/specklesystems/speckle-sharp/pull/1691)
