### ISSUE TITLE
Rhino Connector: RhinoObject Name is not sent as a property

### ISSUE THREAD

**Issue by secretlyagoblin** [specklesystems/speckle-sharp#1410]
As far as I can tell, basically every property you could want is sent to Speckle when you upload from Rhino, except the name!

![image](https://user-images.githubusercontent.com/13952064/179174293-b930b5e5-aa86-499b-9043-b42e6e69bfa7.png)

**Comment by AlanRynne** [comment]
Interesting... thanks for bringing this up! I'll ping @clairekuang since she's the Rhino wizard 🧙🏻‍♀️

**Comment by clairekuang** [comment]
Will be merged with 2.7.0!
