### ISSUE TITLE
Receiving Closed Splines/Circles in Revit

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1413]
### Observed Behaviour

- Looks like every curve from Rhino gets converted to Nurbs. And circles are a special type of nurbs that is not supported by Revit (single closed spline). That is why any sketch element in Revit (floor, wall, ceiling etc.) cant be generated using that as a boundary. `Rhino.Inside` solves this problem by dividing any single closed splines into two and using that instead. We need to do the same thing somehow.

    ![image](https://user-images.githubusercontent.com/51519350/179248297-146975ab-7109-4bdd-921b-c2a03cee0dbb.png)
    This is the error i get while trying to receive a surface generated from above curve as a floor in Revit👇: 
    `The start and end knots must have multiplicity equal to degree + 1. Parameter name: knots`

- More importantly any brep that uses circle as a base doesn't received as breps but gets converted into mesh in Revit😥. Take a look at this simple cylinder from Rhino.

    ![image](https://user-images.githubusercontent.com/51519350/179247725-551783fe-f26b-47b4-81d1-314993a997b2.png)

    ![image](https://user-images.githubusercontent.com/51519350/179247779-25daec05-3743-4867-8d9c-8bc8fad506d4.png)

### Expected Behaviour

Obviously receive them as Breps in Revit.

### Commits Used
- https://speckle.xyz/streams/77e23c3edf/commits/67cbb841cb
- https://speckle.xyz/streams/77e23c3edf/commits/894b651df3

**Comment by paloknapo** [comment]
Parked for now, needs more technical scoping on handling conversions in Rhino.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
