### ISSUE TITLE
🏗 Better Builds while receiving geometry

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1414]
## Expected Behaviour

- Seeing geometry getting build feels a lot better than seeing Revit freeze. 
- It will also act as a progress bar ⬛⬛⬛⬜⬜ too. So instead of one huge transaction, maybe we can do subtransactions to achieve this effect👇.

    ![Revit_ICDqAl1252](https://user-images.githubusercontent.com/51519350/179254738-e15ccdb3-251c-4fe2-b3c5-dcf00f5076a0.gif)

## Observed Behaviour

- Depending on what you receive, connector and Revit freezes❄. Take a look at this gif👇:
    ![Revit_VQktmyVa6s](https://user-images.githubusercontent.com/51519350/179255286-9ba0a09c-d3bc-49f6-a617-1d61ca5ee067.gif)

**Comment by teocomi** [comment]
Related to: https://github.com/specklesystems/speckle-sharp/issues/1376
