### ISSUE TITLE
bug(dui2): rhino crashes during debug and release occasionally

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1420]
Thrown at this line: https://github.com/specklesystems/speckle-sharp/blob/d2cfe0fdf5dac5e5b1ae06f2f4a063cf33dc15ff/DesktopUI2/AvaloniaHwndHost/AvaloniaHwndHost.cs#L20

**Comment by teocomi** [comment]
Hey Claire, can you tell us how to repro? Is it happening when opening files, or doing any other panel operations?

**Comment by clairekuang** [comment]
It happens occasionally when debug, right after initialising the plug-in, before the panel loads. Haven’t encountered this recently however

**Comment by clairekuang** [comment]
Closing since I haven't encountered this issue since the last release
