### ISSUE TITLE
Fix receiving and sending percentages

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#143]
Something's wrong, and sometimes they go above 100%, at least in Dynamo, maybe in GH too.

**Comment by AlanRynne** [comment]
After a quick chat with Dim, this is what we think is going on:

- totalChildrenCount of objects does not include chunks, which is BAD
- on receiving the progress report is handled incorrectly (or emitted by transports incorrectly)
- (optional¿?) when receiving, for correct progress reports, one should always use the first object's total children count, not the commit's.

**Comment by teocomi** [comment]
Linked to #260
