### ISSUE TITLE
Revit MEP fittings should include a base curve

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1436]
Fittings are family instance elements and are sent to Speckle only including their base point, but it is possible also to extract their base curve (works in Dynamo see below), we should add it to our object model as well:

![image](https://user-images.githubusercontent.com/2679513/180275848-5302e153-40c0-4f73-9832-5550fc51368a.png)

Reported by Hao via email

**Comment by connorivy** [comment]
Stream containing elements in question: https://speckle.xyz/streams/642c2c8f9e/commits/ff228649f8?filter=%7B%22ghostOthers%22%3Atrue,%22filterBy%22%3A%7B%22category%22%3A%5B%22Pipe%20Fittings%22%5D%7D,%22colorBy%22%3Anull%7D
