### ISSUE TITLE
Kits folder issues when running network accounts

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1461]
A user is experiencing issues in GH & Rhino where the wrong Speckle/Kits folder is being used by our connectors:

- GH&Rhino are using `Default\AppData\Roaming\`
- BUT the files are installed in `<MyUser>\AppData\Roaming\`
- it also seems that Manager (v2) is using the `<MyUser>` one for account management

https://speckle.community/t/cant-find-speckle-kits-when-using-gh-sdk/3297/3
 
This is probably caused by[ using network service or local service accounts](https://stackoverflow.com/questions/2022430/specialfolder-applicationdata-returning-default-user).

### Potential solution
Since our code is using `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);` to retrieve the Speckle and Kits folder, a solution could be to switch and use `Environment.ExpandEnvironmentVariables("%AppData%")` instead.

**Comment by AlanRynne** [comment]
We fixed this in #1538 but I didn't find the issue then. Must have been looking for the wrong keywords.
