### ISSUE TITLE
Dockable panel initialization not working when launching Revit form a file

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1469]
If launching Revit by double-clicking on a Revit file (instead of first launching Revit and then opening a file) the initialization of the Dockable Panel is not working and throws `The requested dockable pane has not been created yet.`

This seems to be an issue with the Revit API as the panel under both circumstances is actually registered and initialized correctly.

As a matter of fact, as a workaround, **opening another Revit file** is correctly starting the dockable panel.

**Steps to repro**

1. Add command line args to launch revit file:

![image](https://user-images.githubusercontent.com/2679513/182321486-680b87e1-cf14-4b61-b586-a3e0d1f50ce9.png)

2. Click debug
3. After the project has been opened, click on the Speckle command

**Solution tried**

I tried to simplify, and force a re-registration of the panel when clicking on the ribbon button, to no avail.
I also tried changing when the panel is first initialized from the `Idle` to the a `ControlledApplication.ApplicationInitialized` event.

Some more details:

```
        var p1 = DockablePane.PaneIsRegistered(PanelId);  //true
        var p2 = DockablePane.PaneExists(PanelId); //false
        var p3 = App.AppInstance.GetDockablePane(PanelId); //throws "The requested dockable pane has not been created"
```

Also, no events like `DocumentOpened`, or `ViewActivated` are triggered under these circumstances.

![image](https://user-images.githubusercontent.com/2679513/182321026-00f14c5d-069a-421f-bc53-48a96fd10d36.png)

**Comment by teocomi** [comment]
Repro with minimal reproducible project: https://github.com/teocomi/DockableDialogBug

**Comment by teocomi** [comment]
This has been recognized as an issue by ADSK and has been logged internally by them as:

REVIT-195285 [Dockable Panel not registered correctly when Revit is opened from a file -- 19345692]

**Comment by teocomi** [comment]
Will reopen when we have a resolution from ADSK.

**Comment by GianClaudioScarafini** [comment]
Hi @teocomi ,

sorry to bother you.

I still have this issue when I am using a specific workflow, not speckle system related. I am extracting Revit Database info using a "ModelChecker\bestpractices-2023.xml" pointing to the central file where I want to extract information. 

the workflow works in this way. when I start the Revit session it automatically generate and excel file opning in the backgorung the central file.

so when I initialize the software I have this issue that keeps going to pup up even if I click on close.
![image](https://github.com/specklesystems/speckle-sharp/assets/77918123/67ed7633-9a23-4614-9dc4-cbf09e68632b)

can you please help me with that?

**Comment by Mehdi-Lucas** [comment]
Hello @teocomi, this issue is closed but I might have a working solution, I opened a [PR](https://github.com/specklesystems/speckle-sharp/pull/3255) :)

**Comment by teocomi** [comment]
Amazing! Thanks @Mehdi-Lucas, we appreciate it a lot. We'll have a look :)

**Comment by Mehdi-Lucas** [comment]
@teocomi No problem, fingers crossed that it performs as intended and proves helpful for you guys 🤞
