### ISSUE TITLE
Incorrect interval length calculation

### ISSUE THREAD

**Issue by timglewis** [specklesystems/speckle-sharp#1478]
I'm pretty sure this requires the following change to correctly calculate the interval length:

https://github.com/specklesystems/speckle-sharp/blob/a7c779049a437605033583252bc40dd17be07c62/Objects/Objects/Primitive/Interval.cs#L27

`[JsonIgnore] public double Length => Math.Abs((end ?? 0) - (start ?? 0));`

**Comment by teocomi** [comment]
Thanks for spotting @timglewis ! We'll review and get back to you soon :)

**Comment by AlanRynne** [comment]
🤕 True! Just making the fix now :) Thanks for bringing this up!

**Comment by AlanRynne** [comment]
Just merged this in! Should be fixed in our next upcoming release 👍🏻 

Thanks again!
