### ISSUE TITLE
Revit: duplicated elements when sending Groups

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1480]
If sending model groups using the "everything" filter, the elements inside the groups and nested families are sent twice:
- once as part of the group
- once individually as matching the filter by themselves

### To replicate:
Send everything from this model (revit 2022): https://drive.google.com/file/d/1Cxu303t6MVWwCqIwblXZrZqI7FRxZP8c/view?usp=sharing
Sample stream: https://latest.speckle.dev/streams/58f3b0e80a/commits/237593b55c

### Possible solutions
- using the `ContextObject` list we could check if any converter element is also belonging to a model group, this would likely have performance implications
- do not send model groups with the `everything` filter, which could lead to undesired results
- something else I'm not aware of, maybe using the filteredElementCollector....

Reported by @JR-Morgan

**Comment by Zhuangkh** [comment]
I think there is a simple solution to fix this problem by excluding elements with `GroupId`, but it caused another problem, if sending model by "category" filter, should we send the element of the matching category in the group?

**Comment by paloknapo** [comment]
review this one too https://github.com/specklesystems/speckle-sharp/issues/1631
