### ISSUE TITLE
Stuck on send - no progress or conversion

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1486]
### Description

Created a simple model with mesh topography and trees as blocks. Tried to send it to Speckle but it seems to stuck.

![Rhino_1Jov4VCQd8](https://user-images.githubusercontent.com/51519350/183394898-a0a74bb8-8ec7-406d-9ecb-b89ce3c5c849.gif)

## File used

https://drive.google.com/file/d/1ukSWK6L4NNY7BJAXBq3ztqW6zr9ZB9ur/view?usp=sharing

![Rhino_wXNInZBfiP](https://user-images.githubusercontent.com/51519350/183394953-37838dbd-3af0-4d9a-b4a9-8c4ce622cbde.png)

**Comment by clairekuang** [comment]
closed with #1487
