### ISSUE TITLE
Update file size to 25 MB instead of 10 MB 

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#1492]

**Comment by Reynold-Chan** [comment]
@gjedlicska

**Comment by gjedlicska** [comment]
Does this refer to the `MAX_OBJECT_SIZE` or the `MAX_MULTIPART_SIZE` value? Do we have an example of the exception message that is thrown?

**Comment by AlanRynne** [comment]
#1512 this fixed this issue already, we forgot to reference!
