### ISSUE TITLE
Grasshopper Connector - Handling TextToNative() conversion of Speckle.Objects.Other.Text 

### ISSUE THREAD

**Issue by d3ssy** [specklesystems/speckle-sharp#1495]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?
ConnectorGrasshopper

## Describe the bug
Speckle.Objects.Other.Text is not converted when deconstruction a Speckle Block in Grasshopper.

## To Reproduce
* Send a Rhino block from Rhino to Speckle
* Receive block from Speckle in Grasshopper  via connector
* Deconstruct Speckle Object
* Retrieve Blocks in Stream
* Deconstruct blocks
* Access Geometry property
* Text objects remain unconverted

## Expected behavior
* Convert the text objects to TextTags in Grasshopper, or just as plain text strings.

## Screenshots
![image](https://user-images.githubusercontent.com/6257186/183881365-125b1400-8ba0-49ed-aebf-d584dbd5ccb4.png)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: Windows 10

## Proposed Solution (if any)
* Add preprocessor directive and dedicated conversion method on converter:
* https://github.com/specklesystems/speckle-sharp/blob/b49fe366d75bfac5c704cabc8294c04295d2d6c0/Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs#L665

**Comment by AlanRynne** [comment]
Hey @d3ssy!

We don't convert text entities because Grasshopper does not have a direct translation of what `Text` actually does, which would lead to quite a lossy conversion.

What would your expected output of this conversion be in GH native types? Just the text?

Since our `Text` class also holds positioning information, we made the decision of not providing a direct conversion, and just allowing the users to expand the `text` object and pick the information they needed.

This may not be "ideal", and If you've got suggestions on how this should work we're happy to hear them! 😄

**Comment by d3ssy** [comment]
Could you move text (and others) to an additional output Other when the input to the DSO gh component is a block. All outputs in Other would not be converted.

**Comment by AlanRynne** [comment]
Hmm, that would be tricky, as it would be effectively changing the structure of the object being expanded, and this could conflict with an actual property called `Other` that a user may have created.

If you want to filter out non-converted objects I'd say just plug the output into a `Geometry` node and then filter by `null`? Or maybe I'm missing something in your use-case :)

**Comment by AlanRynne** [comment]
Closing this as we're not going to handle `Text` objects differently in Grasshopper for now.

If there is a need to be able to distinguish between what is a `Speckle object` and what is not, we could instead make the parameter `GH_SpeckleBase` public, so you could plug in a random list of objects, and anything that is not a `Base` object (i.e. anything that was not converted in your case) would be null.

If you feel like this would work for you, feel free to open a separate issue for this. Or reopen this one if you still think this a priority for you :)

**Comment by AlanRynne** [comment]
@d3ssy made a separate issue for that ☝🏼, should be quite a quick fix so it may go out on our next release `2.10`.

Thanks for the feedback!
