### ISSUE TITLE
Hosted families not converting correctly in Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1502]
Hosted families like windows are not converting and sending correctly in the current 2.8 alpha release.
It is also quite weird as the problem only occurs when not sending Everything.

Problems observed:
- hosted families are not sent when sending by View or Selection (they work when sending Everything)
- the report shows "Conversion returned null" for such families (not a very helpful error message)
- it sounds like they should have been converted as children of the host family, but that didn't trigger correctly?
- no such problem exists in 2.7

**Comment by bimgeek** [comment]
> - hosted families are not sent when sending by View or Selection (they work when sending Everything)

 @teocomi I don't think its related to sending by `View`, `Selection `or `Everything`. It doesn't work after the initial sent even when sent by `Everything`. see GIF below👇:
   
![Revit_ODNhyJyuj2](https://user-images.githubusercontent.com/51519350/184091604-fdacfce4-db56-4bb8-8191-4d38f4b0b6d7.gif)
 
### Stream Used

https://latest.speckle.dev/streams/62f7dfc963

### Files Used

If you want to test it on your end, download the file from following link and try to send FamilyInstances couple times.

https://drive.google.com/file/d/1yx8pg0jGewBGyxfygaLVJU6IIlRE7p1z/view?usp=sharing
