### ISSUE TITLE
Bug: Top Railing geometry not sent from Revit

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1507]
## What package are you referring to?

Revit Connector

## Describe the bug

Revit connector doesn't send top railing from Revit. See GIF below👇

## To Reproduce

1. Create a railing in Revit
2. Select it and send it to Speckleverse
3. Investigate it in the viewer or receive it in another software

## Expected behavior

I was expecting it to send it.

## Screenshots
![Revit_Nkcaz7jhoK](https://user-images.githubusercontent.com/51519350/184146038-34eea29e-072e-4467-8a4d-bc7052c0f27d.gif)

**Comment by Ibrahim5aad** [comment]
I think this is due to 'TopRail' elements aren't supported at the moment when converting to Speckle objects. 
 
![Screenshot 2022-08-25 143426](https://user-images.githubusercontent.com/50090593/186665889-60e1a64d-8427-47a7-b214-599970d0be4d.png)

**Comment by teocomi** [comment]
Hey @Ibrahim5aad ,

Thanks for looking into this :) If the `TopRail` and `HandRail` are hosted elements, then adding this might be enough to get them through: 

https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertWall.cs#L231

**Comment by Ibrahim5aad** [comment]
Hey @teocomi,

I'm glad I could help, I just started looking into Speckle and I'm looking forward to help on the open issues. 
But I'm afraid this won't do it `GetHostedElements` expects an element that is is/inherits from `HostObject` which is not the case with `Railing` elements. The relationship between `Railing` element associated `TopRail` can be checked by the `TopRail` property of the `Railing` element. And for the `HandRail` elements can be found with `GetHandRails` method.

This can help with the detection of those hosted elements. But for the conversion to Speckle object, a support for those elements has to be added to the `ConvertToSpeckle` method.
