### ISSUE TITLE
Point == null operator overload not working as expected

### ISSUE THREAD

**Issue by FerdiMeijer** [specklesystems/speckle-sharp#1516]
Hi I ran into a tiny issue and thought I should let you know.

In my app I was making sure the basepoint of a speckle revitfamilyinstance was not Null, because for some hosted objects it is.
This stopped working when I upgraded to speckle Objects version 2.7.0.

   var pointA = (Point)null;
   Debug.Assert(pointA == null, "Point is not null."); // fails

It probably has something to do with the fact that the '==' operator is overridden.
If have changed my code to "if(pointA is null)" and that is working.
Haven't tested the other operator overloads in combination with null.

I think this might be confusing for future developers who don't know the == is overridden.

**Comment by AlanRynne** [comment]
OH! That's a good catch @FerdiMeijer, thanks for bringing it up!

We'll look into this ASAP.

**Comment by JR-Morgan** [comment]
Something like this maybe?
```cs
public static bool operator ==(Point point1, Point point2) =>
      !(point1 is null ^ point2 is null) &&
      point1.units == point2.units &&
      point1.x == point2.x &&
      point1.y == point2.y &&
      point1.z == point2.z;
```

**Comment by FerdiMeijer** [comment]
Hi Jedd,

Looks like that would work, but overriding operators is hard, also don’t forget to look at the other operators that are overridden on the Point class.
If I had to fix this problem I would write unit tests for each different combination of points and null’s and the operator under test that I could imagine. That way I would have more confidence it will work in all cases out there in the wild 😊.

Greetings,
Ferdi
