### ISSUE TITLE
Block Conversion not checking for pre-existing instances

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1522]
Conversion routines in Revit should check if an element with the same ID has been received before and based on the user-selected received behavior either update, create or skip it.

Seems like this is not happening for [Block conversions](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertBlock.cs). 
Typically this is done by calling the var  `GetExistingElementByApplicationId()` method, eg: https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertBeam.cs#L44

See: https://speckle.community/t/revit-connector-duplicates-sketchup-groups/3401

**Comment by teocomi** [comment]
Should be a fairly simple one if @clairekuang or @izzylys you want to pick this up!

**Comment by jabarig** [comment]
Thanks @teocomi! 😀

Also, the Revit connector creates a "structural" generic model when receiving blocks from SU. Can it either be a mass family or a standard generic family?

![image](https://user-images.githubusercontent.com/5063609/184943989-69e21fad-7e4b-4748-94ac-7b88f6b8d6f2.png)

**Comment by teocomi** [comment]
Hey @jabarig, we can (should) surely remove the "structural" attribute - but in order to receive it as a different category, we might need to wait on our (WIP) mapping tool, which will eventually allow you to map to specific categories / types in Revit.

**Comment by jabarig** [comment]
Understood and no worries! I'll look forward to the mapping tool.
