### ISSUE TITLE
feat(civil3d): add autodesk.aec element conversions!

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1527]
## What package are you referring to?
 Civil3D connector

## Is your feature request related to a problem? Please describe.
 Currently unable to send ObjectARX loaded entities like walls and windows from Civil3d. These are loaded as ProxyEntitites when ObjectARX library loading is disabled

## Describe the solution you'd like
 Conversion support for the following builtelements:

- [ ] Wall
- [ ] Floor
- [ ] Pipe

**Comment by clairekuang** [comment]
Linked to and potentially conflicting with #1707

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
