### ISSUE TITLE
Investigate & add update mode cross-connectors

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1530]
We should investigate how and where we can bring the **update functionality on receive** that we currently only have in Revit (I believe).

See: https://speckle.community/t/speckle-should-be-able-to-update-existing-objects-in-the-dwg-file/3424/2

**Comment by clairekuang** [comment]
An update receive mode has been added for rhino, autocad, and civil3d!

**Comment by teocomi** [comment]
Update:
- [x] Revit
- [x] Rhino
- [x] Autocad
- [x] Civil 3D
- [ ] Structural connectors ? @Reynold-Chan

**Comment by clairekuang** [comment]
This seems to be closed - though we should document how this was implemented across each connector and how well round-tripping works for cross connector workflows
