### ISSUE TITLE
Trimmed Surfaces from AutoCAD on Viewer

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1539]
## What package are you referring to?

Speckle AutoCAD Connector

## Describe the bug

Trimmed surfaces from AutoCAD creates lines to origin point as we had in  #1441

## To Reproduce

1. Open attached file in AutoCAD
2. Select and send it to Speckleverse.
3. View it online

## Screenshots

![acad_Qu5LWv5UYy](https://user-images.githubusercontent.com/51519350/186180020-478409a7-212d-4afb-8a78-f5638bba48cb.gif)

## Files used
https://drive.google.com/open?id=1zS_TZmEnV-TJ9kUlTuDtIfCpN3U-sScQ&authuser=bilal%40speckle.systems&usp=drive_fs

**Comment by clairekuang** [comment]
This was already fixed for 2.8, see:[https://speckle.xyz/streams/638d3b1f83/commits/2317b5c54a]( https://speckle.xyz/streams/638d3b1f83/commits/2317b5c54a)

**Comment by bimgeek** [comment]
> This was already fixed for 2.8, see:https://speckle.xyz/streams/638d3b1f83/commits/2317b5c54a

Not on my end. I was using 2.8.0-alpha2.

**Comment by clairekuang** [comment]
Could you try building the autocad connector from release/2.8.0 and checking from there?

**Comment by bimgeek** [comment]
> Could you try building the autocad connector from release/2.8.0 and checking from there?

Yep, this solved it. 🚀🚀
