### ISSUE TITLE
Support additional Revit conversions for Forms & Surfaces

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#155]
We'd like to be able to support additional conversions:

- [x]  Surfaces to Revit (as Faces), so that we can generate `WallByFace` elements. This should be quite easy give the existing Brep conversions
- [ ] Forms to Revit, less urgent but would be great supporting them to generate native Revit families ![image](https://user-images.githubusercontent.com/2679513/102994680-6b32fc80-4517-11eb-9af4-b02af52088d1.png) 
- [ ] Surfaces and Forms from Revit to Speckle, least urget for now

Adding Claire as she might enjoy tackling some geometry stuff too!

**Comment by teocomi** [comment]
Hey @AlanRynne please close this after you've broken it down in sub issues.

**Comment by AlanRynne** [comment]
Closing as I split the issue between the different parts to track them independently. Check ☝🏻
