### ISSUE TITLE
refactor(core): merge graphql models and credentials models

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#1552]
`Core.Api.Models`and `Core.Credentials.Responses` both contain models for server requests. In the interest of not duplicating code / referencing each other unnecessarily, these should probably be combined and moved up a level so they can be shared across both modules.

Note that this requires very small updates throughout sharp because the models are used in all the connectors.

**Comment by teocomi** [comment]
Closing for now.
