### ISSUE TITLE
feat(civil3d): investigate part builder support

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1572]
## What package are you referring to?

Civil3D 

## Describe the solution you'd like

Use case from community: see https://speckle.community/t/revit-family-civil-3d-pipe-network-structure/2928
This would enable mapping of revit families with parameters and constraints to C3D building part geometry, and require creating revit family geometry inside a part builder file.

This would require the BIM mapping feature to be fully operational, but first investigate whether or not it's possible to programmatically access Part Builder in C3D.

## Describe alternatives you've considered

Mapping revit fam params to civil3d property sets?

## Related issues or community discussions

see https://speckle.community/t/revit-family-civil-3d-pipe-network-structure/2928

**Comment by Alx-88** [comment]
Hi!
That would be great! When released, it will be possible to test it?

**Comment by clairekuang** [comment]
Yup, pending whether or not the C3D api allows for this. Will post updates here!

**Comment by Alx-88** [comment]
Hi @clairekuang,
Any news?
Many thanks

**Comment by clairekuang** [comment]
@Alx-88 This is scheduled for next sprint (2.11 release)

**Comment by kalvin1357** [comment]
@clairekuang 
Hi Claire, Is this problem solved in 2.11 version? I need to convert some revit family become a Civil3D structure. Is it any solution? Thank you.

**Comment by teocomi** [comment]
Hey @kalvin1357 , we haven't gotten to it yet, but we'll try to prioritize it together with some other corridor improvements we're working on! Cc @paloknapo

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
