### ISSUE TITLE
Core: add simpler methods to perform receive & send operations

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#158]
As a lazy developer I'd like to be able to receive & send data with a single SDK method.

Currently to receive data from a stream we need to do the following:

```
      var streamId = "cd83745025";
      var account = AccountManager.GetDefaultAccount();
      var client = new Client(account);
      var res = await client.StreamGet(streamId);
      var mainBranch = res.branches.items.FirstOrDefault(b => b.name == "main");
      var commit = mainBranch.commits.items[0];
      var transport = new ServerTransport(account, streamId);
      var data = await Operations.Receive(
        commit.referencedObject,
        remoteTransport: transport
      );
```

I'd like to have helper/wrapper methods in Core to do so in a single line, same for sending. It's been discussed before, now we have an issue for it. :)

**Comment by didimitrie** [comment]
We could use the lovely rather new-ish [`StreamWrapper`](https://github.com/specklesystems/speckle-sharp/blob/5911ce3fb3ce3434b4d39fcb287409d211bf42f7/Core/Core/Credentials/StreamWrapper.cs#L23) class for this. It already handles quite a few of the cases; and we ~~could~~ should make it handle more in the future (ie, branches, releases, etc.). 

Also has the advantage of easy to grasp future docs: "just paste in the url", and
- if it's a [stream url](https://staging.speckle.dev/streams/5486aa9fc7), it will just take the latest commit from any branch;
- if it's a [branch url](https://staging.speckle.dev/streams/5486aa9fc7/branches/main), it will take the latest commit from that branch;
- if it's a [commit url](https://staging.speckle.dev/streams/5486aa9fc7/commits/1cb2e19b36), it will pull that commit down. 

This would entail an overload for `Operations.Receive(string url)` - and internally that url gets parsed in a stream wrapper that then gives us everything we need - enough info for the server transport (account, etc) & the rest we default.

**Comment by teocomi** [comment]
Yes we could use the `StreamWrapper` class or a dedicated static helper class. Ideally it would have mutiple overloads such as:

`Operations.Receive(string streamId)` => get the latest commit on a stream by id using the default account
and maybe even 
`Operations.Receive()` => get the latest commit latest commit using the default account

 so end developers don't need to qualify the full URL (since the default account would be used). 

This would be great for scripting environments, quick prototyping etc.

**Comment by teocomi** [comment]
I've added a draft implementation to: https://github.com/specklesystems/speckle-sharp/commit/0ac418e864aef53c8a4bfebbd5b397488d5c4840
Although, it now looks quite weird that a separate pkg is required to use these simple helper methods...

Would you be against bringing the SeverTransport inside Core (just like the SQLlite is) @didimitrie ? That'd allow us the have these methods in Core directly.
