### ISSUE TITLE
Open comments view from connector

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1585]
As suggested by @thoffeller this would be a killer feature, it'll need some tech scoping but all the info needed should be available.
We can add an extra button in the comments view to open a corresponding view in the host app.
- [x] #1827
- [x] #1845
- [ ] acad/civil
- [ ] bentley

**Comment by teocomi** [comment]
Implemented in Revit.
Up to @clairekuang and @Reynold-Chan or @connorivy if we can push this to any other DUI connector for 2.10, otherwise 2.11 will be!

**Comment by thoffeller** [comment]
Very cool, thanks!

**Comment by Reynold-Chan** [comment]
Neither CSI + Tekla have camera views of the model.

**Comment by teocomi** [comment]
Closing this and keeping these as suggestions for DUI3 cc @Gaschitz
