### ISSUE TITLE
New menu tabs on GrasshopperReloadAssemblies

### ISSUE THREAD

**Issue by Sonderwoods** [specklesystems/speckle-sharp#1601]
Hi, I'm doing a lot of plugin development where i need to run the GrasshopperReloadAssemblies command.

Turns out that every time speckle is loaded, it creates a new context menu. Should probably check if one exists of the same name before creating a new one. See below

![image](https://user-images.githubusercontent.com/19936679/189193211-0186c6c4-e1dd-4f83-a06b-92ca3b882185.png)

**Comment by AlanRynne** [comment]
Thanks for bringing this up! I must confess I wasn't even aware of this hidden command 😅

> For future reference, you can access these commands by running the `T_E_S_T` command in Rhino!

I just opened a PR that should solve that issue ;) We'll be releasing version 2.8.1 shortly that will include this.
