### ISSUE TITLE
Rhino (Geometry) -> Revit Direct Conversion Routines

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#161]
Scaffold some basic, simple, non-exhaustive direct conversion routines for geometry (coming from Rhino) into Revit. Some examples, just to kick off a conversation:
- xy planar surfaces (with/without inner trims) -> floors
- vertically planar surfaces (with/without inner trims) -> walls 
- curves/lines -> model curves
- etc.

**Comment by AlanRynne** [comment]
I think this makes total sense, although I'd be inclined to include this in some sort of "smart mode" toggle option in the receiver side. This would allow the user to deactivate it if any of our conversion decisions don't suit them

 A couple of remarks:
- For `curves` -> This behaviour would be pretty much what I'd expect to happen in most situations.
- For `surfaces` -> I see some possible problems:
  - This may seem inconsistent and/or tricky: At least in grasshopper, all `surfaces` are in fact `Brep`s with one face, so we'd have to decide when a `Trimmed/untrimmed Surface` should be a wall/floor and when it should just be a DirectShape.
    - If we do this on the Rhino side, we are effectively modifying the data the user is sending in the stream (what if later you want to grab it in dynamo or gh?).
    - If we do this on the Revit side, we would need to check for surface planarity, orientation, etc in Revit using their lovely APIs...
  - Surfaces would have 0 volume, not sure how this would affect other Revit stuff down the line.
  - Flat roof vs flat floor?

**Comment by clairekuang** [comment]
> * For `surfaces` -> I see some possible problems:
>   
>   * This may seem inconsistent and/or tricky: At least in grasshopper, all `surfaces` are in fact `Brep`s with one face, so we'd have to decide when a `Trimmed/untrimmed Surface` should be a wall/floor and when it should just be a DirectShape.

I believe in Rhino, `Brep` (collection of `BrepFace`, which are trimmed srfs) and `Surface` both inherit from `GeometryBase`, but there is some trickiness with `Extrusion` (inherits from surface) that often need to be treated as breps with a conversion. 

Grasshopper breaks with this naming convention and Surface = single-face brep to prevent loss of trim info when brep faces get converted to srfs.

With walls/floor/slabs, does it make sense to associate the toggle with extracting the boundary curve for vertical/planar surfaces on the rhino side as an indicator for which surfaces get converted into families vs `DirectShape`? On this note, we'd have to handle hole trim edge curves -> voids as well
