### ISSUE TITLE
Feat: Part support in Revit

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#1613]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Is your feature request related to a problem? Please describe.

The part class is not implemented in the Speckle Revit connector, so those items will skipped.

## Describe the solution you'd like

Add the part class into the types of elements that can be sent to Speckle and received back into Revit

## Related issues or community discussions

https://speckle.community/t/parts-support-in-revit/3583

**Comment by teocomi** [comment]
Possibly related to: https://github.com/specklesystems/speckle-sharp/issues/1100

**Comment by connorivy** [comment]
@teocomi I believe these issues are referring to different things. 

This one is referring to the [Part Class](https://www.revitapidocs.com/2018/ca94b36d-4f9a-091d-b31e-a32a16ec89ac.htm) while the linked issue is referring to the [FabricationPart Class](https://www.revitapidocs.com/2018/c9b86162-c105-696a-a919-49a7a7938cc4.htm). FabricationPart objects seem to be for MEP objects, but Parts are for other objects listed [here](https://knowledge.autodesk.com/support/revit/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/Revit-Model/files/GUID-DA150C6B-996C-4C70-9E8C-3C536C232851-htm.html)
