### ISSUE TITLE
wrong modifying of Z axis

### ISSUE THREAD

**Issue by golembiovskyi** [specklesystems/speckle-sharp#1617]
https://github.com/specklesystems/speckle-sharp/blob/02d7032190b26cae1ba23cd3a0a4818ea3670177/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertPipe.cs#L117
wrong modifying of Z axis, so a pipe ends up on incorrect offset from horizontal

**Comment by clairekuang** [comment]
\this was fixed by omitting more parameters in the PipeToSpeckle method
