### ISSUE TITLE
feat(revit): add support for Rebar Container

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1622]
## Description
As mentioned by [gjordanp ](https://speckle.community/u/gjordanp/summary)in the forum, Rebar Container elements support is missing in Revit. 

> Rebar container is an element that contains rebar elements, so if rebar is supported I’m thinking it wont be hard to support.

## Files

https://drive.google.com/file/d/13SVM11xn50GYBaCRpYZfUNORwUp6C0XL/view?usp=sharing

## Screenshots
![image](https://speckle.community/uploads/default/original/2X/5/54771873402d2e01e197c8295b31f3b179a39673.png)
![](https://speckle.community/uploads/default/original/2X/2/2018417b84b434325a748ae6d3f0b7bd83f55d2e.png)

## Related Discussions

https://speckle.community/t/revit-rebar-container-not-supported/3210

**Comment by paloknapo** [comment]
Requested again https://speckle.community/t/rebar-element-in-revit/6855/1

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
