### ISSUE TITLE
bug(revit): DXF Mesh with hidden edges don't work for meshes from AutoCAD

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1624]
## Description

As reported by [nvuk ](https://speckle.community/u/nvuk)on [this thread](https://speckle.community/t/autocad-3d-to-revit-getting-edges-for-annotation-alignment-snaping/3608), looks like DXF Mesh Import method doesn't hide edges that should normally do when receiving meshes from AutoCAD. 

## Files

[2022-09-20-Speckle-DWG_RVT_Snap_points.zip](https://github.com/specklesystems/speckle-sharp/files/9624386/2022-09-20-Speckle-DWG_RVT_Snap_points.zip)

## Commits

https://latest.speckle.dev/streams/2ee78e0c62

## Steps to Reproduce

1. Send any mesh geometry from AutoCAD using Speckle connector
2. Enable DXF for Mesh Import Method under Advanced settings
3. Click Receive

## Screenshots

This is AutoCAD👇

![image](https://user-images.githubusercontent.com/51519350/191713507-739f53fe-10ac-4403-90aa-3a928f726925.png)

Same geometry in Revit👇

![image](https://user-images.githubusercontent.com/51519350/191713575-81a68a74-fbe1-45ce-8210-b0fc827c8a24.png)

**Comment by AlanRynne** [comment]
This is not an issue, it's just the way the DXF exporter works.

For every "naked edge" or "unwelded edge" on a mesh, it will draw a line to highlight it. If the mesh it receives has multiple duplicate vertices (meaning it has unwelded edges somewhere), those edges will be highlighted with a line.

There are other approaches at this that could prevent this from happening, such as measuring the angle between the faces of a mesh, and determining based on that wether to draw the line or not. **But**, this would require our Mesh class to know about its topology, which it currently does not.

It's quite an expensive operation to perform just to figure out the crease angle between faces.

If user's want pretty meshes they need to send "properly welded meshes" into Speckle already.

I am not sure how doable this is in AutoCAD, but the mesh that was sent contained 36 vertices and 12 faces. To get the result he's expecting, it would require the cube to have the minimum amount of vertices possible (i.e. 8)

**Comment by AlanRynne** [comment]
Top-left: The original mesh from autocad
Bottom-right: The same mesh without duplicated vertices

![Image](https://user-images.githubusercontent.com/2316535/201361983-97947746-7852-4803-9684-1fb61693f0bd.png)

**Comment by AlanRynne** [comment]
Closing this as a non-issue. It is the way the DXF converter works.
