### ISSUE TITLE
external(autocad): some `Dimension` conversions are incorrect when receive

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1625]
## Prerequisites

- Fork from our latest release branch: https://github.com/specklesystems/speckle-sharp/tree/release/2.9
- Read our Objects Kit guide for context: https://speckle.guide/dev/objects.html
- Create an account on Speckle.xyz
- Build the AutocadCivil Connector solution

The goal of this task is to (1) demonstrate in-depth knowledge of AutoCAD's SDK and cad-specific classes (2) demonstrate a high-level understanding of how we handle conversions of complex objects in AutoCAD, including how properties of these objects are defined and attached.

## What package are you referring to?

**Autocad Converter Methods**

`DimensionToSpeckle()`: https://github.com/specklesystems/speckle-sharp/blob/85b7428f258c569bf1caa354555a742fba176f7e/Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs#L690

`AcadDimensionToNative()`: https://github.com/specklesystems/speckle-sharp/blob/85b7428f258c569bf1caa354555a742fba176f7e/Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs#L773

## Describe the bug

**Option 1**
Most *rotated dimensions* are received in Autocad exactly as how they are sent. However, in certain cases the `TextPosition` of the received rotated dimension is out of place. Investigate the source of this issue and propose a robust fix for how to handle these cases.

**Option 2**
Most *radial dimensions* are received in Autocad exactly as how they are sent. However, in certain cases one or both of the `Leader`s of the received radial dimension is incorrectly visible. Investigate the source of this issue and propose a robust fix for how to handle these cases.

## To Reproduce

1. Send the provided Autocad dimension test file to a stream on speckle.xyz
2. Receive the sent commit in Autocad

## Expected behavior

All `Dimension`s sent from AutoCAD should be identical when received. 

## Screenshots

**Option 1**
![image](https://user-images.githubusercontent.com/16748799/191816885-65f16f1e-5199-491a-adb3-d6c3aa74f797.png)

**Option 2**
![image](https://user-images.githubusercontent.com/16748799/191818837-b197cd50-fa58-404e-b9f1-f7d49bdef759.png)

## Additional context

Autocad to Autocad `Dimension` conversions use special utility methods called `GetAutocadProps()` and `SetAutocadProps()` that were designed to help intra-application conversion be as accurate as possible: https://github.com/specklesystems/speckle-sharp/blob/85b7428f258c569bf1caa354555a742fba176f7e/Core/Core/Models/Utilities.cs#L97

They also include a *dynamically added* `TextPoint` prop to assist with better conversions.

The bug with Rotated and Radial dimensions may be caused by how these properties are being attached on send, or set on receive. You can also propose an alternative method for handling Autocad-specific dimension properties instead of using these methods.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
