### ISSUE TITLE
bug(revit): Add proper support for Revit Groups

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1631]
## Description

Groups from Revit can be sent via the connector but can't be received back. And the way we handle Revit groups is problematic. Group elements are handled as a single element in the viewer. Group members and their properties cannot be accessed.

Related to [this post](https://speckle.community/t/revit-group-elements/3602) on forum👪.

## Steps to reproduce
Use the sample file or:
1. Model 4 walls or place multiple elements in Revit.
2. Select and group items you added.
3. Select this group and send it to Speckleverse via the connector.
4. Create a new project.
5. Try to receive the commit you just sent.
6. Speckle connector will not give any warning/error but neither will it create the group and its member elements.

## Streams/Commits
https://latest.speckle.dev/streams/fb39fd2b41/commits/5887b61fb2

## Files
[RevitGroupTests.zip](https://github.com/specklesystems/speckle-sharp/files/9653827/RevitGroupTests.zip)

## Screenshots
![opera_qNvuWPftC6](https://user-images.githubusercontent.com/51519350/192481108-3e8450e9-31f6-4015-983f-6658cf77e985.png)

## Possible Solution
A good solution (I think) would be to create a new "Groups" class in Objects.BuiltElements.Revit that extends the BlockInstance class in Objects.Other. It would need a property that contains a list of base objects that holds the converted Revit elements that make up the group in Revit so that when the group is received back into Revit, a new group can be created and then we can add each of the elements that make up that group.

**Comment by Ravina-Deogadkar** [comment]
Is this issue available, Can I take it?

**Comment by teocomi** [comment]
Hey @Ravina-Deogadkar , sure thing, I'll add you.
In case you foresee making any modifications or addition to our Objects classes, please let's discuss it in advance as they can have consequences in other connectors and need to be carefully planned.

Cc @connorivy @clairekuang

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
