### ISSUE TITLE
Revit: Show default options for Advanced Settings

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1632]
### Expected behaviour

Setting dropdown menus in DesktopUI2 should show the default value when no value was set by the user.

### Current behaviour

Settings show no selection if the user hasn't set a value (i.e. hasn't changed the defaults to something different)

![Screenshot 2022-09-27 at 11 34 24](https://user-images.githubusercontent.com/2316535/192490843-a68c2485-d173-440f-ae35-022711d15a3d.png)

**Comment by Ravina-Deogadkar** [comment]
Can I work on this?

**Comment by teocomi** [comment]
Hi @Ravina-Deogadkar , I believe this has been already implemented and we forgot to close it!
Cc @connorivy just in case I'm wrong :)

**Comment by Ravina-Deogadkar** [comment]
Ohhh

**Comment by Ravina-Deogadkar** [comment]
Is there any open good first issue?

**Comment by teocomi** [comment]
Please have a look for any #hacktoberfest issues!
