### ISSUE TITLE
Rhino: Better name of materials on `Receive`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1633]
Our current way of baking materials in Rhino is too long to be comprehensible on the Rhino UI and requires hovering each item to get the full name.

![Screenshot 2022-09-27 at 11 38 07](https://user-images.githubusercontent.com/2316535/192491702-8295a196-ff67-40c6-bda5-3b1d1630e4c2.png)

Ideally, we should either choose a simpler material name, or re-order the pattern so that the important info goes in first (ie. `material -> stream` instead of `stream -> material`)

**Comment by bimgeek** [comment]
merging this w #1833
