### ISSUE TITLE
Show layer names on `Send`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1636]
When having multiple streams in the same document, it's difficult to know what layers were selected for what stream.

The only way to know is to open up the stream view.

![Screenshot 2022-09-27 at 12 09 32](https://user-images.githubusercontent.com/2316535/192498564-03a05374-66b8-4af4-a147-ddfd99b98bc5.png)

This would apply to any DUI-based connectors that use layers.

**Comment by teocomi** [comment]
I think this had already been closed some time ago
![image](https://user-images.githubusercontent.com/2679513/209321048-9aadd56b-5b1c-4a5f-a681-6d358e414e32.png)
