### ISSUE TITLE
Naming/grouping option for saved streams

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1638]
![Screenshot 2022-09-27 at 12 20 57](https://user-images.githubusercontent.com/2316535/192500988-a21455ef-0368-4d53-8b33-0abe5bc60072.png)

There's a lot of redundant info when dealing with multiple branches from the same stream.

Maybe we can name them better, or group them so that the title only shows up once?

**Comment by jsdbroughton** [comment]
Similar strategy could be borrowed from nested branches..?

**Comment by teocomi** [comment]
Definitely, a lot will change after the revamp :)
