### ISSUE TITLE
feat(civil3d): nest offset alignments in parent alignments

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1653]
## What package are you referring to?

Civil3d connector and converter

## Is your feature request related to a problem? Please describe.

Currently, offset alignments are being treated usually as if they were centerline alignments. 

This means on receive, they are created without being linked to a parent alignment, which can be an unacceptable condition if a user specifically wants to send a parent alignment with its offset and then changes the parent alignment after receive (which wouldn't change the offset alignment, and woudl require manually rebuilding the received offset alignment as an offset of the parent).

## Describe the solution you'd like
Offset alignments *when sent without their parent* should be received as centerline alignments.
Offset alignments *when sent **with** their parent* should be received as offset alignments.

## Additional context

This is similar to how hosted elements behave in revit, and would require some refactoring of the connector to store host element relationships if a parent alignment is created first and offset created in the same conversion, making sure they are doubly created during the flatten cycle.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
