### ISSUE TITLE
How is the renderMaterial.id generated?

### ISSUE THREAD

**Issue by oeykmiih** [specklesystems/speckle-sharp#1661]
greetings,

trying to implement Blender as an archviz solution to work with Archicad and been looking into using Speckle for it. (I am aware that it is in alpha)
everything seems to work fine but the renderMaterial.name become null when extracted from Archicad to the Speckle Cloud.

I've noticed the renderMaterial.id seems consistent with the Blender's material name,
whenever I create the "xyz" material it converts to "43ff9d0beff945388b78b192ea288192" as an id.

tried to find the method of generating the material id in the code but without much luck.

could someone give me pointers on how to do it, so I can use it to determine the names of the premade blender materials?

**Comment by teocomi** [comment]
Hey @oeykmiih thanks for the report! Seems like we have 2 issues here:
- Archicad not sending the material names- @clairekuang can help us investigate this
- finding where Blender material ids come from - hopefully @JR-Morgan has some ideas here

**Comment by JR-Morgan** [comment]
Hi @oeykmiih, 

The id of **any speckle object** (`RenderMaterial`s included) is calculated as the **hash of all its properties**[*](https://github.com/specklesystems/specklepy/blob/d0eb364b3ef45c30182be32448ce5138987b1984/specklepy/serialization/base_object_serializer.py#L23-L24), such that if any property on a speckle object is changed, the resulting id will be different. But Identical objects will produce the same id.

As far as ID generation is concerned, `renderMaterial.name` is just another property, and all properties are considered part of the logical identity of the object.

---

That being said, I don't quite follow how this relates to your issue, I would need some more context on what behaviour you are trying to achieve.

As @teocomi mentioned, nameless materials from Archicad sounds to me like a bug with the Archicad converter.

**Comment by oeykmiih** [comment]
hi @JR-Morgan ,

I see, so the generated name should always be same for the same Archicad material, that should help me figure something out in the meanwhile. Thank you for the explanation, trying to get into coding inspired by projects like yours, thus getting to understand the code base helps me.

---

I guess I should have reported the bug as the main topic and then add the side question for the temporary workaround, should I refactor de issue?

**Comment by fraguada** [comment]
@jozseflkiss do you know if materials from archicad have the correct id assignment as they are being sent to Speckle?

**Comment by jozseflkiss** [comment]
Hello @oeykmiih,

Material name export added in Archicad Connector v2.11!
Regards,
József
