### ISSUE TITLE
🦩 Show Filter Details on Main UI

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1662]
## Description

When sending data to Speckle, users can create different filters (`Category`, `View`, `Layer` etc.) according to their organization and send them to different branches in the same stream. But this creates a UI problem cuz currently there is no mechanism in place to show those settings (see image below👇). 

For example, users can create branches for `Floors` and `Walls` and send them to their corresponding branches from Revit or send different layers to different branches from AutoCAD/Rhino.

## Expected Behaviour

Show filters/settings in the DUI2 → Selected category/layer/view names…

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/193573365-860ccd18-69c8-45e6-8e89-608635f9c9b0.png)

![image](https://user-images.githubusercontent.com/51519350/193574306-5f8aa098-a77b-4d34-885f-6495887731c9.png)

**Comment by teocomi** [comment]
![image](https://user-images.githubusercontent.com/2679513/193646923-972063bc-505a-44d3-99ef-3fd3951497da.png)
