### ISSUE TITLE
Bug(ETABS): Speckle plugin fails in ETABS on release branch

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#1666]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

When I'm trying to open the speckle connector on the release branch, it doesn't work. Opening the plugin works until this commit https://github.com/specklesystems/speckle-sharp/commit/84a40937d947b35f56d24f51d3fdf944b819a038. It's not immediately clear to me why this commit would break the ETABS plugin.

## To Reproduce

- Build the ConnectorCSI on the release branch
- Try to open the connector in ETABS
- Be disappointed when the "plugin failed" message shows up

(Bonus steps)
- Checkout the commit immediately before the one above (its this one https://github.com/specklesystems/speckle-sharp/commit/a0604d3303d8c707ec1bba5930f1852759cea563)
- Build the connectorCSI and open it in ETABS
- Be confused when it works

## Expected behavior

The plugin should open and not show a dialog that says "plugin failed"

**Comment by AlanRynne** [comment]
I'm fairly certain we've fixed this in #1703, @Reynold-Chan can you confirm?

**Comment by AlanRynne** [comment]
I can confirm this has been fixed in the `beta4` release, so I'm closing it.
