### ISSUE TITLE
bug: Curve join produced more than one WIRE in PolyCurve.

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1667]
## Description

While trying to receive a structural model I sent from Revit in Dynamo, I encounter the following error.

> Curve join produced more than one WIRE in PolyCurve.
> 

## Expected Behaviour

Instead of canceling the whole receive process, maybe it could just return null instead of the problematic objects.

## Commits Used

[https://latest.speckle.dev/streams/05aad7fcf7/commits/77b95004af](https://latest.speckle.dev/streams/05aad7fcf7/commits/77b95004af)

## Steps to reproduce

1. Paste the link above into a `String` node in Dynamo.
2. Connect this String node to the `Receive Commit` node.
3. Press on Receive button🔵.

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/193982462-7e774282-2e50-42ea-a331-0e964e898053.png)

**Comment by AlanRynne** [comment]
In `2.9`, whatever fails conversion will be returned as `null`. That being said, I'll double check these curves to see what's the problem with that. For future reference, Dynamo is known to error out when things are not as it expects:

- 0 Length lines
- Branching polycurves (i.e. a polycurve that has some point connected to more than 2 lines)
- And now this one, when Curve.Join() expects only one curve as the result of the join operation.

**Comment by AlanRynne** [comment]
https://github.com/specklesystems/speckle-sharp/pull/1670 fixes the error on that specific commit, which was caused by the arcs being built with angles instead of the 3Pt constructor, leading to non-connecting elements in the polycurve.
