### ISSUE TITLE
Support Branch Urls

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#167]
Now that we have [branch urls](https://staging.speckle.dev/streams/5486aa9fc7/branches/yolo%20branch), we should get to support them. 

A branch url, when being an input for a 
1) **Sender**: should create commits on that branch; 
2) **Receiver**: should get the latest commit on that branch, and listen for any new commit updates (on that branch). 

This will be coupled with the removal of the branch name input for sender components.

**Comment by teocomi** [comment]
This might already be implemented in Dynamo, to be checked!
