### ISSUE TITLE
Support updating DirectShape elements

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1674]
## Description

Reported **Gaby Pena** of [Studio NA](https://www.studiona-mx.com/).

Common workflow users follow is they use Revit to document their designs from Rhino. Studio NA is using Speckle for this integration. They are mostly involved in Interior Design projects.

Since Revit is used for documentation, dimensions/annotations play an important role here. However, our Update method deletes all the received geometry and creates new ones in their place, instead of updating unchanged parts and creating only the changed parts. Because we are deleting and creating, all the added dimensions get deleted. To explain it through an example:

> Gaby sends two design alternatives to Speckle. The only difference between the two is that the handles on the second one are rotated 30 degrees. Other than that everything is the same, the second commit is created by using the source geometry of the first commit. 
Gaby receives the first commit and adds dimensions and when she receives the second commit, all dimensions are deleted.
> 

`📌 Received geometry creates **Direct-Shapes** in Revit. This can be seen in the GIF below👇:`

![Revit_zh8ycxyv5l](https://user-images.githubusercontent.com/51519350/194470415-0b2eb589-242d-4450-a94e-2e18279b0b97.gif)

## Expected Behaviour

When we receive the geometry in Revit, the parts that do not change should not be deleted and recreated, they should not be touched.

### Commit 1️⃣:

[https://latest.speckle.dev/streams/6b24f9dc21/commits/893a9c8083](https://latest.speckle.dev/streams/6b24f9dc21/commits/893a9c8083)

### Commit 2️⃣:

[https://latest.speckle.dev/streams/6b24f9dc21/commits/eee69a452a](https://latest.speckle.dev/streams/6b24f9dc21/commits/eee69a452a)

## Steps to reproduce

1. Activate Revit connector.
2. Receive first commit.
3. Add dimensions to geometry in plan view.
4. Receive second commit.
5. You’ll see that all geometries have been created from scratch and dimensions have been deleted.

## Files Used

**Revit File** 

[https://drive.google.com/open?id=12obi8EF2YsEcvJxL4LusWElElnMZhrJd&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=12obi8EF2YsEcvJxL4LusWElElnMZhrJd&authuser=bilal%40speckle.systems&usp=drive_fs)

**Rhino File**

[https://drive.google.com/open?id=12qpfDXE5mHAB5xVTXESUvuMyU8QISWAN&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=12qpfDXE5mHAB5xVTXESUvuMyU8QISWAN&authuser=bilal%40speckle.systems&usp=drive_fs)

**Comment by teocomi** [comment]
Hey @bimgeek, what other categories except from DirectShape you had in mind?

**Comment by bimgeek** [comment]
Freeform elements too.

**Comment by AlanRynne** [comment]
I had a quick look into this and I'm not sure this is doable (pending more research).

It seems like, even if we preserved the DirectShape instance, the class only allows for the replacement of every geometry inside it:

https://www.revitapidocs.com/2015/8d62b427-bc3c-e772-f6b0-0aed603cc1c9.htm

This is a bit of a bummer. It remains to be seen if doing this will preserve some of the dimensions (as opposed to our current strategy of deleting and re-creating a new DirectShape. I'll look into this next week.
