### ISSUE TITLE
bug: Ctrl+Z Borks Update

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1675]
## Description

CTRL+Z is designers’ best friend but doesn’t seem to get along with our Update behaviour. After receiving a commit, when we undo it using CTRL+Z and receive it again, Update does not work and Revit connector creates new geometry. So user ends up with two commits on top of each other.

Take a look at the GIF below.

## Expected Behaviour

Update method always updating geometry even if i use CTRL+Z.

### Commit 1️⃣:

[https://latest.speckle.dev/streams/6b24f9dc21/commits/893a9c8083](https://latest.speckle.dev/streams/6b24f9dc21/commits/893a9c8083)

### Commit 2️⃣:

[https://latest.speckle.dev/streams/6b24f9dc21/commits/eee69a452a](https://latest.speckle.dev/streams/6b24f9dc21/commits/eee69a452a)

## Steps to reproduce

1. Open Revit connector
2. Receive Commit 1️⃣.
3. Receive Commit 2️⃣.
4. Undo using Ctrl+Z.
5. Receive Commit 2️⃣ again.
6. You’ll end up with overlapping geometries in the same place. Update does not work, it Creates.

## Files Used

**Revit File** 

[https://drive.google.com/open?id=12obi8EF2YsEcvJxL4LusWElElnMZhrJd&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=12obi8EF2YsEcvJxL4LusWElElnMZhrJd&authuser=bilal%40speckle.systems&usp=drive_fs)

**Rhino File**

[https://drive.google.com/open?id=12qpfDXE5mHAB5xVTXESUvuMyU8QISWAN&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=12qpfDXE5mHAB5xVTXESUvuMyU8QISWAN&authuser=bilal%40speckle.systems&usp=drive_fs)

## Screenshots

![Revit_SLThTTgsTd](https://user-images.githubusercontent.com/51519350/194473633-0d9972bc-5938-4aff-a426-18fb36474e77.gif)

**Comment by paloknapo** [comment]
@connorivy  let's check if this is still an issue, if not can be closed.

**Comment by teocomi** [comment]
Closing as I believe this has been fixed
