### ISSUE TITLE
papercut: Mismatch in Archicad version

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1677]
## Description

Although I was running Speckle connector on Archicad 25, DUI2 was showing `Speckle for Arhicad 26`. Take a look at the screenshot below👇:

## Expected Behaviour

Whichever version of Archicad it runs on, show that version.

- `Speckle for Archicad 25`
- `Speckle for Archicad 26`
- …

## Steps to reproduce

1. Open Archicad 25 (if installed)
2. Enable `ALPHA Speckle Connector`

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/194520259-a6122871-a0bc-450f-841c-05d8f2393e9b.png)

**Comment by jozseflkiss** [comment]
We can use the same Speckle Connector for all Archicad versions (25 and 26), I removed the Archicad version number from the UI.

**Comment by teocomi** [comment]
In other connectors, we use preprocessor directives to handle these things:

https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs#L14-L24

Could maybe do the same for Archicad?
