### ISSUE TITLE
Archicad Mac CI setup step

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#1687]
To build the ArchiCAD connector code in CI, we need to set up the SDK for CircleCI.

We already have a [setup step](https://github.com/specklesystems/speckle-sharp/blob/b95647e7c54d566e8330c5e6f934c041967f761b/.circleci/scripts/config-template.yml#L278) for the Archi Win workflow, this needs to be adopted / duplicated for the mac build.

@AlanRynne's idea to use an object storage bucket to store these, would possibly be a nice solution. 
You can talk to @iainsproat to set up the bucket and its contents

**Comment by clairekuang** [comment]
Also linked to: https://github.com/specklesystems/speckle-sharp/issues/1144
