### ISSUE TITLE
bug(grasshopper): Value was either too large or too small for an Int64

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1689]
## Description

As pauldotnet from community reported in [this thread](https://speckle.community/t/error-getting-data-from-qgis/3758):

> I’ve sent a DEM from QGIS to Speckle. It worked fine and here is the [stream ID](https://speckle.xyz/streams/26c360960f/commits/625940f9c5). Now, I am trying to receive it in GH and I get this error message. Is there something I am doing wrong?
> 
> 
> ![image](https://user-images.githubusercontent.com/51519350/194923300-16c7643b-3988-4cae-9256-b72a2ca390c9.png)
> 

## Steps to reproduce

Try to receive the attached commit in Grasshopper

## Streams/Commits Used

[https://speckle.xyz/streams/26c360960f/commits/625940f9c5](https://speckle.xyz/streams/26c360960f/commits/625940f9c5)

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/194923348-5f3f4945-0c64-46b1-b48c-064955610f69.png)

**Comment by KatKatKateryna** [comment]
Could reproduce with default GH connector (2.8.2). Is setting "Do not convert", just returns empty Data with no errors. 
Rhino doesn't receive any objects as well. 
QGIS receives properly.

**Comment by KatKatKateryna** [comment]
Resolved in QGIS sender by changing extreme NoData value (e.g. -3.4e+38) to other acceptable value: https://github.com/specklesystems/speckle-qgis/pull/59
