### ISSUE TITLE
Problem with size render of Speckle Desktop Manager

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1705]
## Prerequisites

- [ ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [ ] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug
Problem cause when I use 2 monitors, size of Speckle Desktop Manager Width too long.
- First Screen : Dell M4800 1920x1080
- Second Screen : Dell UltraSharp 24 Inch U2422H 1920*1080

-->

## Expected behavior

I hope can resize or show correct size of screen
## Screenshots

![image](https://user-images.githubusercontent.com/31106432/195351266-39b87e5a-94ee-4663-9603-95708257833e.png)
![image](https://user-images.githubusercontent.com/31106432/195351649-8286de91-daa0-422c-9f51-6a8ad69652c2.png)

## System Info

Window 

### Desktop (please complete the following information):

- OS: Window 10
- Version: Speckle Desktop Manager V2.5.14

**Comment by teocomi** [comment]
Thanks for the report, are you by any chance using a virtual machine?

**Comment by chuongmep** [comment]
Hi @teocomi, that is my laptop connect with another monitor, I don't use any virtual machine for this case.

**Comment by teocomi** [comment]
@chuongmep , we can't seem to replicate this internally, do you have 15 min to spare so I can see it in action? :)

https://calendly.com/d/g5k-jcs-5dx/15-min-chat

**Comment by chuongmep** [comment]
Thanks, @teocomi, I will try to fix bug in this open sources first meeting.

**Comment by chuongmep** [comment]
Hi @teocomi, I used some step by step like this and can fix temp, hope can help you see more about problem :
- (1) Problem with window size.
- Setting to Left side
- Tune off app
- Open again speckle desktop manager
- Problem resolved and size window working normal.
- Setting again bottom In speckle desktop manager
- Close Manager
- Open again Manager 
-(1) Problem with window size.

**Comment by teocomi** [comment]
Thanks for the report @chuongmep ! I just made a beta release that has a setting to disable the docked mode, can you please try with that?

![image](https://user-images.githubusercontent.com/2679513/197585209-999c4f55-5330-46e4-a1b2-6aeb349fed5a.png)

**Comment by teocomi** [comment]
Thanks for checking! I'll close this for now then and release a new stable version 🙏
