### ISSUE TITLE
Bug: Error thrown when trying to import an alignment from a stream

### ISSUE THREAD

**Issue by jhdempsey86** [specklesystems/speckle-sharp#1708]
## What package are you referring to?

Speckle Civil 3D Connector 2.9.0-beta3

## Describe the bug

Error thrown when trying to import an alignment from a stream

## To Reproduce

Start new civil drawing (drawing)
Create an alignment
Upload alignment to a new empty stream
Open up another new civil drawing (drawing2)
Receive the contents of the new stream into drawing2

## Expected behaviour

Alignment should have been inserted into drawing2

## Screenshots

![image](https://user-images.githubusercontent.com/67244422/195409469-0bade7fa-75b7-493d-ac85-a8e3f460231e.png)

## System Info

- OS: Windows
- Civil 3D 2022 
- Speckle Civil Connector 2.9.0-beta3
![image](https://user-images.githubusercontent.com/67244422/195409667-0ede5cb2-4fed-4813-8478-c95dd91f59dc.png)

## Failure Logs

Failed conversion. eWasErased
Couldn't convert object or any fallback values
Could not bake object
```
![image](https://user-images.githubusercontent.com/67244422/195409469-0bade7fa-75b7-493d-ac85-a8e3f460231e.png)

## Additional context

<!---
Add any other context about the problem here.
-->

## Proposed Solution (if any)

No ideas!

#### Optional: Affected Projects

N/A

**Comment by clairekuang** [comment]
Hey @jhdempsey86 , could you send me a link to the stream you sent the alignment to & set it to public?

**Comment by jhdempsey86** [comment]
https://speckle.xyz/streams/beb1852afb

**Comment by jhdempsey86** [comment]
Let us know if that link worked. I wasn't sure if it was public or not.
Also not sure how to add tags to this post. It needs the acadcivil tag adding
