### ISSUE TITLE
Tune up no internet error

### ISSUE THREAD

**Issue by fraguada** [specklesystems/speckle-sharp#1712]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

GH connector

## Describe the bug

The "no internet" error currently reports this: 

> 
> 1. T0: One or more errors occurred. (No such host is known)
>     No such host is known
>     No such host is known

It would be helpful to have this be more meaningful.

## To Reproduce

Open GH, set up an acct and stream, turn off internet, try to send.

## Expected behavior

The error message is more meaningful, for example:

"No internet connection found."

## Screenshots

![image](https://user-images.githubusercontent.com/1014562/195589048-f81de976-894e-4977-9906-b2dfb4890b65.png)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: macOS 12.2.1

**Comment by AlanRynne** [comment]
Not sure we can get the desired message "No internet connection found", since afaik, you'll get the same error if you don't have internet or the server is down.

We can print out something like

```
Failed to fetch branch 'BRANCH_NAME' from stream 'STREAM_NAME' on server 'SERVER_URL'
    {INTERNAL ERROR DETAILS WOULD GO HERE}
```

Fixing this will mostly require handling `SpeckleExceptions` differently than other exceptions in our `Client.GraphqlClientOperations` to:

- Avoid redundant messages
- Avoid duplicate logging when possible, as each Speckle Exception would log itself.

**Comment by teocomi** [comment]
We could add a method (maybe in Core) that also tries to ping a website like google to differentiate cases where the server is down vs no internet.
That's what Manager does for instance...

**Comment by AlanRynne** [comment]
<img width="787" alt="Screenshot 2022-10-17 at 11 39 20" src="https://user-images.githubusercontent.com/2316535/196144821-d3faaf4a-9497-4b5c-b0cb-821e81412ce9.png">

This looks better already! The issue with the duplicated meshes has to do with our regretful decision on how we're logging everything with `Speckle Exceptions`, which I was hoping to work on for 2.10

**Comment by AlanRynne** [comment]
Ok, after poking around with @fraguada it turns out that the `No known host` error only happens after fetching a stream with a specific account. Either with `Stream Get` or `Stream List`.

This makes me think there's an issue with the StreamWrapper.

**Comment by AlanRynne** [comment]
🥳

<img width="859" alt="Screenshot 2022-10-17 at 13 16 05" src="https://user-images.githubusercontent.com/2316535/196163663-3bdffb45-e772-441d-8b14-4a5197bc37f1.png">
