### ISSUE TITLE
Bug(Revit): Speckle crashes Revit 2019

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#1723]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

The speckle plugin launches correctly, but after clicking the "add a stream" button, an error occures that crashes revit

![image](https://user-images.githubusercontent.com/43247197/195880759-c4ad2f28-9fd5-4812-ab85-b2caa8a1aa16.png)

## To Reproduce

1. Install speckle connector 2.9
2. launch revit 2019
3. click the folder icon to add a stream.
4. watch it crash

## Additional context

I haven't dug too much into the issue, but it has something to do with the new sqlite dll that we're using

**Comment by clairekuang** [comment]
Closing as we deprecated Revit 2019 support
