### ISSUE TITLE
bug(grasshopper): Receiving Freeform Elements returns error

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1724]
## Description

Following error is encountered when receiving Freeform elements in Grasshopper:

> 1. Solution exception: Property Get method was not found.
> 

## Expected Behaviour

Not getting any errors.

## Steps to reproduce

1. Receive the stream below👇.
2. Using the `List Item` node, select the Freeform elements at the end of the list.
3. Connect this object to a `DSO` node.

## Streams/Commits Used

[https://latest.speckle.dev/streams/cdf2ebe2e2/branches/2 builtelements/meters](https://latest.speckle.dev/streams/cdf2ebe2e2/branches/2%20builtelements/meters)

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/196111136-33fc705d-ec9f-4389-a051-025b36172eae.png)

**Comment by AlanRynne** [comment]
This was caused by an old `FreeformElement` node in the test file, in combination with the `BaseGeometry` field not being flagged as `Obsolete`.
