### ISSUE TITLE
Objects: Box should not contain a `bbox`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1731]
`Box` class should not implement `IBoundingBox` as it is, in fact, already the type that is expected.

https://github.com/specklesystems/speckle-sharp/blob/b5ebe1df95512709b0fd5ee289883f688f2e21f7/Objects/Objects/Geometry/Box.cs#L11-L21

This results in the addition of the `bbox` props, which as far as we've been able to tell, is not used anywhere, so it will always be `null`.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
