### ISSUE TITLE
Core: Consolidate connector Traversal logic

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1732]
After talking to @JR-Morgan about this, we thought it would be an interesting to have someone (I nominate @JR-Morgan) to have a look at the different `Traversal` methods we use in the different connectors in order to:

- Identify the unique needs of each connector traversal function
- Identify the common patterns across different connectors with similar conversion logic.
- Consolidate all common logic into `Core`

This would reduce code/logic duplication across 20+ connectors, but also open the opportunity for greater performance optimisation of the Traversal/Conversion logic of all connectors. This is usually a big % of the time spent "receiving a commit", but has never been looked at from a performance point of view.

Just to illustrate our case, here's the Flatten optimisation that Jedd made on my original flatten logic (#1369), which uses `Core`'s generic Traversal function, which he also optimised. ;)

![image](https://user-images.githubusercontent.com/2316535/196277033-13ccfb2a-2ada-4172-b272-ee5c54aef6a4.png) 

This could include non-`speckle-sharp` connectors such as `QGIS` and `ArcGIS`, to fully identify shared patterns across the Speckleverse (i.e. should all `layer-based` modelling software - Acad, Rhino, QGIS behave consistently in terms of layer creation, handling, naming...? and so on...)

**Comment by paloknapo** [comment]
Done for C#, new issue for CSI and Tekla to be opened
