### ISSUE TITLE
(bugs) - dyanmo - Structural objects support  + Converter not found issue for send +  bugs on recieve

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#1733]
![image](https://user-images.githubusercontent.com/29717150/196345717-c4a4e667-4af7-4153-9b01-fd4fa44b2947.png)
Converter not found as shown here

![image](https://user-images.githubusercontent.com/29717150/196345741-d3263e53-3e24-4ced-9b76-a152209699fe.png)
some lack of support for conversion errors for structural objects ^ ( might be a feature problem)

![image](https://user-images.githubusercontent.com/29717150/196346091-e9688c48-963e-4109-bd1f-8bb7dc14a1b0.png)
And failure to receive a normal revit stream still for normal dynamo for this error on receive ^

**Comment by AlanRynne** [comment]
@Reynold-Chan for future bug reports, please post also the stream url you used to get this 😄 makes it easier to repro
