### ISSUE TITLE
Deprecate "old" versions of connectors

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1735]
Our initial stance on supporting connector versions was that we would continue to support always 3 major versions of each connector (the current one + 2 back)

- Revit has 5 😅 (2019, 2020, 2021, 2022, 2023). I think 2019 is being removed already due to technical reasons, but maybe 2020 should too?)
- For software that does not cost money, i.e. Unity/Unreal. It may not make much sense to support 3 major versions back.
- Rhino 6 seems quite a way back already...

My main concern around this is that supporting older versions comes at the cost of handling multiple edge cases due to lack of API methods or support for some geometries.

**Obviously**, this cannot be done on a whim. We should consult our Mixpanel stats to figure out which versions still have significant number of MAU's, and even add exceptions if some of our direct clients have some critical need for them.

**Comment by jsdbroughton** [comment]
With my other hat on I can confirm that Revit 2019 has almost completely disappeared apart from some bigger projects now in construction where migration has always been seen as too problematic/high-risk. R2020 is still in heavy use.

Whether these are Speckle users is a different question, concur that the Mixpanel should user Skews show this up?

**Comment by jsdbroughton** [comment]
Last 30 days
![image](https://user-images.githubusercontent.com/760691/196389289-18d7f0c9-9beb-4de4-bf09-f3b2aa9a8c31.png)

**Comment by AlanRynne** [comment]
Closing this as the reason for it being opened was Revit 2019 which we no longer support. We can reopen when 2020 nears it's death!
