### ISSUE TITLE
bug(tekla): Saved Streams are not preserved

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1738]
## Description

When a stream is Saved via Tekla connector, saved streams are not preserved when file/project is restarted.

## Expected Behaviour

Kaydettiğim stream’i görmek isterdim.

## Steps to reproduce

1. Open tekla connector
2. Save a stream
3. Close Tekla Structures
4. Reopen Tekla Structures
5. Enable Speckle connector

## Streams/Commits Used

[https://speckle.xyz/streams/c1f59d8484](https://speckle.xyz/streams/c1f59d8484)

## Screenshots
Stream saved 👇
![image](https://user-images.githubusercontent.com/51519350/196444098-b66c7071-1dcc-454c-bff6-c61d0210fdd5.png)

Restarted Tekla, saved stream is not preserved.
![image](https://user-images.githubusercontent.com/51519350/196444142-97d9f301-53c7-438b-be33-02a9453f36b4.png)

**Comment by Reynold-Chan** [comment]
do we do this with other connectors ?

**Comment by bimgeek** [comment]
> do we do this with other connectors ?

yes we do with revit and rhino afaik

**Comment by fraguada** [comment]
@Reynold-Chan is there a PR associated with this issue? The status is set to Needs Testing, but I don't see where the issue has been referenced in a PR.
