### ISSUE TITLE
Revit: Issue with sending Rebar  (release 2.9)

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#1747]
![image](https://user-images.githubusercontent.com/45512892/196752405-8814fb48-8323-4b01-ac85-1965a64610b5.png)

Clearly `revitRebar.NumberOfBarPositions` can differ from `bars.count`

Steps to reproduce:
1. Send Revit's basic structural sample project

This line is suspicious, that last parameter [is the barPositionIndex](https://www.revitapidocs.com/2021.1/b3f84e4d-0a50-26ef-2edc-eb0678929f0c.htm). We are giving it the last index (at index `revitRebar.NumberOfBarPositions - 1`). Are the other curves just ignored then, are we assuming they are all the same count? 

https://github.com/specklesystems/speckle-sharp/blob/0a570408dbce6bc1c0e8565a651c41ff088dbd51/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertRebar.cs#L148

**Comment by AlanRynne** [comment]
Issue seems non-critical, so we'll be pushing it to `2.10`

**Comment by paloknapo** [comment]
Handled with new rebar conversion.
