### ISSUE TITLE
Bug(Revit): Revit doesn't enable object roundtripping with other programs

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#1750]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Revit

## Describe the bug

Revit is changing the application ids of objects that get sent in from other applications which stops those other applications from updating new geometry brought in from Revit.

## To Reproduce

1. Send objects to Speckle from non-Revit application (see [this commit](https://latest.speckle.dev/streams/f8991bf79d/commits/3854f14ead) from Rhino)
1. Receive those objects in Revit. Edit them if you want.
2. Send those objects back to Speckle (see [this commit](https://latest.speckle.dev/streams/f8991bf79d/commits/20ca63c45a))
3. Notice that the application IDs for the objects have changed.

## Expected behavior

The objects should have the same application ID in order for Rhino to recognize that they are the same objects

**Comment by AlanRynne** [comment]
Closing in favour of general issue #2635
