### ISSUE TITLE
feat(revit): NGON Meshes

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1771]
## Description

Currently, the geometry sent from Revit is sent as a triangular mesh. Revit geometry should be sent as NGON mesh instead of triangular mesh whenever possible.

## Why?

As a basis for this suggestion, the difficulties experienced when working with geometries received from Revit via Speckle in some architectural software can be shown👇:

### **Blender <> Revit Workflow**

In general, some additions (furniture, entourage, lights etc.) and adjustments are made on the architectural model from Revit in the Blender<>Revit workflow. Then, interior-exterior renders and/or animations are created from this final model.

Surface selection (eg a wall surface, door surface) and UV Mapping over triangular mesh geometry is very difficult and laborious. As a short-term solution to this problem, we applied the `Clear Mesh` option while receiving in Blender. However, if the source geometry from Revit was NGON instead, this situation would not be existent at all.

### **Sketchup <> Revit Workflow**

A similar situation applies to Sketchup. Sketchup is a push/pull-based software and the selection of faces is very important in geometry editing. Similar to Blender, we tried to find a solution to this problem by combining co-planar faces on receiving.

### **Revit Meshes in Rhino**

There are requests by users to bring the same feature to Rhino. If the source geometry was already NGON mesh, there would be no need to develop separate solutions for each connector.

## Suggestion

We should send the mesh geometry we send from Revit as NGON mesh whenever possible. Thus, we can avoid many similar situations.

## Streams/Commits Used

Stream below 👇 contains walls and rooms sent from Revit. Any commit sent from Revit can be used to confirm this issue.

[https://latest.speckle.dev/streams/209caa98a6](https://latest.speckle.dev/streams/209caa98a6)

## Screenshots

Revit mesh geometry in Rhino. ⏬
![image](https://user-images.githubusercontent.com/51519350/197686464-0ec39460-33c3-4ccd-b6a7-e016e2e2d5b9.png)

When geometry from Revit is received directly into Blender. ⏬
![image](https://user-images.githubusercontent.com/51519350/197686504-dbd074f0-973d-41bb-88ac-6211fd30f687.png)

When received with Mesh Clear option checked. ⏬
![image](https://user-images.githubusercontent.com/51519350/197686536-260dfff0-4152-4741-93c8-90fbe61bcc32.png)

**Comment by AlanRynne** [comment]
My 2 cents here:

Not sure this will be doable in all connectors. The way it's implemented in Blender uses specific blender functions to make this happen:

https://github.com/specklesystems/speckle-blender/blob/fbda0110cd53201bd4e57e605c055c53bf6c6cca/bpy_speckle/operators/streams.py#L327

This may not be available in all connectors, and even in the ones we do, it may not lead to the exact same NGon result.

On the Revit side, I'm fairly certain there is no ngon face support there, so all mesh faces will always be triangular or quad.

The only way to guarantee consistent results is to code this on our side. Which would require some complex geometry processing capabilities we don't have.🥲

**Comment by teocomi** [comment]
Triangular meshes are the most commonly supported type, while ngons are quite rare, so my preference is to keep things as they are.

Closing this as stale, we can discuss it again if needed.
