### ISSUE TITLE
Create shared project for ConnectorRhino versions

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#179]
This issue would include setting up solution properties to:
- Debug start actions to start the correct rhino version
- Potentially remove speckle command to run on rhino startup and instead add a debug start options command line argument

**Comment by teocomi** [comment]
I think a shared project might not be necessary since Speckle seems to be playing nice in Rhino 7 already.
If we want custom debug actions and command line args, a build configuration would be enough.

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
