### ISSUE TITLE
RhinoConnector Mac overriding the application name for Quit

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#1801]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/760691/198696525-95bdf537-b009-4819-a46b-fd79fb77bfb0.png">

**Comment by cwensley** [comment]
That uses `NSRunningApplication.CurrentApplication.LocalizedName`.  You'd need to either reset that to what it was after Avalonia messes it up, or get Avalonia to not do that.  I'm not sure what API is actually used to set that value, and I can't seem to find anything in the docs.  Maybe some Avalonia folk know how it is being set?

**Comment by AlanRynne** [comment]
DUI3 may fix this, so closing for now!
