### ISSUE TITLE
Remove deprecated User query from Core

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#1803]
After the release of 2.10, the currently deprecated methods should be removed from the Core SDK.

https://github.com/specklesystems/speckle-sharp/blob/release/2.10/Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs#L122

This will trigger some downstream changes in the connectors possibly.

- [ ] Remove deprecated method definition from Core
- [ ] Update affected connectors and DUI

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
