### ISSUE TITLE
Problem with Navisworks plugin when use version Speckle.Core 2.9.0

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1823]
- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

`Speckle.Core` Library version 2.9.0 have problem with load package SQL dependency, version 2.8.0 is good.

## Describe the bug

This is a bug relate to SQL lite dependent : 
First it will be show error, something like this : 

```
System.ArgumentException: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
```
this error can fix by init a SQLitePCL Batteries https://stackoverflow.com/questions/43811731/unable-to-load-dll-e-sqlite3-the-specified-module-could-not-be-found :

```cs
SQLitePCL.Batteries.Init();
```
But new error will be show : 

```cs
System.ArgumentException: System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

```

## To Reproduce

1. Open Navisworks 
2. Open Navis Addin Manager
3. Run command test

```cs
public class EleExtractParaCommand : AddInPlugin
{
    public override int Execute(params string[] parameters)
    {
        try
        {
            RunProcess();
            MessageBox.Show("Done");
            return 0;
        }
        catch (Exception e)
        {
            throw new ArgumentException(e.ToString());
        }
    }
    async void RunProcess()
    {
        SQLitePCL.Batteries.Init();
        // define the base object
        List<string> datas = new List<string>(){"1","2","3"};
        var commitObject = new Base();
        commitObject["datas"] = datas;
        commitObject.totalChildrenCount = datas.Count;
        // get speckle account by client 
        // string url = "https://speckle.xyz/streams/14568be237/commits/f735d15c8e";
        // StreamWrapper streamWrapper = new StreamWrapper(url);
        Account defaultAccount = AccountManager.GetDefaultAccount();
        MessageBox.Show(defaultAccount.userInfo.name);
        string streamId = "14568be237";
        await Task.FromResult(streamId);
    }
}
```

5. See error
-->

## Expected behavior

It will be run like version 2.8.0

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: Windows 10
- Version Navisworks 2022

## Proposed Solution (if any)

resolve problem with some package dependency

**Comment by teocomi** [comment]
Hello @chuongmep !
The Navis connector is not officially supported yet hehe but maybe @jsdbroughton can give some guidance ;)

**Comment by chuongmep** [comment]
Problem resolved now
