### ISSUE TITLE
Some Pointclouds not sending from Revit to Speckle

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1824]
A couple of users have reported this:

- https://speckle.community/t/speckle-dont-send-all-data-point-cloud-from-lidar-mobile/4034
- (private PM): https://speckle.community/t/youre-a-new-user-of-the-year/3967/15

**Comment by chuongmep** [comment]
Duplicate with #1816

**Comment by teocomi** [comment]
Closing as duplicate :)
