### ISSUE TITLE
Bug: Grasshopper7 Converter dll could not be loaded during Archicad receive

### ISSUE THREAD

**Issue by jozseflkiss** [specklesystems/speckle-sharp#1826]
## Prerequisites

1. Apple Silicon (ARM) only issue
2. Grasshopper and Archicad connectors are present
3. Can be reproduced only on developer machines (or later when Archicad ARM is released and relevant Speckle Connector is out)

## Describe the bug

In general, during receiving streams from the server, the installed Speckle Kit dlls (~/.config/Speckle/Kits) are loaded to retrieve class information (`LoadSpeckleReferencingAssemblies` function).
If you have Grasshopper connector installed and Archicad connector is being debugged, the Objects.Converter.Grasshopper7 cannot be loaded. (Originally this canceled the receive operation, now this exception is handled).
The root of this issue is the following:
* the developer machine has Visual Studio and .NET runtime for ARM is installed, so the runtime is arm64 under the debugger
* Archicad Connector is built with "AnyCPU" which can be loaded the debugger
    `file ./ConnectorArchicad/bin/Debug/net6.0/ConnectorArchicad.dll`
    `PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows`
* Objects.Converter.Grasshopper7 is built with TargetFramework net48, which has x64 platform target
    `file /Users/lkj/.config/Speckle/Kits/Objects/Objects.Converter.Grasshopper7.dll`
    `PE32+ executable (DLL) (console) x86-64 Mono/.Net assembly, for MS Windows`
* x64 platfrom target dll cannot be loaded to arm runtime

With the production, released version of Speckle it is OK, since we release the x64 version of ConnectorArchicad (having the runtime selfcontained, with Rosetta it runs on ARM).

## To Reproduce

1. Install Grasshopper Connector
2. Debug ArchicadConnector on ARM mac

## Additional context

<img width="415" alt="image" src="https://user-images.githubusercontent.com/50739844/201058505-9e312f1b-2db4-4fa1-b78f-3c7783c8e0f7.png">
https://stackoverflow.com/questions/4284351/whats-the-difference-between-pe32-and-pe32

## Proposed Solution (if any)

In my opinion the usage of the arm version of .NET runtime on developer machine is correct. I think we don't have to build platform specific builds on developer machines, instead we might need to change the GH dll to not to have a specified platform target.

**Comment by teocomi** [comment]
Not sure why the `TargetFramework` is set to 4.8 in the GH converter. All converters and Objects should be on `.net standard 2.0`, [see](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Converters/ConverterRevit/ConverterRevit2023/ConverterRevit2023.csproj#L4).
Maybe something slipped when the converters got split up @AlanRynne ?

**Comment by gjedlicska** [comment]
I can repro this :)

**Comment by jozseflkiss** [comment]
@AlanRynne  this can be reproduced with v2.12 also.

**Comment by AlanRynne** [comment]
I've assigned myself and @gjedlicska to this to make sure we keep it in our radar for the upcoming release. Since it's a Debug only problem it's low priority, but @jozseflkiss also told me he's making some changes soon that may be impacted by this.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
