### ISSUE TITLE
feat(rhino): Simpler Material Naming

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1833]
## Description

Reported during the meeting with Alex Poulsen:

Currently, the naming system of materials coming from Revit is too long and difficult to distinguish. Our current naming system is:

`Stream Name [branch name @ commit id] - Material Name`

The fact that the name of the stream is in the first place makes things difficult. Because the entire Material name is not visible in the Rhino material interface, which makes it difficult for the user to understand which material is what. Take a look at the screenshot below👇.

## Expected Behaviour

In my opinion, it is sufficient to show only the Material Name. There is no need to add other information. Blender is a good example for this and no issues reported on that side so far. So the new material naming system should be only `Material Name`.

## Steps to reproduce

1. Open Rhinoceros and enable Speckle connector.
2. Receive the commit below.
3. Go to Rhino Material Interface and check the material names.
4. You will find that it is impossible to distinguish because all material names start the same.

## Streams/Commits Used

[https://latest.speckle.dev/streams/1fedfb65da/commits/24841d0e4f](https://latest.speckle.dev/streams/1fedfb65da/commits/24841d0e4f)

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/201269808-8c88dd42-2a5d-4d60-9ceb-a4fdde142a4e.png)

**Comment by JR-Morgan** [comment]
In Unity and Unreal connectors, we are naming materials as `"{name} - {id}"` only. 
I'm not convinced that the stream + branch + commit info is really necessary, the id prop guarantees the material's identity.

If that makes sense for Rhino, then it would be nice to align.
