### ISSUE TITLE
chore(core): Remove all usage of `DynamicBase` obsolete members

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1837]
`2.11` should no longer be used anywhere in our code, and should add the `throw error` input to the `Obsolete` attributes to prevent anybody from using them from now on.

**Comment by AlanRynne** [comment]
@JR-Morgan we should pick this up again!

**Comment by teocomi** [comment]
Changing to ToDo as there is no linked PR
