### ISSUE TITLE
Revit can't send data when a mechanical base on wall 

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1843]
## Describe the bug

bug cause when have a mechanical base on wall

## To Reproduce

File Sample : https://1drv.ms/u/s!AmKukXZ0HxiEle42Xlkt7xdQTLjGHA?e=joK22O
Stream : https://speckle.xyz/streams/ce16dcdd66/branches/bug
## Expected behavior

wall and air condition will be push to stream

## Screenshots
File revit  :
- In Revit File : 
![image](https://user-images.githubusercontent.com/31106432/201476342-08d7a369-bfd7-40bc-9a63-4cd675d619c1.png)
- Case push two object to stream, just wall in stream : 
![image](https://user-images.githubusercontent.com/31106432/201476200-57fcd653-c496-4b7d-aede-eb1fb970da88.png)
-Case Just send air condition : 
![image](https://user-images.githubusercontent.com/31106432/201476303-8e5de90b-be5a-4725-b565-6f3364b7a0ba.png)

## System Info

Revit 2023 
Connector : 2.9.0

**Comment by connorivy** [comment]
Hey @chuongmep,

Thanks for raising this issue! You are right that this was a limitation in the Speckle revit connector v2.9. I believe we now have a fix for it in the connector version 2.10.

Could you try to receive this again using the latest 2.10.0-rc1 pre-release version? You can get that by navigating to the revit connector page in the Manager for Speckle application and then hitting the versions tab in the top right. 

The objects won't receive correctly if you try to receive your existing commit. You'll have to send the items to speckle again and then receive the new commit. Let me know how it goes.

**Comment by chuongmep** [comment]
@connorivy same problem, need more fix
![image](https://user-images.githubusercontent.com/31106432/202500227-8cfac1da-412c-4141-bcf6-52f712579a99.png)

**Comment by connorivy** [comment]
Hmm that's strange because it is working for me
https://latest.speckle.dev/streams/85bc4f61c6/commits/31fe22418b
![image](https://user-images.githubusercontent.com/43247197/202501827-9390c1ef-198b-448d-a443-5d8935c1328b.png)

I'll try to find where that error is coming from but it doesn't look familiar to me

**Comment by chuongmep** [comment]
@connorivy can I ask the team have any trace log to develop for process, how to catch red like this in revit ?

**Comment by connorivy** [comment]
@chuongmep 

Currently we don't capture the trace log like your are suggesting, but I think that is a very good idea so I opened up an issue for it -> https://github.com/specklesystems/speckle-sharp/issues/1869

**Comment by chuongmep** [comment]
Nice!

**Comment by chuongmep** [comment]
Confirm problem resolved in version 2.10 rc1! 
https://speckle.xyz/streams/ce16dcdd66/commits/b1ebf59af6

**Comment by chuongmep** [comment]
Confirm problem resolved! 
https://speckle.xyz/streams/ce16dcdd66/commits/b1ebf59af6

**Comment by chuongmep** [comment]
Still have minor problem with selection, when we select to a wall, also select air condition.
![msedge_vzIQCY2Dqw](https://user-images.githubusercontent.com/31106432/202590396-9add9922-d0a2-46ab-8843-f03505653192.gif)

**Comment by chuongmep** [comment]
In list stream data still is wall, not include mechanical equipment
![image](https://user-images.githubusercontent.com/31106432/202590691-b486d90a-c545-433a-bdb5-ad1c1b68ee11.png)

**Comment by connorivy** [comment]
@chuongmep 
![image](https://user-images.githubusercontent.com/43247197/202733834-64d06e9f-ff9b-4dbe-a8dd-9b259f6fcde1.png)

Because the mechanical equipment is attached to the wall, it is sent as a child element which means that you can find it under the "elements" property of the wall

**Comment by chuongmep** [comment]
@connorivy  I don't agree with the way you are saying, what if I have the power outlets assigned to the wall, which means that every time I list the electrical outlets I need to get all the walls then I can count them. number of sockets ? 
@teocomi this is a very serious data statistics problem, feel free to comment on this section

**Comment by teocomi** [comment]
Hey @chuongmep I understand your point and that's totally valid.
Currently all children elements are treated this way.

We can definitely revisit this in the future, but it would mean adding more complexity when trying to find parent-child relationships.

**Comment by chuongmep** [comment]
Thanks @teocomi. I sure that is a important in future when user start use data with get by category.
