### ISSUE TITLE
Rhino crash when clicking on GH Menu -> Speckle2 ->Open Speckle Manager

### ISSUE THREAD

**Issue by fraguada** [specklesystems/speckle-sharp#1878]
Clicking on the Speckle2 menu -> Open Speckle Manager crashes Rhino

Rhino for Mac Version: 7.23.22282.13002, 7.24.22301.23002
Speckle Version: 2.10.0-rc1, rc3
MBP M1, MBP 2015

edit: this does not occur on Windows with the same Speckle release

**Comment by AlanRynne** [comment]
Should be fixed in the next `rc` release
