### ISSUE TITLE
Allow overriding default Speckle paths

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1880]
We should allow overriding of default speckle paths via Env Variables and programmatically.
Currently, this has been allowed in core for the `UserApplicationDataPath` folder, see: https://github.com/specklesystems/speckle-sharp/pull/1879

What still needs to be done:
- [x] propagate the change in SpecklePy
- [ ] (optional) propagate to the installers
- [ ] look at other paths that will need a similar treatment (eg the `InstallApplicationDataPath`)
- [x] align with proposed changes in the Blob storage PR https://github.com/specklesystems/speckle-sharp/blob/core/blobSupport/Core/Core/Helpers/Path.cs#L28

**Comment by gjedlicska** [comment]
@teocomi do we need to add this behavior to the install path too now?

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
