### ISSUE TITLE
Add Revit receiver error for geometry that fails on commit (not convert)

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#189]
- Came up when receiving BuiltElements (ft) in a Revit doc (mm).
- Look into unit conversion debugging
- Suppress revit error modal and log this in the UI instead?

**Comment by didimitrie** [comment]
Action: we'll need to transform this into a bug report. More info needed: 
- built elements sent from gh/rhino/revit?
- replication instructions/sample file

**Comment by clairekuang** [comment]
![image](https://user-images.githubusercontent.com/16748799/109539787-9dce1800-7ab9-11eb-8b7f-52bde34a7d56.png)

Caused by trying to create a wall from a base line that was too small.

**Comment by teocomi** [comment]
Possibly related to this: https://github.com/specklesystems/speckle-sharp/issues/230
