### ISSUE TITLE
feat(acad): Conversion of 3D polycurves to splines

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1906]
## Description

Currently when a user receives a 3D polycurve with an arc, that element will be under failed conversions on report. Because AutoCAD can’t generate a 3D polycurve with an arc if its not linear. So it needs to convert them into a spline. We don’t do this currently and show this conversion as failed. Eventhough the geometry is still generated but not as a spline but as individual elements of the polycurve.

- Better conversion for 3DPolyCurves to Splines needed.
- Don’t show these elements under `Failed` but show under `Created` with a message.

## Steps to reproduce

1. Try to receive Rhino test stream in Autocad.
2. Take a look at the 3D Polycurve with an arc. It will be different from the objects right next to it.

## Streams/Commits Used

[https://latest.speckle.dev/streams/3ed8357f29/branches/rhino2autocad](https://latest.speckle.dev/streams/3ed8357f29/branches/rhino2autocad)

## Screenshots

Speckle Viewer 👇

![image](https://user-images.githubusercontent.com/51519350/203547826-20f99c32-e353-49fc-bfc4-48780886e81a.png)

Autocad 👇

![2vH545IqjA](https://user-images.githubusercontent.com/51519350/203547847-24575c66-c6b7-4b8f-94e9-794763ae2250.gif)

**Comment by clairekuang** [comment]
The reporting has been fixed, but the spline conversion will probably have to be added as a receive setting!
Autocad api for joining entities fails on these curves, so this may need to be done via calling the `Join` command

**Comment by clairekuang** [comment]
After some more investigation, I don't think it's worth it at this point to start implementing commands (due to language pack reasons). Since the report issue has been resolved and now selecting the report item will select all created polycurve segments, the user can manually join them more easily via command which for now should be good enough.
