### ISSUE TITLE
Rhino: 2.10 issue with receiving Blocks

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#1909]
receiving blocks do not get generated

![image](https://user-images.githubusercontent.com/45512892/203570355-bb9f90f4-6802-4688-8bee-25f6d18a777e.png)

No errors in report

![image](https://user-images.githubusercontent.com/45512892/203570302-1a902159-2682-45cb-a606-0986b59be0f8.png)

**Comment by fraguada** [comment]
FWIW also fails on Rhino for Mac
