### ISSUE TITLE
Bug(Revit): Family instances flagged as MEP elements not sending to Speckle

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#1915]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Revit Converter

## Describe the bug

Previous the contents of the Revit model [here](https://we.tl/t-IcsBS0Lixx) (Revit 2022) would send to Speckle as family instances correctly, but now the elements are getting flagged as MEP elements (and they are) but they are not correctly sending to Speckle.

Here is the error that the report is showing for both elements
![image](https://user-images.githubusercontent.com/43247197/203632733-cb4fb5ca-b951-41eb-a75f-8228eacb5e6f.png)

## To Reproduce

Download the revit file -> https://we.tl/t-IcsBS0Lixx
Open in Revit 2022
Send all 4 objects to Speckle
The 2 MEP elements fail to convert

## Expected behavior

All elements convert successfully

### Desktop (please complete the following information):

- OS: Windows11
- Revit Version: 2022
- Version : 2.10.0-rc3

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
