### ISSUE TITLE
One click send crashes when sending to stream without user logged in

### ISSUE THREAD

**Issue by jozseflkiss** [specklesystems/speckle-sharp#1918]
If no user is signed in, there is a send button, it crashes when trying to send the model:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/50739844/203717950-2fff4306-39c8-4a4d-ab49-7e351f98f243.png">

If you have alread signed in, just delete the files in "C:\Users\tester\AppData\Roaming\Speckle\" folder.

**Comment by teocomi** [comment]
This is actually not just an Archicad issue; looking into it!
