### ISSUE TITLE
Grasshopper: DSO no longer supports dictionaries

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1927]
Regression from earlier versions (tbd on which) reported in https://speckle.community/t/excel-grasshopper/4251/2

DSO node should understand Dictionaries (and expand them as it does with Base objects) but it does not.

**Comment by AlanRynne** [comment]
This fix would require some changes in the DSO component that I'm not comfortable rushing into 2.10. There is a workaround to this edge-case so it's not really blocked. And an issue has been opened in excel to deal with their side of the issue https://github.com/specklesystems/speckle-excel/issues/40

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
