### ISSUE TITLE
Can't Send Object In Enviroment Revit Family Document

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1928]
## Prerequisites

- [ ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [ ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

This is a bug when opening revit, create a new family and want commit geometry in family document to stream

## To Reproduce

1. Go to Revit
2. Create a new family
3. Create an Extrusion
4. Send to stream
5. See error

## Expected behavior

Geometry family will be send to speckle.

## Screenshots

![image](https://user-images.githubusercontent.com/31106432/204000203-c7e57df4-e03c-46c8-af71-b2c0f5e7393b.png)

## System Info

Windows 10 : 
Speckle Version 2.10 Rc4

#### Optional: Affected Projects

https://speckle.community/t/probem-with-complex-family/4260/4)](https://speckle.community/t/probem-with-complex-family/4260/4

**Comment by teocomi** [comment]
This is a known limitation, only meshes sent as direct shape elements are supported in the family editor.

**Comment by chuongmep** [comment]
@teocomi They are suspended when this happens, we should have a stop process and notify users ?

**Comment by chuongmep** [comment]
May be in there we should check what element we support first before run in RevitTask.RunAsync process, because Task is hard to debug in Revit.
https://github.com/specklesystems/speckle-sharp/blob/d55372525d4f1aec9a2bd7098bfbc7fe0aa17290/ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs#L46

**Comment by teocomi** [comment]
Oh I see, sorry I confused sending with receiving!
When sending, elements that do not have a direct conversion (like extrusions in this case) should just be sent as meshes, I guess something is failing in the conversion, we'll look into it :)

**Comment by Zhuangkh** [comment]
The reason for the exception is that the family document does not have the `ProjectInformation` property, which is a small problem that can be easily fixed. see https://github.com/specklesystems/speckle-sharp/pull/1945.

However, `CombinableElement`(Form/Extrusion/...) from a family document doesn't have a category property, which the current sending logic requires element to have.

Do you think it's necessary to support sending objects in family documents?

**Comment by chuongmep** [comment]
@Zhuangkh Yes, It's really useful.

**Comment by teocomi** [comment]
Good find @Zhuangkh ! 
If needed, we can group `CombinableElement` under a made-up category when sending to allow them to go through...
