### ISSUE TITLE
Curtain Wall Mullion and Curtain Wall Panel Categories not supported

### ISSUE THREAD

**Issue by martinromby** [specklesystems/speckle-sharp#1938]
Please consider adding the Curtain Wall Mullion and Curtain Wall Panel Categories to supported categories in the Revit connector.

**Comment by ks-cph** [comment]
https://github.com/specklesystems/speckle-sharp/blob/c90b288863b602bf584398b7e60f5812612e7d86/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertFamilyInstance.cs#LL37C6-L56C8

**Comment by ks-cph** [comment]
The comment is correct, we need to make sure that the elements are not generated twice. In my opinion, two options would solve the problem:
1. The wall itself does not have a geometry and only references the mullions and panels in the elements[]- Array; Mullions and Panels are regularly converted as `FamilyInstance`
2. The `CurtainWall` is converted as it is but to make sure the information for mullions and panels is exported, the elements are generated without the geometry.
3. Convert mullions and panels as independent elements.

I would propose implementing the first option. I can make a PR and someone reviews it?

**Comment by teocomi** [comment]
Thanks for the investigations @ks-cph ! We'll be looking at this in the next few weeks, if you want to send a proposal PR in the meantime, that'd be great.

You might already know it, but branch off from `dev` as that's the "work in progress 2.15" branch.
