### ISSUE TITLE
RevitConverter: line-based elements convert curves into baseCurve and baseLine

### ISSUE THREAD

**Issue by ks-cph** [specklesystems/speckle-sharp#1943]
The RevitConverter adds an object for the base curve for line-based objects. For some categories the Converter creates them as `baseCurve` sometimes as `baseLine`. For instance, columns, walls and beams get an object `baseLine` while pipes and railings get `baseCurve`

I would suggest aligning the naming convention to `baseCurve`

**Comment by teocomi** [comment]
Hey @ks-cph ,

Yes, I agree that any prop of type `ICurve` should be consistently named :) Are you happy to make the PR?
Cc @clairekuang as she's helping us coordinate changes in Objects across connectors.

One thing to keep in mind is that this might break some grasshopper definitions, and as such, we should deprecate old constructors like this: https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Objects/BuiltElements/Column.cs#L84
