### ISSUE TITLE
RevitConverter: Material quantities add length of elements

### ISSUE THREAD

**Issue by ks-cph** [specklesystems/speckle-sharp#1944]
Related to issue #1302 and PR #1314 
#1314 implements the `material_quantities` to the revit connector. `material_quantities` contains the volume and area of each `Material` in an element. 

Sometimes it is alos essential to have the length of an element divided by `Material` Thus, I would like to add another parameter to material quantities.  Besides `area` and `volume` it should also have a `length`.

Please let me know if you see any problem with that?

Cheers,
Kilian

**Comment by teocomi** [comment]
I don't see issues with it, please go ahead :)

**Comment by fraguada** [comment]
@connorivy @AlanRynne @ks-cph  what is left to do to close #1976

**Comment by connorivy** [comment]
@fraguada The ball is in my court. I haven't been working on Revit at all this sprint which is why this hasn't been closed yet. I just made my last structural PR that I'm going to make this sprint so I'll work on this now.
