### ISSUE TITLE
Non json ignored get only properties wreak havoc for new GetMembers implementation

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#1969]
Since this change to DynamicBase #1620 
Calling `GetMembers(DynamicBaseMemberType.Instance)` throws for Object models that have `get` only properties that aren't json ignored.

This is because get only properties will be deserialised as dynamic properties, and we end up with both instance and dynamic properties of the same name.
This scenario has undefined behaviour, and is actually the source of the bug.

We should decide on what behaviour is desirable and stick to that.
In the meantime, i have a band-aid fix for GetMembers, but this is just a temporary fix to GetMembers throwing.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
