### ISSUE TITLE
feat(archicad): Soften Internal Edges of received geometry

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1972]
## Description

Currently receiving a geometry in Archicad comes with these ugly mesh edges. Check screenshots below 👇.

## Expected Behaviour

Internal edges should be hidden. Thus a clean representation will be obtained in Plan/3D Views.

## Current Workaround

Currently, users can select received geometry and go to `Morph options` > `Edge Type` and select `Hidden` option to hide all edges. Check the screen recording below to see this in action 👇.

## Steps to reproduce

1. Open Archicad and enable Speckle connector
2. Receive below stream.
3. Examine the received geometry.

## Streams/Commits Used

[https://latest.speckle.dev/streams/b0ca08d801](https://latest.speckle.dev/streams/b0ca08d801)

## Screenshots/Recordings

https://user-images.githubusercontent.com/51519350/205292047-ae730787-2900-4b28-874b-52c1f4e877ce.mp4

---

Visible Edges 👇

![image](https://user-images.githubusercontent.com/51519350/205291944-0a871bba-2e10-4307-bf51-47bd5e34b36e.png)

![image](https://user-images.githubusercontent.com/51519350/205291973-fb433284-901b-44c6-9629-e61beec5c204.png)

Hidden Edges 👇

![image](https://user-images.githubusercontent.com/51519350/205291999-d64a9fde-20ae-4813-81ae-1c897b1c97ac.png)

![image](https://user-images.githubusercontent.com/51519350/205292026-65e9f0f5-6a6d-4390-8bc2-0e8fbf2284dc.png)

**Comment by jozseflkiss** [comment]
https://github.com/specklesystems/speckle-sharp/pull/2127
