### ISSUE TITLE
Update readme/contributions page

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1977]
We should update the readme & contributions with information of how we work and how PRs should be submitted (eg targeting the `release` branches instead of `main`)

**Comment by chuongmep** [comment]
Problem relate @1876

**Comment by AlanRynne** [comment]
There's been talks around the team of changing this behaviour so that the _default branch_ would be the one everybody needs to PR into.

The current git workflow we're following does cause some internal and external friction.
