### ISSUE TITLE
Objects: Enforce alignment of `dotnet` and `python` SDKs with tests

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1999]
Mirror issue of specklesystems/specklepy#237
# Description

This is born out of @gjedlicska's fights in `specklepy`, and the realisation that we are constantly miss-aligning both our SDKs in many subtle but important ways.

Minor changes in how our objects are serialised, the type of their properties or their nullability, will have breaking effects in the other SDKs, and it's quite a difficult thing to keep track of.

This greatly affects the stability of our product, as workflows that depend on _cross-language_ to work (Rhino -> Blender, QGIS -> Unity, ...) will most likely break when the definition of objects is not the same across `python` and `dotnet`.

# Proposed solution

A good solution for this would be to have some way of testing if the implementation on both sides is correct. i.e:
- That the object exists in the SDK
- That the object contains the same properties in it's definition
- That the object properties have matching Types and nullability

This would require the creation of some sort of "conformance testing" that would work across languages.

Our initial idea would be to:
- Consider `speckle-sharp` the main **source of truth** as for what our objects are.
- Generate some sort of `type definitions` from speckle-sharp that would be _language agnostic_ (this doesn't have to be a json schema in particular... but it would be nice)
- Use those generated `type definitions` to verify that **all objects** across programming languages are defined in a consistent way.

Furthermore, we could add a layer of cross-language validation on top of this with some _mocked values_:
- Using a mock library (in python, dotnet or both?) to generate a set of object instances for each available class.
- Serialise those instances into JSON
- Verify that the generated JSON can be deserialised in the other language, and that the type/values are consistent.
- This could be chained up to verify "round-tripping" of objects between specklepy and speckle-sharp works consistently too.

# Examples of why this is necessary

- Misaligned SDKs can be a major source of problems, and will affect the overall "quality" of what we deliver. It's very easy to introduce new changes that are single-sided, very difficult to catch them down the line in a different language than the original.
- https://speckle.community/t/child-class-speckle-type-deserialization-issue/3803/6
- More to come

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
