### ISSUE TITLE
Allow function pick link element to push data

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#2003]
## Prerequisites

- [ ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [ ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [ ] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the solution you'd like

It will be useful if we allow user pick element in link to push not is all at the moment, some more option can think : 

- Select : Link Element and element
- Select : Link Element
![image](https://user-images.githubusercontent.com/31106432/207243725-52519884-22c2-46a5-b920-247e23862a57.png)

**Comment by teocomi** [comment]
Hi @chuongmep are this options for sending linked elements not enough? https://speckle.guide/user/revit.html#sending-linked-models

**Comment by chuongmep** [comment]
Hi @teocomi, in my case, I just push all element of linked model on crop box view and select some element from linked to send, at the moment just have function push all element from linked model.
