### ISSUE TITLE
Revit connector cannot send some lighting fixtures with ceilings

### ISSUE THREAD

**Issue by majidaldo** [specklesystems/speckle-sharp#2004]
## Prerequisites

- [x ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [ x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

RevitConnector

## Describe the bug

When you send a Revit model with lighting fixtures, some of them do not 'convert' because they don't 'attach'. It's curious that it alternates b/w sent and errored (not sent).
If ceilings are excluded from the selection, the lighting fixtures go through (as there is no attempt to attached them to anything).

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3588248/207463253-301a97db-e490-4ec3-8d30-f78bcbd8532d.png)
[model.zip](https://github.com/specklesystems/speckle-sharp/files/10222833/model.zip)

## Expected behavior

Lighting fixtures should 'attach' to ceilings.

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: Windows 10
- Revit: '22
- SpeckleConnector: 2.10

## Proposed Solution (if any)

workaround: setting to send detached objects.

**Comment by teocomi** [comment]
Hey @majidaldo apologies this took a while, this has been fixed in some of our recent MEP prs! Will be included in 2.16!

**Comment by connorivy** [comment]
Hi @majidaldo,

2.16 hasn't been fully released yet, but in the meantime you can download a work-in-progress version of the 2.16 connector by toggling on the "Show pre-releases" option and using the latest wip version from the Speckle manager.
![image](https://github.com/specklesystems/speckle-sharp/assets/43247197/5217c3fc-d0e9-4b80-a338-8991f86611c5)
