### ISSUE TITLE
bug (Navisworks): Angle Send Object Rotate 90 Navisworks Connector

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#2015]
## Prerequisites

- [ ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

Model
![image](https://user-images.githubusercontent.com/31106432/208330265-4360518b-7531-41b9-b98e-ef137c609d73.png)

When we commit
![image](https://user-images.githubusercontent.com/31106432/208330289-8452f2f7-5e15-4443-b77f-ebf7c1ae33fa.png)

This is unit transform 
![image](https://user-images.githubusercontent.com/31106432/208330432-0ec1463a-a552-4696-b9af-d9447ded8652.png)

Format file : dwfx 
Source file come from : Plant3D

## To Reproduce

1. Go to Navisworks , open test.nwf : https://1drv.ms/u/s!AmKukXZ0HxiElfRdh3apFYTy4d-d6Q?e=y7eiXb
2. Click on Object
3. Send Object To Speckle
4. See error : https://speckle.xyz/streams/24036875aa/commits/6b5ddb4214
![image](https://user-images.githubusercontent.com/31106432/208331649-17bdb158-280a-4e27-a4f2-780f53417b13.png)
![image](https://user-images.githubusercontent.com/31106432/208331662-cd649d28-d0ea-4bd4-a1ec-026f11247fce.png)
![image](https://user-images.githubusercontent.com/31106432/208331929-1f25c0bc-e033-4a1b-936f-ce05ef1dda79.png)

## System Info

If applicable, please fill in the below details - they help a lot!

**Comment by jsdbroughton** [comment]
This is replicable with some of the Navisworks sample models.

**Comment by jsdbroughton** [comment]
Source data for comparison. 

Where Up Vector and North Vector are as Navisworks default, 0,1,0 Up and 0,0,-1 North, Current conversion flips the Y and Z axis.

If Up Vector and North Vector are modified to 0,0,1 Up, and 0,1,0 North Current conversion is correct. (most of my source models were these) 

It seems when the first append to a blank ActiveDocument is from Revit/IFC that, Navis automatically corrects the Y/Z problem.

## Possible Solution

File Object checks on beginning transformation and generates a corrective TransformMatrix. This can then be applied to vector translation routines to correct transformation. I will check for them before the RealWorld transformation or post. - maybe it doesn't matter.

**Comment by jsdbroughton** [comment]
https://speckle.xyz/streams/7ce9010d71/commits/c2616bd26b

![image](https://user-images.githubusercontent.com/760691/210084970-b7abf22c-652d-44ac-8ad6-3ec739de03dd.png)

**Comment by jsdbroughton** [comment]
Additional instances were found of instances of differently-handed geometry. Thanks, @chuongmep.

The initial report suggests the generative source software varies - which suggests Navisworks on append is compensating (smartly) Also apparent is that, like the initial examples, the errors are a cartesian unit (90°) to a control axis.

Not yet testing for the impact of user transforms.

Speculative steps toward a more robust fix.

- Orientation checking of the File level container stored and cross-referenced to the Speckle platonic ideal
- Extract the orientation-fix code and expand it to include test cases based on the input reference model
- Assemble test model materials for release regression and acceptance testing

![image](https://user-images.githubusercontent.com/760691/212296846-f917c157-eaa1-4abb-8428-484341de548a.png)
https://speckle.xyz/streams/14568be237/commits/a37bc7ef80

![image](https://user-images.githubusercontent.com/760691/212296897-ffdfb186-f02f-4d15-bff6-9016fe7af2ef.png)
![image](https://user-images.githubusercontent.com/760691/212296908-2f2bff20-ba4f-4c85-9523-e9bf9d50200b.png)

**Comment by jsdbroughton** [comment]
![image](https://user-images.githubusercontent.com/760691/218785593-9db830e1-02a5-4e9e-a4a4-f5d5c7c34100.png)
