### ISSUE TITLE
Dynamic Base not allowing typed properties from being set  

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#202]
The introduction of property names validation has broken the Revit connector :)
The connector needs to set instance member on Base objects but that's not allowed by https://github.com/specklesystems/speckle-sharp/blob/e1e4a95c475f01670c662f3ad81b9d98764870dd/Core/Core/Models/DynamicBase.cs#L79

I'm not sure what the reasoning behind that line is, but I'm going to disable it temporarily, @AlanRynne let's chat on Monday.

**Comment by AlanRynne** [comment]
Oh no! Yeah feel free to disable it, it was on the list of validation rules we had come up with but if ir breaks stuff we can definitely ditch it.

**Comment by zhukoven** [comment]
@teocomi thanks for looking into the issue. I switched off this check and senders work.
