### ISSUE TITLE
bug(Navisworks): Crash on long idle session

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2021]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

ConnectorNavisworks

## Describe the bug

On long idle session, the DUI triggered a CLR Exception uncaught which results in terminal crash report.

## To Reproduce

Launch Navisworks, Initiate DUI interaction. Go and have a cup of coffee. Return. Sob

## Expected behavior

Application not crashed

## Screenshots

![image](https://user-images.githubusercontent.com/760691/208675649-b3b996c2-8a64-4da0-8dc7-9873f029c315.png)

If applicable, please fill in the below details - they help a lot!

### System:

- Windows: 11
- Navisworks: 2023
- SpeckleNavisworks: 2.11.0.alpha1

## Failure Logs

[dmpuserinfo.zip](https://github.com/specklesystems/speckle-sharp/files/10268676/dmpuserinfo.zip)

**Comment by jsdbroughton** [comment]
Alternatively, it is `mscorlib.dll` that is the crashed module.

**Comment by jsdbroughton** [comment]
Consistent dump analysis pointing to Avalonia tasks as a source.

May need help from @teocomi capturing this so as to not leave this Exception unhandled.

![image](https://user-images.githubusercontent.com/760691/210842982-c986688c-7cbe-493a-b266-28b4462c31c1.png)

**Comment by teocomi** [comment]
Not sure if it could help at all, but you could try adding this to the loop:

https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs#L202-L204

In Revit, it helped make the app responsive during receive, see convo: https://github.com/AvaloniaUI/Avalonia/discussions/8782#discussioncomment-3434577

**Comment by jsdbroughton** [comment]
I have already implemented this. :'(
