### ISSUE TITLE
bug: Civil 3D connector not sending corridor object in stream anymore

### ISSUE THREAD

**Issue by joostschlebaum** [specklesystems/speckle-sharp#2065]
The Civil 3D connector stopped sending corridor models with the following error:

Autodesk.Civil.DatabaseServices.Corridor 176B8 Failed
eNullObjectId

![c3dspeckleerror](https://user-images.githubusercontent.com/77269459/212054888-f7ff6168-ad91-4a6f-be94-ba7efeb4dc06.PNG)

Last time this stream was updated and the connector was used succesfully is about 30 days ago. Since then I did not use the connector until today to update a stream on a project, without success. 

It seems to be just the corridor's that aren't working. Other types of geometry stream just fine. I am using the latest version of the connector. The previous version which I also tried throws the same error.

Unfortunately I cannot share the DWG file with the corridor, but happy to share screens or more info if needed.

**Comment by teocomi** [comment]
Hey @joostschlebaum, thanks for reporting this issue; while we look into it can you please confirm if every corridor is affected or only that specific one in your project?

As a workaround for now, you can downgrade the connector and send from there.

**Comment by joostschlebaum** [comment]
Hey @teocomi , thanks for your quick reply.
I did some troubleshooting and have traced down the issue. It is in the corridor surfaces. It seems the connector either doesn't check the checkmark of the surface (and tries to send it anyway) OR it tries to retrieve the geometry first. The corridor surface in my case is empty (the conditions to create the surface were changed) so the error (object = null) seems valid. Deleting it alltogether fixed it for now. 
Maybe it can be fixed by checking if its checked, and when no skip it.

![image](https://user-images.githubusercontent.com/77269459/212071759-af39bb41-2218-4082-9098-59aa7f0dd22b.png)


Let me know if you need anything else.

Thanks

**Comment by teocomi** [comment]
Amazing, thanks for investigating, we'll get on this early next week :)
