### ISSUE TITLE
Archicad Connector geometry fidelity

### ISSUE THREAD

**Issue by jozseflkiss** [specklesystems/speckle-sharp#2098]
Problems to solve:
- Receive
  - Import render materials to Archicad for Morph elements
  - Edges created by the tessellatation from the sender side, will be hidden when importing (import edges as "soft" and "hard" edge)
  - Instead of exploding elements by meshes and generating several Morphs in Archicad, always one element is created
  - Introduce GDL Object import and reuse geometry if available
  - Import Revit family instances as GDL Objects
- Send
  - Export missing hierarchical elements (Stair, Railing)

Out of scope
- property import, export

## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Archicad Connector

## Is your feature request related to a problem? Please describe.

Will solve:
https://github.com/specklesystems/speckle-sharp/issues/1973
https://github.com/specklesystems/speckle-sharp/issues/1972

**Comment by AlanRynne** [comment]
This got left open
