### ISSUE TITLE
Removing Saved Stream in Rhino is not working properly

### ISSUE THREAD

**Issue by carluxlopez** [specklesystems/speckle-sharp#2099]
Happening on an M1 Mac 👇🏼

1. Hitting Remove icon
2. Click in Remove button in the modal
3. Result: Modal keeps and saved stream is not removed until Cancel button is hit or modal is closed (not sure about the exact pattern)

![rhino](https://user-images.githubusercontent.com/117730949/214792550-0c8e800e-99c9-4b86-aea4-81c0f4f93bd2.gif)

**Comment by AlanRynne** [comment]
Works on an `Intel` mac with 2.11.1 installed
![2023-01-26 09 58 32](https://user-images.githubusercontent.com/2316535/214796333-0350d6f5-002f-4670-8aa9-0955c2f2681d.gif)

**Comment by carluxlopez** [comment]
I think @clairekuang can have more info here
