### ISSUE TITLE
Change Streams.List node to be a dropdown

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#210]
Minor enhancement for GH & Dynamo: change the Streams.List node to be a dropdown.
This would make the user flow of re-using existing streams much quicker than the current one.

Not sure it's feasible in GH, but it sure is in dynamo.

Time estimate ~2-3h

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
