### ISSUE TITLE
Enhancement: Support Material Update for Revit Connector when receiving a commit

### ISSUE THREAD

**Issue by AhmadEltobshy** [specklesystems/speckle-sharp#2109]
### Description
_____________________________________________________________________________________________________________________________
When dealing with Revit connector you can upload the material categories to the speckle server in a commit including material category, when you try to open new file or same document on another device when you receive the commit you just upload to server with materials category, nothing happens. The current materials list in Revit document isn't updated. Also, the data sent in commit is not sufficient to create or update a material with the same properties and assets.  

### Expected Behavior 
______________________________________________________
The expected behavior when receive a commit regarding material to check if the document has this material or not. If it already exists,  then the connector updates this material. otherwise create a new material with the same characteristics. keeping in mind the restriction of Revit API has of creating or editing the material properties

**Comment by teocomi** [comment]
Thanks for the suggestion @AhmadEltobshy ! Is this something you could contribute to?
Otherwise, we'll definitely add it to our backlog cc @paloknapo

**Comment by AhmadEltobshy** [comment]
I will contribute that one, i almost finish and will make a pr soon.
