### ISSUE TITLE
materialQuantities missing on certain Revit Categories

### ISSUE THREAD

**Issue by martinromby** [specklesystems/speckle-sharp#2117]
The `materialQuantities` object is missing on the following Revit Categories:

- Ducts (needs to be specified for the actual duct thickness)
- Duct Insulation
- Flex Ducts
- Flex Pipes
- Pipes
- Railings
- Ramps

**Comment by ks-cph** [comment]
I am looking into this atm. It appears that the method ```Autodesk.Revit.DB.Element.GetMaterialIds()``` malfunctions for these categories. Hence, the quantities are not added. I will further investigate the issue and propose a solution soon after.

**Comment by martinromby** [comment]
Fixed in the 2.17 connector version 
https://github.com/specklesystems/speckle-sharp/releases/tag/2.17.0%2Fall
