### ISSUE TITLE
[ enhancement ] Keep Grasshopper behaviour on Extend Speckle Object

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#213]
Hi!

When extending some SpeckleObjects (organized in a tree/list) adding a new property, the component now requires consistent input of Key and Values: keys must have same data structure then values. If only 1 value for the Key is provided, then only the first object is actually extended.

![image](https://user-images.githubusercontent.com/64929000/106871897-08ff1700-66d3-11eb-941b-6a7b770958ea.png)

This is not reflecting the general Grasshopper behavior, where usually a single value given in input is cross referenced and graphted to match the most complex data structure of the other inputs.

As for the sample provided, assuming that the objects that I want to extend belongs to the same class, I would like to provide the Key of my new class property once and not duplicate the data to match the data structure of my objects.

Open for discussion, ofc! :)

**Comment by didimitrie** [comment]
Piggybacking on this issue with another one i found when debugging a bit the situation here:

![eso-problems](https://user-images.githubusercontent.com/7696515/107340932-41796900-6ab6-11eb-81ea-6eb19108078d.gif)

ESO seems fine, but if you plugin in a list in what used to be an item it breaks, and stays broken...
