### ISSUE TITLE
Bug(Revit): Received room separation lines are associated to the wrong level

### ISSUE THREAD

**Issue by Mehdi-Lucas** [specklesystems/speckle-sharp#2131]
## Prerequisites
- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Revit connector

## Describe the bug

Received room seperation lines will be affected to the active plan view. They may appear to be in the correct 3d position but only because they are offseted on the Z, if we look at their level param it is wrong as we can see on this send/receive gif exemple:
![boundaryLinesLevelBug](https://user-images.githubusercontent.com/71726210/217857912-2b542f0d-4461-45a0-86ae-52f610f58a8e.gif)

## To Reproduce

1. Create a room separation line on level 1
2. Send to Speckle
3. Delete the room separation line in Revit
4. Switch the view to the level 0 plan
5. Receive the room separation line
6. Check it's level id, it will be affected to level 0 instead of level 1

## Expected behavior

Room separation line affected to the correct level, I have a WIP solution, here is a gif showing how the receiving should logically behave:
![boundaryLinesLevelFix](https://user-images.githubusercontent.com/71726210/217859685-30d79c09-9e63-4530-a188-5904d9639354.gif)

## Additional context

There is another open issue https://github.com/specklesystems/speckle-sharp/issues/1193 that IMO is different but has some important overlap with this issue.
The solution I'm proposing here fix partially the other issue as it allows line creation from the 3d view (as seen in the gif of the expected behaviour). However, there is still some change to be done to fully fix the other issue. notably the case where there is no view plan in the doc the line creation will fail. I'll try to tackle https://github.com/specklesystems/speckle-sharp/issues/1193 after this one.

Just to nuance a bit what was said in the other issue: 
[The problem here is that Room Separation Lines (the correct name for them in Revit) cannot be created if the active view is anything other than a plan. 
I think we missed this detail! And thanks Autodesk 😣](https://github.com/specklesystems/speckle-sharp/issues/1193#issuecomment-1095479307)

The real problem was that in Speckle we always passed the ActiveView to the creation method and that's why it failed when it was a 3d view. see code: 
https://github.com/specklesystems/speckle-sharp/blob/56a572ec03c425a5a2dfda9cfe457c771bc20230/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertCurves.cs#L155
If we pass another plan view to the method, the lines will be created even if the ActiveView is a 3d view. (see expected behavior gif)

## Proposed Solution (if any)

I'm proposing and actually working on this solution:
1. Add the level info when sending the room separation line
2. When receiving the line back check if it has a level info:
   * true: try to create the room separation line on that level
   * false: use the activeView instead (actual behaviour)

If this is clear enough and my logic is ok with the team, I'll finish the WIP and open a new PR to fix this issue.

**Comment by teocomi** [comment]
Thanks for spotting this! Your proposed solution sounds great, looking forward to the PR then 🙏

**Comment by Mehdi-Lucas** [comment]
this can be closed, fixed by https://github.com/specklesystems/speckle-sharp/pull/2177

**Comment by AlanRynne** [comment]
Awesome :D thx!
