### ISSUE TITLE
Use locking mechanism to prevent AccountManager form starting multiple flows simultaneaously

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2142]
Currently, if multiple apps are using the AccountManager class to add an account at the same time an error will be thrown about the port being used.

We should instead be able to differentiate if the port is used by a separate process and/or a Speckle one. A solution is to use a lock file/flag (ideally in the SQL transport) so that it can be checked cross-app and we can give a meaningful error message to the user.

Eg
If the lock exists and still valid -> Complete the account add in the app you started it in / or close all other apps or something / if it crashed pls wait until the timeout.
If the lock is not valid any more -> Please close all stuck instances of revit manager rhino whatever
If no lock and port taken -> Please close the app, that is not a Speckle app, that is running on port 27... whatever

**Comment by AlanRynne** [comment]
This can be closed now :D
