### ISSUE TITLE
CI: Speed up our pipeline as much as possible

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2143]
As our pipeline has grown, we've introduced several bottlenecks that may need to be revised:

- [x] We're overusing checkout, it's called on every job. Look into a caching strategy for our repo files. This step can take up to 1min sometimes, but usually goes for 8-30seconds.
- [x] Using Mac/Windows images instead of linux ones provides no benefit in our `Core` `Objects` and `DUI` builds.
- [ ] Connector Mac builds have 2 clearly different steps (zip the connector and build the installer). These use mono and dotnet respectively, and would be wiser (and faster) to split these into 2. This would allow us to remove the setup steps that take around 8min and use docker images instead.

**Comment by teocomi** [comment]
I know it's out of scope, but if touching the CI, we could also add a final step for the discord notification 😉

**Comment by AlanRynne** [comment]
Closing this for now as we've already achieved all the objectives (at least as much as it makes sense right now)
