### ISSUE TITLE
[ enhancement ] Data conversion failed from Goo to Speckle

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#216]
Hi again!
I have another one, then I stop it for today, promise!

![image](https://user-images.githubusercontent.com/64929000/106922643-8ba4c800-670d-11eb-9e19-db3a3683d953.png)

`c#` and `python` script components always wrap their output as `Goo` ghp class. Currently some speckle components require pure `Speckle` objects as input parameters. This makes impossible to mix the use of ghp components and scripting inside ghp.

**Comment by AlanRynne** [comment]
Fixed! Should be merged in imminently.... Thanks for pointing it out @iltabe, there was a missing case in the `CastFrom` methods of our `GH_Goo` custom classes.
