### ISSUE TITLE
Add send and receive performance metrics reporting

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#2160]
With the new Serilog based logger we can start reporting the performance of send and receive operations.
Make sure to log:
- streamId
- root object id
- server url

**Comment by AlanRynne** [comment]
We already have **some** level of performance metrics added to our Send/Receive operations, but it's not perfect.

Also, we recently added `Serilog.Timings` to time processes in Archicad. This could be expanded further into every part of Speckle

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
