### ISSUE TITLE
bug(revit): updating analyticalMembers location may change the location of connected members

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#2164]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Revit Connector

## Describe the bug

In revit when an analytical member is dragged, it will also drag the end of any analytical members that are connected to it. In the two screenshots below you can see that the first one is the original state of the building. The second one is after a version from ETABS was received (however the geometry was UNCHANGED). The problem is that during the receive operation, the column baselines were set vertically, and then the crossbeam (highlighted in the images) that connects the tops of the columns had its baseline set with it's endpoints flipped. This normally would not be an issue except that it dragged the tops of the columns with it even though they had already been set and were not supposed to move.

![image](https://user-images.githubusercontent.com/43247197/219792521-0d1d7dc6-96bb-4101-9ea0-8db2842abacb.png)

![image](https://user-images.githubusercontent.com/43247197/219792471-2a0a1d10-0bee-421c-8bd2-49079f0dce99.png)

## Expected behavior

The geometry should be unchanged since it was not changed in ETABS and the data that was sent to Speckle shows the same geometry as the original geometry in Revit.

## System Info

If applicable, please fill in the below details - they help a lot!

**Comment by AlanRynne** [comment]
Closing!
