### ISSUE TITLE
feat(core): optimize ApplicationObject storage for improved performance

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#2178]
When profiling the rhino connector, we discovered that storing `List<ApplicationObject>` and retrieving specific objects (which happens on every log and update event) is performance costly and could be improved significantly by storing them as a `Dictionary<string, ApplicationObject>` instead.

This would require a change to the bindings for DUI2 and effect every DUI2 connector that uses `ApplicationObject`, which is wide in scope but straightforward in implementation.

**Comment by teocomi** [comment]
Closing has this has been tackled in https://github.com/specklesystems/speckle-sharp/pull/2454
