### ISSUE TITLE
Enhance Rhino -> Revit schema workflow

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#221]
- [x] Split command into AddSpeckleSchema and RemoveSpeckleSchema
- [x] Add supported schemas to the Add command options ("Automatic" option preserves current assumption hierarchy)
- [x] Add selection geo filter for all type options
- [x] Add "DirectShape" option for meshes and breps, with additional schema specification afterwards (SpeckleSchema: DirectShape: Type)

**Comment by teocomi** [comment]
More context: https://www.notion.so/speckle/Rhino-Revit-PUBLIC-254be7b8fabd4da0891761a8223d379d
