### ISSUE TITLE
Cant parse version of the server

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#2222]
https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-47138cf51af408dbf150f40d00000000%27&showExpanded&permalinkId=permalink-262

**Comment by teocomi** [comment]
Can't see the link above, is this still an issue?



![Image](https://github.com/specklesystems/speckle-sharp/assets/2679513/9d9294b4-0a37-4f4c-8481-97507fd5fe79)

**Comment by AlanRynne** [comment]
Closing as stale, we can reopen if it pops its head again in one of the Error reporting meetings.
