### ISSUE TITLE
Could not fetch invites in Revit

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#2230]
This error message is one of the most common reported [error in seq](https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-9a0c77c51bc508db48a6970e00000000%27&showExpanded&permalinkId=permalink-267)

it can happen quite often ~ 350 times in a [4 hour window.](https://seq.speckle.systems/#/events?signal=signal-m33301&q=select%20count(*)%20from%20stream%20where%20@EventType%20%3D%200x9270231C%20group%20by%20time(4h)&from=2023-02-26T23:00:00.000Z&view=timeseries)

A [breakdown of the different inner exception types](https://seq.speckle.systems/#/events?signal=signal-m33301&from=2023-02-26T23:00:00.000Z&q=select%20count(*)%20from%20stream%20where%20@EventType%20%3D%200x9270231C%20group%20by%20ExceptionDetail.InnerException.Type)
![image](https://user-images.githubusercontent.com/57442769/222680977-27cea235-5191-428d-88af-e24cf21e70ed.png)

Most of the events are comming from an argument exception like [this](https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-812ee33e1bc608db8eb0980e00000000%27&showExpanded&permalinkId=permalink-268)
This error type should be fixed by #2222 

These should be looked at: how and [why are we getting forbidden](https://seq.speckle.systems/#/events?signal=signal-m33301&from=2023-02-26T23:00:00.000Z&view=timeseries&filter=@EventType%20%3D%200x9270231C%20and%20ExceptionDetail.InnerException.Type%20%3D%20'GraphQL.Client.Http.GraphQLHttpRequestException')?

**Comment by teocomi** [comment]
This was a bug on the server that's been fixed recently.
