### ISSUE TITLE
Uniform triangulation libraries

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2242]
We currently have 2 triangulation libraries:

- TriangulationHelper https://github.com/specklesystems/speckle-sharp/blob/64b1b41a6babf565c7cbe2ee603714c20d689a4a/Objects/Objects/Utils/MeshTriangulationHelper.cs#L11
- Triangles.NET

We should probably standardize on the latter and if needed move it to its own nuget.

**Comment by AlanRynne** [comment]
@JR-Morgan had a different view on this, as it seems the libraries perform different operations in our ecosystem there may be a place for all.

I'm closing this for now.
