### ISSUE TITLE
Our logging effort clashes with RhinoCompute

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#2258]
Rhino compute [uses](https://github.com/search?q=repo%3Amcneel%2Fcompute.rhino3d%20serilog&type=code) `Serilog` too as their logging platform.

If a user has the `Rhino / Grasshopper Connector` installed and runs Rhino Compute on that machine, our current logs are merged with their logs resulting in:
* us potentially overriding version info in their log
* us leaking the hashed userId to their log
* rhino compute errors making their way into our logging systems

The fix for this is to not use the Serilog global static logger, but to store our own instantiated logger in our own static property.
This is mostly a brainless refactor, but it has to happen across all connectors for consistency.

**Comment by gjedlicska** [comment]
hey @JR-Morgan can i drop this ball on you? The core part is done in #2313, we need to make sure connectors use the `SpeckleLog.Logger` global static instance instead of the `Serilog.Log` convenience methods, to avoid hijacking other plugin devs logs.

Once we're done with the refactor in sharp and manager, we need to remove this [line](https://github.com/specklesystems/speckle-sharp/pull/2313/files#diff-e8ffa496d274af4e06de148c7c03c4dd580f54508d47c7438a1b833d74de0571R105)

**Comment by JR-Morgan** [comment]
Cool! on it

**Comment by teocomi** [comment]
Closing as temporarily fixed.
Related to https://github.com/specklesystems/speckle-sharp/issues/2477
