### ISSUE TITLE
Bug GH: inform user when wrong account is used to send / receive

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#226]
When a user tries to send / receive to a stream they don't have access to we should inform them.
Currently the following happens in GH, dynamo seems to be already returning better messages.

**Sending to a stream with link sharing on, but without write access:** no error is shown, but conversion halts.
![image](https://user-images.githubusercontent.com/2679513/107556127-ef2c6b00-6bcf-11eb-862b-581cd9eb713d.png)
![image](https://user-images.githubusercontent.com/2679513/107557280-4ed74600-6bd1-11eb-91c1-dd3df846542c.png)

**Sending to a private stream, without access:** an error is shown but it's not clear
![image](https://user-images.githubusercontent.com/2679513/107556231-0f5c2a00-6bd0-11eb-9c39-ae808588efe9.png)
![image](https://user-images.githubusercontent.com/2679513/107557213-37985880-6bd1-11eb-934e-144767f25505.png)

**Receiving from a private stream, without access:** an error is shown but it's not clear
![image](https://user-images.githubusercontent.com/2679513/107556316-2dc22580-6bd0-11eb-957c-0baabe4bf0aa.png)
![image](https://user-images.githubusercontent.com/2679513/107556866-d1abd100-6bd0-11eb-9d11-b9adb87faa09.png)

**Comment by AlanRynne** [comment]
I tagged the issue incorrectly so it didn't automatically close on PR merge. Closing now!
