### ISSUE TITLE
Modify Base prop validation method to align with speckle-py

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#227]
After a quick conversation with @izzylys about https://github.com/specklesystems/speckle-py/pull/55, we have decided to go forward with the proposed modification in c# too to keep both implementations aligned.

Current:

https://github.com/specklesystems/speckle-sharp/blob/59fccad07fde2af3fe039bd221045f9368483984/Core/Core/Models/DynamicBase.cs#L59

The `IsPropNameValid` method returns a boolean value and has an extra `out` property that returns the "reason" for not being valid.

Proposed:

Change it to return `void` and, if not valid, should throw an Exception containing the reason/reasons for failure.

```c#
public void IsPropNameValid(string name) {...}
```

**Comment by didimitrie** [comment]
Not sure why .net should follow python. Closing for now; feel free to reopen if I'm stupid
