### ISSUE TITLE
enhancement(Navisworks): Improve Tree Building handoff and Conversion Loop

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2272]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

SpeckleNavisworks

## Is your feature request related to a problem? Please describe.

Because of the incremental development leading to the alpha release, similar problems were solved multiple times. Some parts of the CanConvert process are repeated 2/3 times
1. Converting Selections to the ultimate number of nodes to convert
2. In the Connector/Conversion loop
3. Validating the converted objects

## Describe the solution you'd like

Having adopted the Collections class, added more Geometry Primitives and handled the fallbacks for those not yet supported, there are now fewer unknowns in the CanConvert loop and the Object conversion in general. Simplifying the logic of "keeping score" will increase speed, improve UX with progress reporting and accurately record the total object count.

## Describe alternatives you've considered

I considered picking up a previous attempt at converting all child nodes in a flat list and reconstructing the tree once all are converted. The current solution has the keeping track of pointers already baked in, but the logic of Deep First feels worth keeping. 

Part of the solution should be to stop applying both approaches in one.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
