### ISSUE TITLE
[ Bug ] Grasshopper Stream receiver component doesn't update after the input change

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#229]
1. Place a receiver
2. Connect a stream to the receiver input
3. Receive data. It works!
4. Connect a different stream (maybe just a different branch) to the same receiver component
5. Receive data. Broken! (or data from the old stream/branch is returned)

![image](https://user-images.githubusercontent.com/64929000/107645239-c1e7c780-6c78-11eb-8c97-37ed1e3fe300.png)
The receiver component at the bottom is a fresh one.

**Comment by didimitrie** [comment]
Thanks for reporting! I can reproduce the bug. We'll look into it.
