### ISSUE TITLE
RevitConnector: Pipe Fitting Not Show

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#2294]
## Prerequisites

Install Revit 2023 

## Describe the bug

When we send a network, pipe fitting not show.

## To Reproduce

1. Go to Revit Open Speckle Connector
2. Click On Send With Selection Pipe Network
3. Open Web Viewer
[Project1.zip](https://github.com/specklesystems/speckle-sharp/files/10985526/Project1.zip)

## Screenshots

![image](https://user-images.githubusercontent.com/31106432/225476043-f55416e0-910c-4571-9067-64129466e321.png)
![image](https://user-images.githubusercontent.com/31106432/225476249-ec5fc8a5-a3e4-4932-b4a0-ac8740ffb3db.png)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS:  Windows 10
- Browser  : Firefox
- Version 2.13

**Comment by teocomi** [comment]
Possibly related to https://github.com/specklesystems/speckle-sharp/issues/1436
