### ISSUE TITLE
🧹 Monorepo Cleanup

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2296]
> This is a long development ticket to be split in the future. This is just a conversation starter around what "needs to be done"

We've been collecting some dust on our Monorepo that is quite normal on a project this size, but it's time to give it a quick (or not so quick...) polish!

> Please edit this list and add any items that need to be discussed

**Things that can be done immediately**:
- [x] Have a single .editorconfig on the monorepo root
- [x] Use Directory.Build.props (and .targets) to share common properties across projects (Company, copyright, copy to objects folder after build...)
- [x] Make `All.sln` the **only** solution in the repo, use `solution filters instead` to select specific parts of the solution. This allows for the build configurations to be stored in a single solution, making editing faster. A single solution also makes it impossible to have projects missing in one solution or another.
- [x] Enable Style and Code Quality analyzers
- [x] Choose a language version to apply by default.

**Things that require each team member's involvement:**
- [ ] Uniform target frameworks (when available) or at least minimise the amount of versions we use.
- [x] Upgrade all our projects to SDK style (there's a migration tool that works great). This will allow us to remove `MSBuild.AssemblyVersion`, enabling the whole solution to build with `dotnet build`. Would speed up CI and reduce credit cost by allowing us to build on linux.
       > This may or may not be fully feasible. Must be checked per project

**Potentially disruptive actions:**
- [ ] Do a solution-wide reformat to ensure all code complies with .editorconfig in root. THIS SHOULD BE DONE PER CONNECTOR, 1 AT A TIME, to allow each owner to choose when is the best moment to do this.

**Things that need discussing, but are not blockers:**
- [ ] Use Central Package Management and lock files (this + CircleCI caching should speed up restoring time considerably) https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management
- [x] Style and analyzer rules (we'll start with "recommended" set but we'll disable some)
- [x] Code Style formatting (https://csharpier.com or other?)
- [ ] Coreowners (potential for more specific entries in the `CODEOWNERS` file. @JR-Morgan mentioned a few places in core where he'd like to be pinged for changes. And I'm sure there are parts of Core/Objects that some people would like the opportunity to give feedback on changes)

Some of this changes **will imply a change in our CI** to some degree. In theory we could replace our calls to a `sln` file to a `slnf`(solution filter) and it should just work as normal, but it remains to be tested.

**Comment by gjedlicska** [comment]
migrate all possible projects to:
- `netstandard`
- `net7` (ie tests and consoles)
- or the latest `netframework` possible supported by the host app

**Comment by AlanRynne** [comment]
Added suggestion to use Central Package Management + Lock files

**Comment by AlanRynne** [comment]
Closing this as the vast majority of the work has been done. I'll open separate tickets for what's left
