### ISSUE TITLE
feature(revit): Regression of curtain grids on roofs

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2302]
Roofs with curtain grids don't correctly convert to Speckle.

Since adding support for Revit instances, the `RoofToSpeckle` does not correctly use the roof footprint of each instance.

Previous behaviour: (Visually correct)
https://latest.speckle.dev/streams/7d051a6449/commits/03d53878ee?filter=%7B%7D&c=%5B19.85991,-1.02284,7.88778,6.41016,12.92177,-3.47544,0,1%5D

2.13 Behaviour: (family definitions are the same, despite footprint being different)
https://latest.speckle.dev/streams/c1faab5c62/commits/46a2ada8e3?filter=%7B%7D&c=%5B19.85991,-1.02284,7.88778,6.41016,12.92177,-3.47544,0,1%5D

Note that `WallToSpeckle` has a check for curtain grids, Perhaps something similar is needed for roofs.

---
Revit file on Google drive

**Comment by clairekuang** [comment]
Thanks for investigating this, will get around to it on mon ~
