### ISSUE TITLE
Enhancement : RevitConnector : transfer Revit Builtin categories (OST_xx)

### ISSUE THREAD

**Issue by thoffeller** [specklesystems/speckle-sharp#2319]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Revit Connector

## Is your feature request related to a problem? Please describe.

Yes, since we're depending with leaDE on classifications and Revit has nothing to offer but builtin categories this is more a bug than a feature

## Describe the solution you'd like

Currently, when pushing from Revit to speckle, the display name for the builtin cat is transfered. Since this is related to the language you start Revit with, it is not a relyable classification. Translations may change during Revit versions and we have to provide mappings for all supported languages of Revit for all Revit versions (2023. 22. 21. 20, ...)
Additionally to the translated Revit category I'd like to add a new parameter to the transfered parameters called BuiltInCategory and value is OST_Walls for example.

## Describe alternatives you've considered

There is no alternative ;-)

## Additional context

nothing to add, so far

## Related issues or community discussions

Found nothing

**Comment by teocomi** [comment]
Hey @thoffeller we were just discussing the same issue recently, yes please go ahead!
Note that there are a few different places where we set the `element.category` property, but a quick search should yield all cases.

**Comment by thoffeller** [comment]
Hi @teocomi , shall I replace the current approach and override it or do we add another category? I haven't checked other connectors, is there a similar approach? This would be realy useful, because we do mappings to elements based on their classification.

**Comment by teocomi** [comment]
Please just add a new `builtInCategory` property, other connectors don't have this problem as far as I know :)
