### ISSUE TITLE
Bug (DUI): Category selection adds invalid/'null' category to selection

### ISSUE THREAD

**Issue by dtnaughton** [specklesystems/speckle-sharp#2326]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

DUI2

## Describe the bug

Bug discovered while using connector in Revit. When adding an additional category to a saved stream that originally sent data by categories, an additional 'null'/blank category gets added to the selection. See screenshot.

## To Reproduce

1. Select send by category and select some categories.
2. Send data
3. Access same stream in ‘Saved Streams’ and add a new category to previous selection

This seems to insert a null/empty category between existing and new

## Expected behavior

Should not add this blank/null.

## Screenshots

![image](https://user-images.githubusercontent.com/77862637/227206157-4dd79d46-73b6-4414-a5f1-eecc077f81d8.png)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: Windows
- Version: Speckle 2.13.0-beta3

**Comment by teocomi** [comment]
Thanks for testing on the bleeding edge and reporting back :)
