### ISSUE TITLE
Brep Conversion Failiure

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#233]
Swooshing in to report: 

![image](https://user-images.githubusercontent.com/7696515/107806071-33e60c80-6d5e-11eb-9f13-40f0a9ae3aa3.png)

From @izzylys's race car stream, [see here](https://staging.speckle.dev/streams/d631b3eecc/objects/d298e02ff85f932c7cc22b9c8a160411).

**Comment by AlanRynne** [comment]
Got it! Seems like we need to add some option to the unit converter to prevent some of the "non-unit" geometries in the BREP to stay with their values intact. Mainly the 2D curves.
