### ISSUE TITLE
Module Add-in Loaded All with Another Module Add-In Assembly

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#2334]
- [ ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [ ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

When I try Debug for Revit software, I know the team need design again folder(sub folder) to load event for addin, because if we keep same kit folder, it will be load all kit not relate like : 

- Revit Load Another Assembly => Autocad, Navisworks, ....
- Navisworks Load another Assembly => Revit, Autocad ,...

![image](https://user-images.githubusercontent.com/31106432/227555771-155ff3eb-564d-41e9-b6e7-2cea649b3aac.png)

## To Reproduce

Just try debug and see debug output load assembly.

## Expected behavior

It doesn't load another module assembly from another add-in with another software

## System Info

If applicable, please fill in the below details - they help a lot!

#### Optional: Affected Projects

[log.txt](https://github.com/specklesystems/speckle-sharp/files/11063457/log.txt)

**Comment by AlanRynne** [comment]
Hi @chuongmep

For what I gather this is the expected behaviour. The Kit folder will contain all the dlls for each converter + the object model. In order for our `KitManager` to find the correct converter for a given application, it needs to try and load each dll separately and  then return the one that is supported by a given app.

Closing this for now, but feel free to open if I misunderstood anything ;)
