### ISSUE TITLE
Bug When Send MEP Element

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#2337]
## Prerequisites

- [ ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

bug when we send some MEP element 

https://speckle.xyz/streams/0786379ee6/commits/b22b79a6f3

## To Reproduce

1. Go to Revit and open project
2. Click on Send All
3. Open Web Viewer
[MEPBug_Exhaust_Damper.zip](https://github.com/specklesystems/speckle-sharp/files/11073602/MEPBug_Exhaust_Damper.zip)

## Screenshots

![ảnh](https://user-images.githubusercontent.com/31106432/227816620-43430073-b488-4c89-b25f-08d733b02b50.png)
![ảnh](https://user-images.githubusercontent.com/31106432/227816629-b8ea1934-936f-4e07-9d28-0b4c2219308e.png)

## System Info

If applicable, please fill in the below details - they help a lot!

**Comment by teocomi** [comment]
Hey @chuongmep can you please confirm what version of the Revit plugin were you using and if this is resolved in in the latest beta?

**Comment by chuongmep** [comment]
Hi @teocomi, I tried with latest in dev branch.

**Comment by connorivy** [comment]
This was an instancing issue that is fixed as of 2.15
