### ISSUE TITLE
bug(Archicad): Objects' class reusage on multiple interfaces

### ISSUE THREAD

**Issue by jozseflkiss** [specklesystems/speckle-sharp#2342]
Archicad classes from the `Objects` kit are used on:
1. the interface between the connector (C#) and the server
2. the interface between Archicad add-on (C++) and the connector (C#)

Despite 90% of the fields are common for both interfaces there are some differences:
* optionality:
  * for 1. interface a field is optional when it is optional in the Archicad API
  * for 2. inteface almost all the fields are optionals (except `id`, `applicationId`, etc) 
* type differences
  * for 1. interface we use `displayValue` with `Mesh`-es
  * for 2. interface we have Archicad `MeshModel`

The problem which can lead to crashes:
During a send operation a field of e.g. `ArchicadWall` is optional if it is optional in Archicad API.
In a receive operation if a Speckle `Wall` is received, a temporary `ArchicadWall` instance is created to transfer the data to the host application. But in this case most of the fields are not set, so - if they are not optional in the first case - a default value (usually zeros, empty strings etc) are sent to Archicad. This cause problems, because the default elem became invalid with those zeros and default values.

Repro: receive this stream with parametric import: https://speckle.xyz/streams/9ff64f51e6/commits/5118357ddc

![Image](https://user-images.githubusercontent.com/50739844/227972177-abc61108-ae0a-40dd-b5dd-a0925722fd5a.png)

**Comment by jozseflkiss** [comment]
#2736 is a temporary solution for this.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
