### ISSUE TITLE
bug(Archicad): Parametric receive differences

### ISSUE THREAD

**Issue by jozseflkiss** [specklesystems/speckle-sharp#2351]
There are some differences between the sent and received (as parametric) models in Archicad. E.g.
- wall junctions with roofs
- door/windows not imported in case of missing library parts

![Image](https://user-images.githubusercontent.com/50739844/228243424-edb3f7c5-7f88-40fb-a22f-687c473ba64b.png)

Test model: https://latest.speckle.dev/streams/d10c6bff11/commits/0cc8f0a86d

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
