### ISSUE TITLE
bug(navisworks): Long sends are cancelled.

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2360]
## Describe the bug

Large commits sometimes fail with the current infrastructure. This may be resolved in work with Core and Server, but in the meantime, an expectation that a large selection, once processed and converted, succeeds should be met.

Experimentation around repeating the same commit multiple times, eventually succeeding, suggests a retry on that specific error should be possible - with a maximum number of retries as a failsafe. This requires the converted objects to be held in memory. A UI could notify the number of attempts if subsequent attempts are triggered.

## Alternatives considered

The issue could be helped with an as-yet unscoped possibility of caching the converted objects. There is no good way to do this as a constant conversion, as many things may change for an object between commits (overrides, hidden status etc.). Still, the specific selection could temporarily be hash identified and a disk cache of the conversion held for multiple sends.

**Comment by jsdbroughton** [comment]
The null case on sending attempt with the WebSocket cancelled propagates to the `Operations.Send` as a `Cancellation` rather than the `null` result.

There isn't a good way to retry send on that premise as there may be other legitimate reasons a Cancellation exists.

I'm open to ideas @JR-Morgan @gjedlicska

**Comment by jsdbroughton** [comment]
![image](https://github.com/specklesystems/speckle-sharp/assets/760691/fd12285b-d9e5-4408-9f5d-4f884a44c656)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
