### ISSUE TITLE
bug(navisworks): Host application crashes caused by a closed/disposed websocket 

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2361]
This issue arose inside the GraphQL inside DUI.

<img width="691" alt="Screenshot 2023-03-29 112926" src="https://user-images.githubusercontent.com/760691/228809109-903807a4-9011-4784-82ec-9f815181b410.png">

It affects Revit also.

Manifests on UI interactions with DUI and application close.

## Proposed Fix

In the first instance, handle the Exception in the Connector so as not to propagate to the host application.

Ideally, not swallow this error if in handling it, a remedy is needed.

**Comment by teocomi** [comment]
Yes, I think we should def tackle it before DUI3. In Revit I noticed that this bit prevents an exception that was being thrown when closing the app: https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Events.cs#L74-L81

But ideally, we'd come up with a better fix in Core or DUI directly.

**Comment by AlanRynne** [comment]
closing after connectors review in favor of #2574
