### ISSUE TITLE
feat(rhino): Add planar curve to beam conversion in Mapping tool

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2379]
Add conversion for Planar Curves to Beams in the Mapping tool.

**Comment by paloknapo** [comment]
Mapping not available for planar curves 


![Image](https://user-images.githubusercontent.com/760452/231388550-eabdc76a-6109-48db-8651-b46b66f7029e.png)


Test file:
https://drive.google.com/file/d/1aaoLaKgRYCIDOAbK9hwqR4ll_BEgx2hw/view?usp=sharing

**Comment by AlanRynne** [comment]
Just double-checked this with pavol's file and it works on my end

![image](https://user-images.githubusercontent.com/2316535/232716397-59519536-3ae5-43db-88c2-0e2f878e6951.png)
