### ISSUE TITLE
Transport Cleanup

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2392]
I would quite like to clean up some problems in `Operations.Receive`, `Operations.Send`, and our `Transports`

Problems I'm facing:

### 1 Exception handling in Transports is done poorly:
Transports are not consistent in the way they communicate **Non-recoverable errors**

In some cases, **exceptions are being thrown**, other times exceptions are caught and passed to `OnErrorAction`.
[for example](https://github.com/specklesystems/speckle-sharp/blob/0ad7ff3f2211f6d54a15ff49eb80d2575b0cce87/Core/Core/Transports/SQLite.cs#L81-L108)

This has several problems
- This leads to inconsistent error handling, and, since `OnErrorAction` is optional, important exceptions are being swallowed.
- Using `OnErrorAction` for non-recoverable exceptions is bad, as important stack trace info is lossed, and if `OnErrorAction` is null, failures are completely silent.

    
Additionally, Transports are not disposed by Operations.Receive (EVEN WITH `disposeTransports = true`!!!!) if an exception is thrown anywhere that prevents Receive from returning.
         
### 2 Cancellation in Transports is done poorly:

Frequent `null` returns on cancellation make handling cancellation impossible!

Returning null everywhere just leads to random other bits of code exploding `NullReferenceException`s!
`ThrowIfCancelationIsRequested` should be used in most cases instead.

### 3 Continuation in many parts of Core is incorrect, and leads to deadlocks.

`ConfigureAwait(true)` is the default behaviour for awaiting async calls, and will attempt to marshal back to the calling thread once complete. This is "feature" is designed for UI async calls, where you need to sync back to a UI thread.
`ConfigureAwait(false)` allows worker threads to continue execution between async calls. 
This is the "recommend" way to do async in Library code, where you don't need to sync to a main or UI thread.

For most (maybe all) parts of `Core`, we want to use `ConfigureAwait(false)`, and we are not!

1. This leads to deadlocks, e.g. if the treadpool gets exhausted, or a custom Synchronisation context is used, or the awaited thread is waiting to continue on a blocked thread.
    -  This is a major blocker for Unity Connector and leads to frequent deadlocks!
1. There's also performance overhead to using `ConfigureAwait(true)`, and it's totally unnecessary, since we don't care about our Receive operations running on an applications `Main` or `UI` thread.

### 4. `Operations.Send` and `Operations.Receive` are unreadable

These are core functions for community developers using Speckle, I think it's important that they are clean and easily readable.
In the last couple releases, we've made these functions a little messier, and they still encode the v1 deserialzier/serializer logic in a way that clutters these functions (and makes the nullabilty syntax suck!)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
