### ISSUE TITLE
Archicad: Implement new Collection support

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2396]
- [x] Ensure we can receive commits with new collection structure
- [x] Ensure backwards compatibility (We can receive older commits with non-collection structure)
- [x] Send `Collection` structure from ArchiCAD?

see https://github.com/specklesystems/speckle-sharp/issues/2187

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
