### ISSUE TITLE
Rhino: Cleanup deprecated layer structure in Connectors

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2397]
After implementing collections (see https://github.com/specklesystems/speckle-sharp/issues/2187)
The Rhino, and likely other connectors too, have quite large sections of code designed to maintain backwards compatibility with receiving older commits with the Old behaviour for generating layers.

After a few (we should decide on a number!) release cycles, we should consider cleaning up the mess left over from this deprecated code.
Otherwise, this is techdept that will pile up and haunt us 👻 

In general, we need a strategy for how to handle backwards compatibility, most notably, How we communicate this to users

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
