### ISSUE TITLE
Consolidate our build artifacts into a global `dist` folder

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2409]
# Current situation

Our build artifacts for each connector and converter are built into it's `bin` folder (default c# behaviour), but the exact location of the files is always a bit of a mistery, the folder structure inside the `bin` folder will differ depending on its _target framework_, _runtime identifier_, _build configuration_, etc... so that a Rhino6 connector could be in `bin/Release/net462/win-x64/DLL FILES`. This folders would also be deeply nested into our monorepo structure.

# Proposed solution

I propose creating a new target in our projects similar to our `CopyToKitFolder` behaviour, that instead would copy all build artifacts (converters, connectors...) into a global `dist` folder with a predictable structure.

The result would look something like this:

![image](https://user-images.githubusercontent.com/2316535/230963869-6fb0ebb3-005c-4878-a090-88e749d10931.png)

This will bring several benefits:
- Dist could act as a "single source of truth" for the installers. Removing the need of checking multiple deeply nested folders to check for undesired dlls, verify versions, etc.
- This would also simplify the installer files, making the files more readable (i.e. all required kit files for a connector would end up in `dist/{SLUG}/kit/`, simplifying the path the installer uses, and removing the entry for each converter version dll.
- Ability to build and cache the result consistently in our CI pipeline in a single path (i.e cache `dist/rhino` instead of caching the bin folders of both Rhino 7 and Rhino 6 projects, as well as the 4 converter projects (Rh6, Rh7, Gh6, Gh7)

With consistent caching, we could also split the installer logic into it's own step on the pipeline, allowing us to build all our connectors on Windows.

## Some preliminary tests

I wrote a quick target to do what we wanted in a "semi-magical" way. Each connector or converter project should define a `SpeckleArtifact` **item**, that defines all the metadata needed for that project to be copied over:

```xml
<ItemGroup>
  <SpeckleArtifact Include="artifact" Slug="rhino" Version="7" Type="connector"/>
</ItemGroup>

```

This should define the slug, version and type of artifact (`connector` or `kit`). Made a test with rhino and revit (resulting in the screenshot above.

Here's the target I used, I'm pretty sure it would still require some tweaking, as projects such as `Dynamo` have a post-build step that does some extra work to gather all required files into a `ConnectorDynamo/dist` folder, and may be other edge-cases I'm unaware of

```xml
<Target Name="SpeckleArtifactToDist">
  <Error Text="SpeckleArtifact.Slug must be set"
    Condition="'%(SpeckleArtifact.Slug)' == ''"/>
  <Error Text="SpeckleArtifact.Version must be set"
    Condition="'%(SpeckleArtifact.Version)' == ''"/>
  <Error Text="SpeckleArtifact.Type must be set to 'connector' or 'kit'"
    Condition="'%(SpeckleArtifact.Type)' != 'connector' And '%(SpeckleArtifact.Type)' != 'kit'"/>

  <PropertyGroup>
    <Destination>$(RepositoryRoot)dist/%(SpeckleArtifact.Slug)/%(SpeckleArtifact.Type)/</Destination>
    <!-- We only copy connector files in a versioned nested folder -->
    <Destination Condition="'%(SpeckleArtifact.Type)' == 'connector'">
      $(Destination)%(SpeckleArtifact.Version)/</Destination>
  </PropertyGroup>

  <ItemGroup>
    <SourceFiles Include="$(OutDir)/**/*" Exclude="$(OutDir)/**/*.deps.json"/>
  </ItemGroup>

  <Message Text="Copying connector %(SpeckleArtifact.Slug)%(SpeckleArtifact.Version): $(Destination)" Importance="high"/>
  <Delete Files="$(RepositoryRoot)dist"/>
  <Copy SourceFiles="@(SourceFiles)" DestinationFolder="$(Destination)/%(RecursiveDir)"/>
</Target>
```

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
