### ISSUE TITLE
DesktopUI: refresh available accounts

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#241]
I believe the accounts are only refreshed at startup, we should provide another way (manual or automatic) to refresh the available ones. This could happen:
- after visiting the settings/profile page
- after clicking a specific refresh button
- after other operations (clicking "add stream", when the main window is activated...)

**Comment by izzylys** [comment]
my vote is for the first two + when you click the account switcher button in the "add stream" dialogue
