### ISSUE TITLE
🧹 Monorepo Cleanup: Phase 2

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2410]
Some items left from our initial cleanup at #2296 plus any other things that may come up meanwhile

- [x] #2407 
- [x]  ~~Uniform target frameworks (when available) or at least minimise the amount of versions we use.~~
- [ ]  Do a solution-wide reformat to ensure all code complies with .editorconfig in root. THIS SHOULD BE DONE PER CONNECTOR, 1 AT A TIME, to allow each owner to choose when is the best moment to do this.
- [x]  ~~Use Central Package Management and lock files (this + CircleCI caching should speed up restoring time considerably)~~ https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management 
- [x] Codeowners (potential for more specific entries in the CODEOWNERS file. @JR-Morgan mentioned a few places in core where he'd like to be pinged for changes. And I'm sure there are parts of Core/Objects that some people would like the opportunity to give feedback on changes)
- [x] ~~Potentially #2409~~ Will be part of the CI rehaul

**Comment by AlanRynne** [comment]
Central package management Isn't really what we need. It could help on some very specific cases, but in general we don't share enough dependencies between all packages to make it worth it.

**Comment by AlanRynne** [comment]
For the "Uniform Target Frameworks" item, the ideal solution would be for each converter to target the same framework as its connector. @JR-Morgan has brought up in the past that, although this currently works, it could be introducing some difficult to track bugs that we're not aware of yet.

Moving from targeting netstandard2.0 to their respective frameworks shouldn't break, as we're already doing so for Rhino7 due to targeting issues when compiling.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
