### ISSUE TITLE
Investigate group support in ETABS

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2428]
To investigate group support in ETABS and other CSI connectors.
See forum thread: https://speckle.community/t/revit-to-etabs-groups/5419/5
Sample model: https://drive.google.com/file/d/1K0CF2vkjH0uMqodeE7HrPS2uU5oZMyzg/view?usp=share_link
Sample stream: https://speckle.xyz/streams/77e450f389

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
