### ISSUE TITLE
GH: Make Base and Stream parameters capable of "internalizing" data

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#243]
This came up in a conversation yesterday with a friend, just writing it up so we can discuss this post-beta release.

Currently, our `GH_Param` implementations of `Base` and `StreamWrapper` have the basic implementation, but it would be cool if users could internalise the data so it would be saved within the file itself.

Should be fairly easy to implement, just have to swap it for `GH_Persistent` param and implement Read/Write methods.

**Comment by didimitrie** [comment]
This entails potentially internalising 100mbs of data. I don't think we want to do that :)
