### ISSUE TITLE
bug(Rhino): User strings on blocks not received

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2445]
## Describe the bug

User strings added to Blocks in Rhino are sent to the server and viewable online. When receiving the Blocks, users report these user-strings are not present in Rhino

## Test cases
Use cases and stream materials in Notion

**Comment by teocomi** [comment]
Also reported here: https://speckle.community/t/connectors-and-base-object-receive/5441/4?u=teocomi
