### ISSUE TITLE
Investigate Setup.Init being overriden in Rhino/Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2465]
It seems that `hostApplication` and other variables set during `Setup.Init` get overridden in Revit/Rhino when/if Dynamo/Grasshopper are started.

This means that logs and metrics belonging to a connector get erroneously tracked as another one.

This issue is to investigate if that's really the case and what could be a solution.

**Comment by teocomi** [comment]
For mixpanel we could pass the host app as an argument instead of using the "global" one.

**Comment by AlanRynne** [comment]
I think the issue currently is not that the Logger "is being overridden" but rather that "you can only have one logger at any given time, whoever initialises the logger first gets it's HostApp set, and the other just rolls with that.

i.e. If you initialise Grasshopper and then initialise Speckle Rhino, all events will be tracked as `Grasshopper` events. 

If you already have streams in the Rhino file, DUI initialises automatically, causing Rhino to be the HostApp.

There are several ways to solve it:

- Make the logger non-global. I.e. Each connector will register their own logger during setup. If no logger is set, no logging is done.
- Assume all Rhino/Grasshopper events are Rhino events, and just attach some extra context metadata for anything coming from GH
- I'd welcome other suggestions too...

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
