### ISSUE TITLE
Curtain Panel Nested Families Issue

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2471]
See forum reports: 
https://speckle.community/t/curtain-wall-panel-with-nested-shared-famillies/5508/2?u=teocomi

Sample file by [M.Tarabishy](https://speckle.community/u/M.Tarabishy) and [Thomas-Lcp](https://speckle.community/u/Thomas-Lcp):
https://drive.google.com/drive/folders/1b_xpPVGTUG4lb3ovLtSXCuJZXC8NZVY6?usp=share_link

Note from Thomas:

> If you want to reproduce my issues then go to “EXPORT IFC” view and select all “MGMF_PMR_Frigorifique” then open Speckle, select a steam, and click to preview to crash your Revit or send to see what happen in online view.

**Comment by ks-cph** [comment]
I describe the cause of the issue in #1938

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
