### ISSUE TITLE
bug(Rhino) Mapped objects from SketchUp not received

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2488]
### To replicate:
1. Open a new Rhino model
2. Receive this commit https://speckle.xyz/streams/9ff64f51e6/commits/3a449dcd88
3. No objects is received
4. Error in the report

![Image](https://user-images.githubusercontent.com/760452/234337425-4a8e56df-737c-4bfa-809a-92a8b8d655d9.png)

### Expected behaviour
Receive this object

![Image](https://user-images.githubusercontent.com/760452/234337758-b5ab7f97-2c54-4f56-9561-c6c4b82cff6a.png)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
