### ISSUE TITLE
Improve use of typed and dynamic detached props

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2509]
Following on [this bug fix](https://github.com/specklesystems/speckle-sharp/issues/2446) and these PRS:

- #2456
- #2507

We want to improve how detached properties are handled in case they are Typed or Detached.
Currently, an object can have both a typed detached `elements` property and as well a dynamically attached `@elements` one, this is of course confusing and leads to issues in the viewer and other parts of Speckle.

@JR-Morgan 's proposal:

> We can solve this by implementing some internal dictionary d`ynamicPropName : string -> shouldDetach : bool`
The `this[]` indexer can sill accept `@` prefixed keys, but this prefix will be stripped from the prop name, and instead used to set this bool. Such that we never serialize the `'@'` prefix, but we do keep backwards compatibility with using the `'@'` prefix

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
