### ISSUE TITLE
UI: add standard layer name format for receiving commits

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#253]
Currently:
 - Rhino format is "{stream.name}: {state.Branch.name} @ {commitId}"
 - Autocad format is "{stream.name}[{state.Branch.name}@{id}]" (: illegal char)
 - dynamic prop illegal chars: ./

Proposed standard format:
 - "{stream.name}[ {state.Branch.name} @ {id} ]"
 - omit emojis and leading spaces

**Comment by didimitrie** [comment]
Really sorry about emojis; but this `"{stream.name}[ {state.Branch.name} @ {id} ]"` looks 👍

**Comment by teocomi** [comment]
I'd also include trailing spaces ( a `.Trim()` should do :) )
