### ISSUE TITLE
Batch Uploader for Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2541]
Revirew of current MVP and planning next steps.

https://github.com/specklesystems/batch-uploader

Spec in Notion:

https://www.notion.so/speckle/Batch-Uploader-for-Revit-fcc99c374eed45b1ae9e5cbf8040bc89

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
