### ISSUE TITLE
Exclude light cones from conversion of light fixtures

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2551]
We should not be sending this geometry which often can be curved and heavy.

![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/96ad7163-4d66-463f-baa8-46d8f5da7c65)
![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/d7410701-f66f-43de-a778-d76c261551f7)

**Comment by JR-Morgan** [comment]
This is a big problem for the Unity connector users who are adding colliders to their imported geometry.
There is no way easy way for us to exclude the lighting cone from physics colliders.
Which makes these cones act as solid walls (and other physics objects can't move through them...)
![image](https://github.com/specklesystems/speckle-sharp/assets/45512892/81707f77-0f27-4d5b-9497-528adf4aaf38)
