### ISSUE TITLE
Improve GH > Rhino workflow

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2579]
Grasshopper data does not get clear/correct layers. Reported by @didimitrie 

Possibly related to: https://github.com/specklesystems/speckle-sharp/issues/2397

Issues: 

- we’re baking in the data path (can be okay, but looks weird - not that critical, but i’d expect a refinement here)
- objects are baked on the default layer, not on the created layers

Tested two cases: 

1) Using the variable inputs of the send component

![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/67f0d054-c3be-4ed3-ac08-e80c238d5cda)

2) Using the CSO component with list access

![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/bc9e47d3-212d-4fce-b48b-f04b732250f6)

**Comment by AlanRynne** [comment]
This is kinda bigger than just GH:

Revit and Navis are baking an empty `Views` layer, and Navis has a similar problem with GH where "too many meaningless layers" are created (i.e. layers with names like `Obj-432` with a single object inside them, see screenshot bellow)

We may want to evaluate how the traversal works and align properly with what is expected.

In the case of Grasshopper, i think it makes sense to "flatten the data tree" (i.e. not bake any of its branches), but we'd have to chat with Jedd on how we can make this a more general solution with the current traversal.

![navis-layers](https://github.com/specklesystems/speckle-sharp/assets/2316535/794481c4-3253-4673-8ea3-723dba37fbda)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
