### ISSUE TITLE
feat(civil3d): add profile to speckle conversions

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#2580]
## What package are you referring to?
 Civil3D connector

## Describe the solution you'd like

Add Profile To Speckle and Profile to Native conversions, taking into consideration:

- [x] sending individual profiles
- [x] sending profiles as part of featurelines and corridors
- [x] re-evaluating the current profile class

## Additional context

Requested by community members (Jacobs civil engineering)

**Comment by teocomi** [comment]
@clairekuang please link the matching PR and close if done :)
