### ISSUE TITLE
Missing Roof/Windows in 2.14 RC

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2594]
We have a report of a potential regression in RC8 regarding roof and window elements not visible in the viewer: https://speckle.community/t/latest-rc-2-14-revit-connector-missing-different-roof-windows/5775

Might be a problem with instancing or with the viewer - maybe it's been already resolved in the latest fixes.

Sample model: https://drive.google.com/file/d/1pg-WaQfxeOYlNlMwItPb_NjiZ1jbdkuT/view?usp=sharing

**Comment by clairekuang** [comment]
Not a blocker for the release, this is a viewer issue on xyz since the windows display fine on latest:
https://latest.speckle.dev/streams/3f895e614f/commits/b33bc31084
