### ISSUE TITLE
Revit cable tray not converting to Speckle MEP

### ISSUE THREAD

**Issue by timglewis** [specklesystems/speckle-sharp#2597]
A cable tray object doesn't convert correctly from Revit.

## Describe the bug

The import via the Revit connector doesn't seem to convert the object correctly.  

The cable tray object in Revit is shown here:

![image](https://github.com/specklesystems/speckle-sharp/assets/13721823/1a8cfca5-5419-48f0-ba19-5495bbbbaa95)

The object in Speckle is shown here:

![image](https://github.com/specklesystems/speckle-sharp/assets/13721823/a3469ba6-57eb-4926-92bc-1a15219b77e6)

I have attached a zip file containing the Revit model here:

[Cable Tray Test.zip](https://github.com/specklesystems/speckle-sharp/files/11538636/Cable.Tray.Test.zip)

## System Info

* Revit 2021. 
* Speckle Manager 2.13.3

**Comment by timglewis** [comment]
We haven't tried previous versions for this element so I can't confirm if it's a regression.

It does appear to be similar to #2337

**Comment by connorivy** [comment]
Hi @timglewis,

Sometimes Revit has multiple display meshes for an object. One (or more) default and then one (or more) view specific. I wonder if the image of the cable tray in the Revit modeling space is a view-specific mesh, and the one in the Speckle viewer is the default mesh. 

Try sending to Speckle using the view filter 

![Image](https://github.com/specklesystems/speckle-sharp/assets/43247197/bf7ee349-11d7-4055-9982-7c0c722b5c17)

this will send the cable tray's mesh as the view specific mesh. I'm not completely sure this is the issue, but give it a shot and let me know if that shows up correctly.

**Comment by katelewis13** [comment]
Hi @connorivy,

I work with @timglewis and have just tested out your suggestion. It looks like upgrading the speckle connector to the latest and specifying the view to select has resolved the issue. 

Looking into this a bit further it seems that when you change the 'Detail Level' in Revit from fine to medium, the simplified mesh is shown, so based on what you're saying it appears speckle exports the Medium detail level by default. Is there a way to specify the level of detail to export in the speckle connector settings, or is exporting a specific view the only solution at this stage?

![image](https://github.com/specklesystems/speckle-sharp/assets/30174604/50f49231-69c2-4863-b198-e735e93e8718)

**Comment by connorivy** [comment]
Hi @katelewis13 

That is good insight. I looked into this and what I found appears to be a bug (or maybe a quirk) with the Revit api. If you look at our [CableTrayToSpeckle method](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertCableTray.cs#L82) you'll see the line where we assign the display value
```
displayValue = GetElementDisplayValue(revitCableTray, SolidDisplayValueOptions)
```
And the [SolidDisplayValueOptions](https://github.com/specklesystems/speckle-sharp/blob/799cdd0e0558fd4fa1da53a01e77e9098f303f35/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertMeshUtils.cs#L13) is defined as
```
public Options SolidDisplayValueOptions = new Options()
    {
      DetailLevel = ViewDetailLevel.Fine,
      ComputeReferences = true
    };
```

As you can see, the Revit api allows you to retrieve meshes with a given detail level, but our detail level is already set to ViewDetailLevel.Fine. I double checked this with the very helpful [RevitLookup](https://github.com/jeremytammik/RevitLookup) tool and I saw the same thing. I guess revit considers this geometry to be view specific and therefore will not give the correct view unless you use view-specific geometry retrieval.

**Comment by connorivy** [comment]
Closing as a revit limitation
