### ISSUE TITLE
Migrate to new version of the Graphql Client nuget 

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-sharp#2598]
Due to some gql subscritpions related issues, we need to migrate to the new 6.0 version of the gql client sooner rather than later. We need to upgrade the server to use a new protocol, that is not supported by the current 5.1 versions.

The migration is a bit more involved, that just bumping a package version, cause we need to do some upgrades around JSON deserialization. The way we're currently using Newtonsoft is not working with the new version.

https://github.com/graphql-dotnet/graphql-client/releases/tag/v6.0.0

**Comment by teocomi** [comment]
Done in: https://github.com/specklesystems/speckle-sharp/pull/2564

**Comment by gjedlicska** [comment]
Sweet. We just need to set it to auto negotiate with the server.

**Comment by teocomi** [comment]
According to the log, it's on by default: The client now negotiates the websocket protocol with the server by default

So for now I had to explicitly set the protocol here: https://github.com/specklesystems/speckle-sharp/blob/b20afb8188391df279108bdfd438b82ec4740e2b/Core/Core/Api/GraphQL/Client.cs#L57

If this change needs to be timed with a server release we need to discuss how not to break older clients...

PS feel free to reopen this if more changes are needed!

**Comment by gjedlicska** [comment]
Yeah, its a bit misleading, cause looking at the implementation, if no values are supplied to the `WebSocketProtocol` it defaults to auto negotiate. But based on this PR: https://github.com/graphql-dotnet/graphql-client/pull/539#issue-1662372496 auto negotiation is not implemented.

So there is not much we can do about this rn... 
Thanks for the help @teocomi
