### ISSUE TITLE
Investigate potential conversion bugs

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2603]
Having looked through seq at `Object failed during conversion` templated bugs (for 2.14 versions)
The following are the most popular conversion exceptions logged.

<html><body>

elementType | (first elementType) | count
-- | -- | --
Autodesk.Revit.DB.Mullion | Autodesk.Revit.DB.Mullion | 5183
Autodesk.Revit.DB.Material | Autodesk.Revit.DB.Material | 4475
Autodesk.Revit.DB.Panel | Autodesk.Revit.DB.Panel | 1953
Autodesk.Revit.DB.CurtainGridLine | Autodesk.Revit.DB.CurtainGridLine | 442
Autodesk.Revit.DB.WallSweep | Autodesk.Revit.DB.WallSweep | 249
Autodesk.Revit.DB.View3D | Autodesk.Revit.DB.View3D | 169
Autodesk.Revit.DB.Area | Autodesk.Revit.DB.Area | 97
Autodesk.Revit.DB.Architecture.StairsRun | Autodesk.Revit.DB.Architecture.StairsRun | 6
Autodesk.Revit.DB.Plumbing.PipingSystem | Autodesk.Revit.DB.Plumbing.PipingSystem | 6
Autodesk.Revit.DB.Structure.PointLoad | Autodesk.Revit.DB.Structure.PointLoad | 2
Autodesk.Revit.DB.Architecture.StairsLanding | Autodesk.Revit.DB.Architecture.StairsLanding | 2
Autodesk.Revit.DB.Group | Autodesk.Revit.DB.Group | 2

</body>
</html>

[query for table](https://seq.speckle.systems/#/events?signal=signal-m33301,signal-39&q=select%20elementType,%20count(*)%20as%20count%20from%20stream%20where%20@EventType%20%3D%20ToEventType('Object%20failed%20during%20conversion')%20and%20productVersion%20like%20'2.14%25'%20group%20by%20elementType%20order%20by%20count%20desc&from=2023-05-21T23:00:00.000Z)

### ToSpeckle

**Converter returned null:**
  - [ ] Curtain Wall Mullions - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-cabd162f5c2a08db128f803e00000000%27&showExpanded&permalinkId=permalink-72
  - [ ] Curtain Panel - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-caaeb6045c2a08db0c8f803e00000000%27&showExpanded&permalinkId=permalink-74
  - [ ] Curtain Wall Grids - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-16a1e7835c2708dbc4c57c3e00000000%27&showExpanded&permalinkId=permalink-75
 - [ ] Views - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-b7e184ba5c1c08db712b713e00000000%27&showExpanded&permalinkId=permalink-76
 - [ ] Wall Sweeps - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-635069cf5aa908db487d1f3d00000000%27&showExpanded&permalinkId=permalink-77
 - [ ] Point Loads - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-e19d56305c1c08db4f6e713e00000000%27&showExpanded&permalinkId=permalink-79
 - [ ] Landings - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-f171f9f25b3908db95c2983d00000000%27&showExpanded&permalinkId=permalink-80
 - [ ] Runs - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-f16d8cf05b3908db93c2983d00000000%27&showExpanded&permalinkId=permalink-81
 
**Null ref:**
- [ ] Areas - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-a20096345c2a08dbfb64803e00000000%27&showExpanded&permalinkId=permalink-73
- [ ] Electrical Circuits - https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-b89aea095bc808db1d67353e00000000%27&showExpanded&permalinkId=permalink-78

Ideally, we should investigate these, and potentially either:
- Identify and fix a bug in the ToSpeckle conversion.
- Throw a more meaningful exception instead of returning null!

**Comment by AlanRynne** [comment]
I'll add my 2 cents here:

`Throw a more meaningful exception instead of returning null!`

**YES** 🙏🏼 I've come to the realisation that returning null in our converters was a very bad decision 😅
The meaning of `null` is not clear (did the conversion fail? was it just not supported? should we retry at the end...). Properly documented exceptions would be ♥️

It also forces us to defensively code for both `null` and `exception` cases, with both triggering the same behaviour in reality.
