### ISSUE TITLE
Add support for electrical circuits in Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2604]
The “Electrical Circuits” category is made of non-geometrical elements and they are not currently being sent to Speckle.

https://speckle.community/t/is-it-possible-to-push-electrical-circuit-data-to-my-stream/5812/5

**Comment by teocomi** [comment]
Probably fixed as part of: https://github.com/specklesystems/admin/issues/429

**Comment by majidaldo** [comment]
> Probably fixed as part of: https://github.com/specklesystems/admin/issues/429

can you fix the link pls?

**Comment by teocomi** [comment]
Sorry that's a private repo! But the fix will included in the coming 2.16 release, a RC is scheduled for tomorrow :)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
