### ISSUE TITLE
Revit: Improve MEP support [masterissue]

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2608]
This is a master issue to collect a few related issues.

- https://github.com/specklesystems/speckle-sharp/issues/2604
- https://github.com/specklesystems/speckle-sharp/issues/2597
- https://github.com/specklesystems/speckle-sharp/issues/2337
- https://github.com/specklesystems/speckle-sharp/issues/1915
- https://github.com/specklesystems/speckle-sharp/issues/1436
- https://github.com/specklesystems/speckle-sharp/issues/2004
- 

Once tackled we should ensure, this use cases is also addressed:
- https://speckle.community/t/publish-linked-revit-models/2444/39

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
