### ISSUE TITLE
Deleting stream on frontend causes DUI error that crashes Revit

### ISSUE THREAD

**Issue by connorivy** [specklesystems/speckle-sharp#2623]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

DUI

## Describe the bug

Revit crashes when I delete a saved stream from the frontend

## To Reproduce

1. Create a stream in Revit
2. Send to that stream
3. Delete stream on frontend
4. Delete stream card from DUI
5. May need to try two or three times to get it to crash

## Screenshots

![delete-stream-crash](https://github.com/specklesystems/speckle-sharp/assets/43247197/8c2d774d-ace0-4322-b460-63cbc33a5149)

## System Info

If applicable, please fill in the below details - they help a lot!

**Comment by teocomi** [comment]
Hey Connor, on what branch are you getting this?
The `UserStreamRemoved` subscription has currently been disabled: https://github.com/specklesystems/speckle-sharp/blob/dev/DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs#L340
