### ISSUE TITLE
Move binary test files to Google Drive

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2636]
Let's reduce our repo size by moving rvts and other heavy binaries outside the repo.

**Comment by AlanRynne** [comment]
The problem with that is that Git LFS is charged both by "data storage usage" and "network bandwidth". Meaning the more people pull the files, we get charged more for it.

If we ever stop paying for LFS (or gets too expensive), we'd need to back-edit the history of the LFS part for the repo to allow users to pull it again without it.

I've been through this in one of my repos and it was bit of a PITA.

**Comment by teocomi** [comment]
Discussed with Alan today and we decided to:
- move all Revit test files to a shared google drive folder (I made [this one](https://drive.google.com/drive/folders/1k4kQdjUHm-LSOT_uf9qZuIA-a9KePr4H?usp=sharing) in our drive) and document so in our Readme @connorivy 
- try removing these binaries from our Git History to keep the repo size small, [see this] @AlanRynne (https://docs.github.com/en/repositories/working-with-files/managing-large-files/moving-a-file-in-your-repository-to-git-large-file-storage)
