### ISSUE TITLE
Send Breps from Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2647]
The Revit connector only extracts the Mesh representation of elements, but some workflows call for a more detailed representation. We could (optionally) also extract their solid/Brep geometry when sending to Speckle.
See thread: https://speckle.community/t/not-receiving-breps-from-revit/5943/4

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
