### ISSUE TITLE
Core: Objects specific traversal rules should not exist

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2658]
Our default traversal contains some rules that are "objects-specific" i.e. are based on checking the speckle_type of an object.

This is non-breaking, but also a bit of a red flag. We should come up with a way for Core to know if something needs ignoring without having to know the object. Similar to `SchemaIgnore`?

_Originally posted by @AlanRynne in https://github.com/specklesystems/speckle-sharp/pull/2651#discussion_r1226468417_

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
