### ISSUE TITLE
Brep failing to convert Rhino => Rhino

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#266]
Some Brep sent Rhino => Rhino are having conversion issues. Not urgent but something for our backlog!

[Sample model.3dm ](https://drive.google.com/file/d/1aGNflvvK8MrZQn_hIArJXq1k_fdNEc67/view?usp=sharing)
[Sample Stream](https://staging.speckle.dev/streams/d2f5207515)

**Comment by AlanRynne** [comment]
Aha! More weird _edge case_ candidates!! Will look into it 👀

**Comment by AlanRynne** [comment]
This was caused by some mismatch in Matteo's machine and is not a real issue. Can you confirm @teocomi?

**Comment by teocomi** [comment]
I confirm and 🤦‍♂️!
