### ISSUE TITLE
bug(Excel) Operation cancelled when receiving all fields

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2676]
It's not possible to load data into Excel table when all fields are selected. It works if one field us unselected.

### To reproduce
1. open this stream https://speckle.xyz/streams/f2ffe143f3
2. hit Receive and filter button
3. try to download "Info" 
4. select "all fields" and hit OK
5. "Operation cancelled" error notification pops up and receiving fails

![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/74745323-e9d8-49a2-920d-41e739edbb76)

6. unselect one field and try again
7. data is received successfully

**Comment by teocomi** [comment]
@paloknapo fixed in https://github.com/specklesystems/speckle-excel/pull/51 :)
