### ISSUE TITLE
bug(Parameter Updater): Values from formulas received incorrectly to Revit

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2687]
Various values from Excel formulas are send fine to Speckle but only one is populated in the Revit schedule. 

### Sample data

- [Excel spreadsheet](https://1drv.ms/x/s!AuYBAkIukpz2iZ5A6yvLmJZ1daIl8A?e=Wd0JNA)
- [Speckle commit](https://speckle.xyz/streams/030b829d5a/commits/b31b8e35cb) from data above
- [Revit file](https://drive.google.com/file/d/1o00Wzer9FtNRF28Zl8_oo9PS_0DgFxh7/view?usp=drive_link) with wrong data, see "Walls schedule"

### To replicate
1. Open Revit file above, go to "Wall Schedule" and delete values in row "Description"
2. Receive from commit above

formula used in Excel: `="price per segment "&SUBSTITUTE([@Area],"m²", "")*[@Cost]`

![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/9d476263-292e-4717-bb97-89b9edb1c906)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
