### ISSUE TITLE
Inconsistent use of the `category` prop on DirectShapes

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2733]
I noticed we're inconsistently using the `category` prop on `DirectShape` Speckle objects:

- first, it's a `RevitCategory` enum and not a string
- second, it gets serialized to int 😅

This was designed when we first implemented the GH BIM nodes, but we should find a better solution now.

![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/f0bf42c3-0ea1-4383-9603-2de60e40c26c)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
