### ISSUE TITLE
bug(grasshopper): StreamGet resolves Stream Id with default Account not the account provided

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2742]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

RhinoGH

## Describe the bug

<img width="1029" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/760691/c7bafff7-58a6-4b32-ae50-b89201cc2bb7">

User expectation would be that passing a String ID per the property label and providing an account would resolve to the Server Stream.

Instead, the Node uses the Default Account server to resolve a Stream ID, not the provided account property.

_Providing a Stream Url including the ID resolves to a stream as expected._

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
