### ISSUE TITLE
Revit Preview not Working

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2744]
![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/c824dc8e-46e7-44c5-9bcf-fd5ec4b51c44)

The Receive preview does not work, it seems to be a casting issue. 
If this can't be solved quickly we should then disable the preview entirely.

**Comment by JR-Morgan** [comment]
Receive preview now disabled: https://github.com/specklesystems/speckle-sharp/pull/2772

Even if we can get it working again, the current implementation is very broken, and not super useful imo.
- 1. we are using mesh conversion only, so the preview isn't even a preview of the actual conversion that would happen. Unlike in rhino (which does a full conversion, just without a bake) 
- 2. We don't convert instances, so some objects are going to appear in the wrong place in the preview.
- 3. We don't do a complete traversal, we just convert all meshes, so we may include meshes that shouldn't be displayed anyway.

If we want to bring it back, it would take a fair bit of work.
And as far as I can tell, the only benefit it has to, say the viewer, is to see your geometry in context with your model.
