### ISSUE TITLE
Revit: Align traversal behaviour with other connectors

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2747]
Right now, The Revit connector is an exception when it comes to ToNative traversal. In that we perform most of the traversal inside the converter.

This leads to 
- Duplicated logic that is easy to misalign
- Incomplete reporting as hosted/nested speckle objects won't have report cards created
- Traversal misalignment with other connectors
- Exception handling is inconsistent and can lead to bugs where one object failing can cause parents to fail conversion.

I propose (and agreed with @connorivy) we need to first align the Revit connector before we can have reliable error reporting

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
