### ISSUE TITLE
Corridor Featureline - Curve is "null" but points are extracted

### ISSUE THREAD

**Issue by jhdempsey86** [specklesystems/speckle-sharp#2749]
## Prerequisites

- [x ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [ x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x ] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Civil 3D Connector 2.14

## Describe the bug

When pushing a corridor object into Speckle, the featurelines are visible in the data. But the "Curve" parameter of the object is null. But it does manage to extract the points of the featurelines.
I have used the same DWG file previously with the same version of the connector, and the Curve property had a value.
I have since amended the corridor object, by manipulating the surface it uses as a target, and to add some extra subassemblies on to the assemblies that are used in the corridor

## To Reproduce

Use the attached DWG file. 
[Verge Test Drawing for BART.zip](https://github.com/specklesystems/speckle-sharp/files/12016166/Verge.Test.Drawing.for.BART.zip)
Push the contents of the DWG file to any Speckle stream
Inspect the featurelines held in the Speckle database. 
The curve parameter of each featureline is showing as null
This can be seen in the following commit:
https://speckle.xyz/streams/7b8b693358/commits/248c99e012
From description of the bug above, its difficult to say what particular step of amending the corridor may have caused this behaviour. But the resultant corridor and featurelines do no have any issues in Civil 3D, so Speckle should be able to populate the Curve parameter

## Expected behaviour

The Curve parameter should be populated for the FeatureLine

## Screenshots

![image](https://github.com/specklesystems/speckle-sharp/assets/67244422/84ac4d8b-29f0-4408-a946-7a6601369f1d)

## System Info

- OS: Windows 10 Enterprise
- Version - Civil 3D Connector 2.14.4

## Failure Logs

None

## Additional context

None

## Proposed Solution (if any)

None

**Comment by jhdempsey86** [comment]
@teocomi can you please add to your backlog?

**Comment by teocomi** [comment]
Yes! @clairekuang can you please have a look? Hopefully it's a quick one :)

**Comment by clairekuang** [comment]
Hi @jhdempsey86 , since corridor featurelines can have breaks (resulting in multiple curves), the conversion has been improved two releases ago and the curve value has been moved to the `displayValue` property. Let me know if this is an issue for you, or if you have suggestions on how to handle the case where featureline baselines have multiple curves.

**Comment by jhdempsey86** [comment]
@clairekuang, thanks for letting us know. I will adjust or code to look at the displayValue property rather than the "curve" property.

Can you confirm in which release that update was made? I will need to temporarily roll back the connector I use so i can continue working while I wait for someone else to update a shared library where we need to switch to using the "displayValue" property
