### ISSUE TITLE
DesktopUI: filters do not update with user changes if they are already applied

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#275]
Desktop UI doesn't allow changes in filter application once one or more filters are already selected. User changes are reflected in the button controls, but do not persist after setting.

![image](https://user-images.githubusercontent.com/16748799/109451083-8a349a00-7a44-11eb-8cd3-3e933156097c.png)

**Comment by teocomi** [comment]
Hey Claire, I experimented with this a bit in Revit and found the following, can you please confirm on your end:

- changing filter **type** works as expected (eg going from _selection_ to _category_)
- adding new items to a list based filter (eg categories) works as expected
- removing items from a list based filter, **doesn't work**

**Comment by clairekuang** [comment]
Yes, tested and confirmed for both Rhino and Revit!
