### ISSUE TITLE
DesktopUI: small bugs

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#276]
- [x] "Stream Details"  header fails to update when switching back to main view after stream deletion

![image](https://user-images.githubusercontent.com/16748799/109456235-45aefb80-7a50-11eb-934e-ee54412c7aab.png)

**Comment by izzylys** [comment]
- [ ] this terrible overlay that isn't changing for light mode (i'm sorryyyyy)
![image](https://user-images.githubusercontent.com/7717434/109530471-acfb9880-7aae-11eb-847b-54ccd040ccab.png)
- [ ] button to remove streams you don't have a local account for / don't have access to

**Comment by clairekuang** [comment]
- [ ] disallow creating streams with the same name as an existing file stream
- [ ] include stream id in stream details card (helpful in the case of adding a stream with the same name as an existing stream)

![image](https://user-images.githubusercontent.com/16748799/109991848-9a799d00-7d02-11eb-8e7a-451e35393cf4.png)

**Comment by izzylys** [comment]
i also liked having the stream id there, but @didimitrie is the one to blame for removing them hehe. thoughts? are we bringing em back?

**Comment by teocomi** [comment]
I think disallowing duplicated stream names would require too many changes, but in favour of adding the stream id (ideally subtly below the name?).

**Comment by clairekuang** [comment]
> I think disallowing duplicated stream names would require too many changes, but in favour of adding the stream id (ideally subtly below the name?).

Updated comment to reflect this!

**Comment by izzylys** [comment]
do we want it on the card as well or is it not needed?

![image](https://user-images.githubusercontent.com/7717434/109997857-8cc71600-7d08-11eb-8d0f-5caba6506885.png)
![image](https://user-images.githubusercontent.com/7717434/109997863-8e90d980-7d08-11eb-8177-1847e815df78.png)

**Comment by clairekuang** [comment]
Personally would prefer leaving it out on the card, would be nice to leave whitespace for more frequently referenced info instead (like a 'last updated' timestamp?) - but it's up to @didimitrie
