### ISSUE TITLE
Core: ParallelServerAPI depends on ServerAPI

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2770]
Problem:
The `ParallelServerAPI` has a hard dependency on `ServerAPI` (rather than using the `IServerAPI` interface)

This means `ParallelServerAPI` cannot be unit tested.

Potential Solution: 

1. Add the `HasBlobs` function to the `IServerAPI` interface
    - This is the only operation missing from the interface.
    - This is not quite as simple as it should be [due to this line](https://github.com/specklesystems/speckle-sharp/blob/a9513f6683510840f546e2d9f54ddf209cbbe00f/Core/Core/Transports/ServerUtils/ParallelServerAPI.cs#L236)
2. Replace reference to `ServerAPI` in `ParallelServerAPI` with `IServerAPI`

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
