### ISSUE TITLE
DirectShape fallback on receive

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2777]
When receiving in Revit, we should always fallback to a DirectShape conversion (with a matching category) in case:

- it's receiving native objects that are unsupported (`CanConvert` does not return true)
- the conversion fails or is known to be buggy (eg roofs) NOTE: instead of returning null when the conversion fails, we need to call this fallback method
- ~LATER elements with no matching family & type (to be investigated as an option for the type-matching dialog)~

**Comment by paloknapo** [comment]
Conversion error interrupts receiving with fallback option and with missing types mapping ignored. 

Revit throws this error and receive operation stops. 


![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/3eba1d01-b7cb-4962-8564-7eed1193e152)


![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/d69dd355-4c41-41db-8215-2501d948ef85)

Seq errors:
https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-929b9de2a7a708dbb5dc338600000000%27&showExpanded&permalinkId=permalink-307
https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-a664154ba7a708db3df5338600000000%27&showExpanded&permalinkId=permalink-308
https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-a664636aa7a708db3ef5338600000000%27&showExpanded&permalinkId=permalink-309
https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-a67d31eaa7a708db3ff5338600000000%27&showExpanded&permalinkId=permalink-310


Tested with 2.26 wip3
Test model https://latest.speckle.dev/streams/a585a6df6c/commits/825a98bb04
