### ISSUE TITLE
GH: Upgrade `T4` template to new `SourceGenerator`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2810]
T4 template has been a blessing and a curse. The new Source Code Generators for C# are much better.

They are run as part of the build process, so there is no need for extra tools or dependencies

They also allow for higher levels of customisation that is not really possible (or at least, comfortable to code) in a T4 template

Lastly, nobody knows how T4 templates really work, most people don't know they exist. Source Code Generators have been widely documented in the recent releases and allow for a degree of separation with the main Grasshopper code that wasn't currently possible. 

## Solution

The branch linked to this issue has an initial prototype implementation I coded in under 2 hours (hence, requires another careful look at it whenever we get to this).

It also addressed the issue that we had on our generation logic where moving the constructors or modifying its parameters in any way, will completely break the previous code, because the name of the class and its `guid` were affected by it.

It generates both the new components and the upgraders to automatically swap all `obsolete` components for the new ones.

## Good opportunity for:

- Thinking about Icons? At least one color per app. @bimgeek already had some done in the past but adding them to the T4 template was going to be ugly.
- Going through our nodes and verify that keeping them makes sense.

## Potential problems

This will require A LOT of testing. In essence, we're swapping every single schema node, so we would have to test 100+ components for:

- Correctness in the node generation
- That the node runs as expected and classes can be received in the target application successfully.
- Ability to upgrade old nodes to new ones while preserving all existing connections.

**Comment by bimgeek** [comment]
i'd be happy to help with testing this.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
