### ISSUE TITLE
Support for sending multiple instances of the same Linked file

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2823]
The selection logic is currently assuming only 1 instance of linked models can be present in the document, but apparently, there can be multiple ones.

Community report: https://speckle.community/t/revit-to-sketchup-multiple-instances-of-revit-link-model/6630/3

### Proposed solution

Treat linked models just like any other element instance in the main doc.
This means that linked models will always be sent in their entirety, and category filters will not be able to selectively pull elements out of them. This is a (big) limitation, but otherwise, we'd need to change our whole conversion logic to keep track of what  `RevitLinkInstance` each element belongs to.

cc @clairekuang as I think she proposed this approach back when dealing with transforms

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
