### ISSUE TITLE
bug(Revit) Sending linked models from view doesn't work

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2829]
Error pops up and sending fails when sending linked models with view selection.
![image](https://github.com/specklesystems/speckle-sharp/assets/760452/91eb8115-7a8d-4ef5-a114-47f7d8341779)

## To replicate
1. Open [this test model](https://www.notion.so/speckle/Linked-Model-Project-1-2702975de7d943c09c4b58c0b53dd428?pvs=4) 
2. Set selection filter to "3D View 1"
3. Activate "Send linked models" in advanced settings 
4. Send - fails with error

[Error log in Seq](https://seq.speckle.systems/#/events/?filter=@Id%20%3D%20%27event-aebceab0941908db7940047300000000%27&showExpanded&permalinkId=permalink-300)

**Comment by teocomi** [comment]
Related to #2823 , we're essentially not dealing with linked models well.

**Comment by paloknapo** [comment]
It is possible to set visibility of linked models individually for each Revit view. Sending linked models doesn't need to be supported until the #2823 issue is resolved but user should be able to send a view without any errors. 


![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/e1e4a977-4c23-4ea1-9c43-25449b9ee974)
