### ISSUE TITLE
feat (rhino-mapper) Add surface mapping option for roofs and ceilings

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2835]
In Speckle Mapper for Rhino, add mapping options:

- surface as (Revit native) ceiling
- surface as (Revit native) roof

Options will be accessible in "Revit Element to Map" drop down after receiving project info, see below.

Test project info for Revit house here: https://speckle.xyz/streams/9ff64f51e6/commits/e0b54940a7

**Comment by clairekuang** [comment]
@paloknapo could you make the test project info stream public, or add me?
