### ISSUE TITLE
feat(rvt): Send Toposolids

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#2854]
## Description

With Revit 2024, Topography is out and Toposolids are in. They are very similar to other Sketch-based elements like Floors, Ceilings etc. Currently they are being skipped on send. So no geometry, nothing is sent.

## Files Used

I used Snowdon Towers sample project that comes with Revit 2024.

## Speckle Model URLs

https://speckle.xyz/streams/88bc8b9f85/branches/site

## Screenshots

![image](https://github.com/specklesystems/speckle-sharp/assets/51519350/58efd850-13d1-4b9e-9d8e-cc892fa07174)

![image](https://github.com/specklesystems/speckle-sharp/assets/51519350/18cf5bcd-090e-4065-ad41-afd23bd938d0)

Toposolids docs here:

https://www.revitapidocs.com/2024/7516b682-d489-a462-47ab-192c63d1d9e4.htm

Test file
https://drive.google.com/file/d/1UPjoyB4DD8kUdC_zICY9z2HKlvvQPiXl/view?usp=drive_link

Test commit
https://speckle.xyz/streams/9ff64f51e6/commits/cb9937318a

**Comment by paloknapo** [comment]
Same as https://github.com/specklesystems/speckle-sharp/issues/2757

**Comment by BovineOx** [comment]
@paloknapo should we mark one as a duplicate?

I have some questions/statements:
- Topography is still supported in 2024 and when I open the 2023 test file in 2024 the Topography is not converted to a Toposolid, I believe we should treat Topography stored in Speckle as Topography still and not convert it - agree?
- Do we wish to support Toposolid more generically or do we consider this Revit specific?
- Would other software treat Toposolids as a mesh, just using the display value? Do you know what we do for Topography today in other software?
- If I store a Toposolid from 2024, would we expect it to open in 2023 as Topology? I think not but needs some thought

**Comment by paloknapo** [comment]
1. Yes, there is no need to convert Topography. 
2. It's currently Revit specific but I'll check how Archicad deals with terrain models and if a more generic support for Toposolids is needed.
3. Yes, receiving Toposolids in other Connectors as mesh (display value) is OK.
4. Ideally, a Toposolid from Revit 2024 could be received as Topography in Revit 2023 but please investigate further. This has low priority and if the solution is too complex, receiving it as DirectShape with category Topography could do the trick.
5. Yes, details TBD

**Comment by BovineOx** [comment]
So the current observations are:
- Pushing the sample model from #2757 actually pushes the toposolid if you push everything but it does not seem to be selectable?
- It pushes as geometry only
- Pulling it back works but... if you drop to perspective view, the perspective is extreme, so I wonder if the object geometry is being scaled incorrectly when pushed or pulled out
- Revit 2024 hung when pushing the Snowdon towers sample

**Comment by BovineOx** [comment]
Hmmm cannot repro the error, could just be while debugging...  will post back if I learn more

**Comment by BovineOx** [comment]
- Receiving the geometry stored as RevitElement in Speckle we seem to get two items

**Comment by BovineOx** [comment]
Should look at Ceiling and Floor objects from Revit API

**Comment by BovineOx** [comment]
[just_topography_2023.zip](https://github.com/specklesystems/speckle-sharp/files/12586014/just_topography_2023.zip)

Added the file above, curiously if I push the whole thing I get extra geometry I am not expecting...  but I think if I select the pads and topo I am fine.

**Comment by BovineOx** [comment]
Archicad notes:
https://www.notion.so/speckle/Topography-e151b3e8af2a4c9abdd4d16559187068#ed6d6fb12c6a436d95d0478d42870236

**Comment by paloknapo** [comment]
Tested, works as expected.
