### ISSUE TITLE
bug (revit): brace to speckle conversion missing properties

### ISSUE THREAD

**Issue by dtnaughton** [specklesystems/speckle-sharp#2858]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

speckle-sharp

## Describe the bug

Numerous properties are missing on brace to speckle conversion (including but not limited to material quantities, category etc...).

## To Reproduce

Send any brace from Revit to Speckle

## Expected behavior

Should include similar properties as are sent for beams to speckle.

## Additional context

Conversion issue occurs because[ BraceToSpeckle method](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertBrace.cs#L41) relies on using BeamToSpeckle method and then creating a new RevitBrace object and mapping the properties from the RevitBeam obj. The properties are successfully added to the RevitBrace object, but most dynamic properties are not mapped across in the conversion from beam to brace.

## Proposed Solution (if any)

We should utilize Core methods to fetch all dynamic properties of the beam object and map those to the brace obj.

**Comment by dtnaughton** [comment]
I'd be happy to open up a PR with a proposed fix if that's more convenient.

**Comment by teocomi** [comment]
Hey @dtnaughton , good find! Yes, I think getting all dynamic props from the Beam and adding them to the Brace would work. Can you make a PR?
