### ISSUE TITLE
bug(rvt): MEP elements fail to scale some of their parameters on `ToSpeckle`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2863]
Just a couple of things I noticed while testing the new send-everything changes:

From this commit https://latest.speckle.dev/streams/4e51c4025f/commits/178faef2d5

- This elbow connection is received in Revit with 45 degree angle instead of 90 ![Screenshot 2023-08-21 at 09 09 30](https://github.com/specklesystems/speckle-sharp/assets/2316535/965f8424-0c33-42e0-b5ad-c4cde94d9c91)

- These elbow connections have incorrectly scaled their bend radius ![Screenshot 2023-08-21 at 09 11 09](https://github.com/specklesystems/speckle-sharp/assets/2316535/6312ee8c-2ed1-49aa-9b83-8389bb25fe80)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
