### ISSUE TITLE
GH: Possible detaching issue on `Extend Speckle Object`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2865]
Reported in the forum: https://speckle.community/t/detached-properties-when-extending-object/6850

Possible detaching issue in `ExtendSpeckleObject` that does not propagate the `detach` property of the input param to the param name.

This could lead to potential objects not being detached on that property, which in turn can lead to "object too big" errors when sending.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
