### ISSUE TITLE
bug(Revit): Cached conversion methodology assumes scale factors only

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2878]
The performance refactor introduced to cache the returned results from Revit API `ConvertFromInternalUnits` assumed all returned values with be a conversion factor. Some conversions, however, are a constant offset e.g. K to C

https://github.com/specklesystems/speckle-sharp/blob/faf081f9f5ab3cdafb25c2503bfbe92ed31b41b9/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/Units.cs#L203C4-L208

Offset conversions (like temperature) return wildly incorrect results.

UI Value: 13.1499deg C
Internal: Value: 285.372
Unit Type: celsius
cacheValue: -272.15

error returns: -77664.05 degrees

**Comment by teocomi** [comment]
🙌

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
