### ISSUE TITLE
Revit: DXF import places objects incorrectly

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2907]
Reported in the forum and confirmed to be an issue in 2.16: https://speckle.community/t/revit-mesh-coordinates/6524

DXF import from navisworks lands in the wrong location. Normal DirectShape import works as expected and objects are correctly located in model space.

**This particular issue is no longer reproducible with the Navis files the user provided**: Changes in the conversion of Revit, and the addition of the "displayableObject" conversion handles this case correctly so no DXF import is performed (displayable objects are converted to DirectShapes). User mentioned lack of materials but this has also been fixed in 2.16

**The DXF issue is still there** though, I'm trying to reproduce the issue with files from Rhino, but it seems there are some assumptions that we've made when importing DXF that are not correct.

EDIT:

Issue is reproducible with a simple file from Rhino. Located a set of meshes near the origin and also 17km away (futher than revit can handle) and the behaviour does look a lot like what's going on in the forum user's model.

![2023-09-12 13 38 55](https://github.com/specklesystems/speckle-sharp/assets/2316535/6f3f6313-d244-40fe-9096-3b8d5b4b0d63)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
