### ISSUE TITLE
bug(navis): transformation by bounding box not relocating geometry to model origin

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2916]
3 options exist for geometry transformation: 

1. Navis Model Origin
2. By Bounding Box centre
3. By Project Location

The latter 2 of these options should relocate geometry relative to the transformation origin to model origin 0,0

Bounding Box transforms appear to be broken.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
