### ISSUE TITLE
Revit: Illegal attempt to modify document. Reason: HandleEvent was not called from UI thread

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#2918]
This exception is thrown when opening the Revit 2024 sample model and as a first thing sending by view to Speckle.
A manual workaround is to open any other view before sending.

![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/34e9be04-c449-4ae0-8f93-d8628e6daf4f)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
