### ISSUE TITLE
ConverterRevitTests missing for 2024

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2927]
**User Story**
**As a** Speckle Revit user
**I wish** the ConverterRevitTestsShared to be available and run for Revit 2024
**In order to** catch any issues in unit/integration tests relating to 2024

Additionally we should review places where we have added specialisation for 2023 (i.e. #if REVIT2023) to see if those sections should apply to 2024 also.

It was also said that the these shared tests are not running for 2023 but I do see the project for that version. It should be checked.

Where these tests are consumed they should also be consumed for Revit 2024.

We should also copy the pattern from UNITY using the UNITY_XXX_OR_NEWER

- Add ConverterRevitTestsShared for Revit 2024
- Check conditional compilation to ensure 2024 is encompassing any areas as it should
- Add the pattern above from unity UNITY_XXX_OR_NEWER

<img width="262" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/73857041/bc7d52c2-113f-401f-a9e6-28f1f6ac1b39">

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
