### ISSUE TITLE
feat (Tekla) Support mod items

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2932]
## Description

https://www.notion.so/speckle/Support-mod-items-3711ba1017594cacab17d54c0a8fdaee?pvs=4

## Test model

...coming soon

## Acceptance criteria

Given that I created a item in Tekla, when I send it to Speckle, then it appears in the viewer.

Given that I created complex geometry in Grasshopper, when I send it to Speckle, then it can be received to Tekla as mod item.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
