### ISSUE TITLE
Seq error reporting for structural connectors

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2934]
User Story
As a Speckle Engineer and Monitor of SEQ
I would like error reporting for structural connectors to be consistent with existing pattern (see below)
In order to be able to interrogate SEQ for errors in a comprehensive way that provides insight and enables root cause analysis

The scope could be limited to ETABS with other tickets.

Nascent A/C:
* Same exercise as we did for Revit in 2.16, details TBC.
* Move away from app object manipulation, consuming existing pattern for exception handling and reporting
* Returning null patten should be changed to adopt throw pattern used elsewhere

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
