### ISSUE TITLE
bug(tekla): Conversion report is not itemised and non-scrollable

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2937]
<img width="280" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/760691/38c995bb-3665-4696-822a-8421cffe88cd">

Expectation: The conversion report (send) to be itemised per element as per the other DUI2 connectors
Found: A long timestamped text list

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
