### ISSUE TITLE
Investigation: ETABS GraphTraversal should be upgraded

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2938]
**User Story**
Investigation to support...

  **As a** Speckle engineer
  **I would like** ETABS to use traversal consistent with other connectors
  **In order to** avoid non-standard methods that can lead to bugs, inefficient development etc...

This estimate is the gap analysis between current implementation and what needs to be done. If the gap is found to be small at the end, then we can discuss, document the changes on the ticket and deliver as part of this ticket, otherwise the output should be a new ticket with the technical implementation

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
