### ISSUE TITLE
Investigation: Does update receive work as expected?

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2941]
**User Story**
**As a** Speckle Engineer and consumer of Speckle (ETABS)
**I would like** confidence that receive update mode and send and receive generally are working for ETABS
**In order to** raise any issues to resolve breakages in ETABS that need addressing ahead of Grid support

The output of the ticket should be confirmation of the send/receive working as expected in all modes and any ticket(s) to resolve, preferably with technical solution added.

Should also consider this setting of which Mode the connector is in?
* "There’s a setting distinction between “send” and “receive” modes" - this does not feel quite right?

**Comment by paloknapo** [comment]
Grasshopper - updated elements:

- columns
- beams
- walls
- slabs

Grasshopper - not updated elements:

- braces

Revit - updated elements:

- columns
- beams
- walls
- slabs

Updating slabs can result into corrupted geometry. 


![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/57833ebc-55bc-4249-a56a-aee38310acc8)


Revit - not updated elements:

- ...

Updating is quite slow even with small models.

**Comment by paloknapo** [comment]
Broken geometry bug reported here https://www.notion.so/speckle/Broken-geometry-when-updating-slabs-in-ETABS-5c539b61ed9f4f28a682da2f4329cfe0?pvs=4
