### ISSUE TITLE
Review existing grid class and options for grid support

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2943]
**User Story**
**As a** Speckle Team member
**I would like to** know the existing grid implementation as well as the various representations of Grid across the connector host suit and how they are used
**In order to** understand and help define the scope of Grid Support for ETABS and beyond

The output should be details of how grids are currently defined, as well the workflows we wish to support and the scope therefore of the grids work.

I have included Pavol in the discussion as he will need to link in the views and workflows from the community 

https://www.notion.so/speckle/Grids-Capability-API-check-by-Host-App-5c7caec9330d4546879ac886587a1ff2

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
