### ISSUE TITLE
Review the TODOs in ETABS

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2944]
**User Story**
**As a** Speckle Engineer (Speck-eng-eckleer?)
**I wish to** review the TODOs within the **ETABS** code
**In order to** resolve or create issues to resolve material problems

The output should either be some small fixes or some tickets to fix larger items. We do not want a god PR of course so err on the side of investigation and writing up tickets with technical descriptions.

**Comment by AlanRynne** [comment]
Forgot to dump my findings in notion:

https://www.notion.so/speckle/CSI-Connector-Pending-TODOs-0f4a9a1c8bad4a37ba3c5c1f77b2fc3d?pvs=4
