### ISSUE TITLE
Handle instancing, even if ignore for now

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2946]
**User Story**
**As a** Speckle Engineer (and ETABS Connector user)
**I would like** to handle instancing in ETABS
**In order to** avoid the connector and host application crashing

Instancing should ideally follow the same patterns as elsewhere (do we have a definition? for A/C purposes?)

If following the pattern is a large item, then we should ignore instancing, not crash and raise a ticket to add support.

**Comment by AlanRynne** [comment]
Check if instances are properly ignored. A potential edge-case could be `StructuralFoundation`s from Revit

**Comment by paloknapo** [comment]
Revit instances are ignored including StructuralFoundations, Connector doesn't crash. 

Rhino blocks are not ignored completely, some are loaded. 
https://speckle.xyz/streams/9ff64f51e6/commits/5380e61669

![Image](https://github.com/specklesystems/speckle-sharp/assets/760452/489545e0-57bf-4511-9cd3-c6c3ee3eddc6)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
