### ISSUE TITLE
Investigation: Does ETABS structural model class properly implement collections?

### ISSUE THREAD

**Issue by BovineOx** [specklesystems/speckle-sharp#2948]
**User Story**
**As a** Speckle Engineer
**I wish to** know that the Structural Model class within ETABs correctly implements collections or what is required to do so
**In order to** properly schedule the work to implement collections if required and assess if necessary ahead of grid support

There was some concern that the structural connectors are behind on the current collection implementation and whether we need to do work ahead of grids to support this.

It may be we do not, but if work is ultimately required then we should create a ticket and document the technical solution. If it is require ahead of grids then it needs to be raised as something to do ahead of grids.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
