### ISSUE TITLE
Etabs sends objects with null units

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#2950]
With a little testing. I noticed that some objects are sent with units, and some objects are not

https://latest.speckle.dev/streams/c1faab5c62/commits/6dc6d1ff25?c=%5B761.69052,-458.1221,318.33574,10.9728,288,288,0,1%5D

![image](https://github.com/specklesystems/speckle-sharp/assets/45512892/769f745a-b151-4dd8-b9f7-c3b70ee2f951)

Steps to reproduce:
1. Draw some Beam/Column/Brace
2. Draw some tendons
3. Send everything to speckle
4. observe tendons have `null` units, and scale incorrectly in viewer.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
