### ISSUE TITLE
Revit: PolyCurve conversion not working properly

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#296]
Seems like the Revit converter is only handling the **first** curve in the Speckle `PolyCurve` when converting to native.

This prevents from creating complex model-curves, revit floors, etc...

**Comment by teocomi** [comment]
Related to this, I believe that if a polycurve/polyline is used as a base curve for walls, only the first segment is created.
Possibly a fix could address both issues.
