### ISSUE TITLE
Mac CI Zip step should fail if it doesn't find any of the items

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#2960]
Related to #2958 

Ideally, we'd like to fail the CI run if a single file that is expected from the `ZIP` process is missing/can't be found.

<img width="1511" alt="Screenshot 2023-09-21 at 10 22 07" src="https://github.com/specklesystems/speckle-sharp/assets/2316535/e0d48e1d-6e76-4117-9e51-bfc6545944e4">

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
