### ISSUE TITLE
Bug: The new 2.16 category naming implementation needs alignment

### ISSUE THREAD

**Issue by martinromby** [specklesystems/speckle-sharp#2976]
The new 2.16 rc3 category naming implementation needs name alignment in the object. 

**2.15.2**
This connector version has a clear alignment on the naming between `elements[0].Name.value` (Structural Columns), `elements[0].applicationId.value` (Structural Columns) and `elements[0].elements[0].category.value` (Structural Columns)

See specific commit here:
https://speckle.xyz/streams/8bfb3033d8/commits/b3727333a2

![Category name alignment w 2 15 2](https://github.com/specklesystems/speckle-sharp/assets/15892140/1bd70512-6763-4423-92df-183f5888e249)

**2.16.0-rc3**
The new release candidate connector version has a misalignment on the naming between `elements[0].Name.value` (Structural Columns), `elements[0].applicationId.value` (Structural Columns) and `elements[0].elements[0].category.value` (StructuralColumns)
See specific commit here:
https://speckle.xyz/streams/8bfb3033d8/commits/e5a6eba82d

![Category name alignment w 2 16 0-rc3](https://github.com/specklesystems/speckle-sharp/assets/15892140/b909bfe3-edbe-4cd3-928c-ff9d76d5b371)

Since we work with a hardcoded list of categories, we would appreciate to keep the alignment as in the 2.15.2 version: `elements[0].elements[0].category.value` (Structural Columns)

Structural Columns is just used as an example, but the above goes for every categories mentioned here:
https://docs.google.com/spreadsheets/d/1By5RM0PCMw-M1ZVubXD3bF1FVz3Uk4u4vBrRUhJzWXw/edit?pli=1#gid=1933640094

**Comment by teocomi** [comment]
Thanks for flagging this Martin!
Seems to have been an involuntary consequence of our rework on categories. We'll make sure it's addresses before the stable release.

cc @paloknapo @AlanRynne

**Comment by teocomi** [comment]
Thanks for flagging this Martin!
Seems to have been an involuntary consequence of our rework on categories. We'll make sure it's addresses before the stable release.

cc @paloknapo @AlanRynne

**Comment by teocomi** [comment]
Hey @martinromby my understanding is that the strings sent in 2.15 use the display value of the Category field, which is localized.
How are you currently handling categories in other languages?

**Comment by clairekuang** [comment]
Hi @martinromby , to give you more context this misalignment was introduced because we've (1) refactored how we were previously sending category values with a [new list of `RevitCategory` enums](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Objects/BuiltElements/Revit/Enums.cs) for better internal alignment and (2) we are now using the category display name for our `Collection` class while using the enum value for object `category` property values.

Would changing the `Collection` name to match the object category property values solve your misalignment issue, eg using `StructuralColumns` instead of `Structural Columns` for both the `Collection` name and the object `category` value?

**Comment by martinromby** [comment]
Hi @clairekuang and @teocomi 
Thanks for taking time out of your retreat to get back to me on this. :)

> Hey @martinromby my understanding is that the strings sent in 2.15 use the display value of the Category field, which is localized. How are you currently handling categories in other languages?

We haven't run into these issues just yet. But this [PR](https://github.com/specklesystems/speckle-sharp/pull/2910) smoothens those bums - thanks! 🙌 

Just for reference:
Commit with 2.15.2 version - with DEU localization (localized category naming):
https://speckle.xyz/streams/8bfb3033d8/commits/059d931656

Commit with 2.16.0-rc3 version - with DEU localization (standardised category naming):
https://speckle.xyz/streams/8bfb3033d8/commits/bc4f108228


> Hi @martinromby , to give you more context this misalignment was introduced because we've (1) refactored how we were previously sending category values with a [new list of `RevitCategory` enums](https://github.com/specklesystems/speckle-sharp/blob/main/Objects/Objects/BuiltElements/Revit/Enums.cs) for better internal alignment and (2) we are now using the category display name for our `Collection` class while using the enum value for object `category` property values.
> 
> Would changing the `Collection` name to match the object category property values solve your misalignment issue, eg using `StructuralColumns` instead of `Structural Columns` for both the `Collection` name and the object `category` value?

Ahh - I see. At the moment we use the object `category` property values, but I agree that the ENUM lists are a better implementation and we'll change our whitelisted categories accordingly. 
I'll leave the `Collection` naming up to you, but I weigh towards some sort of naming alignment between `Collection` and `object`.
