### ISSUE TITLE
bug(tekla): Report Log renders in DUI as a text blob

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-sharp#2978]
Side effect is that the report also doesn't scroll.

<img width="412" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/760691/22b61b51-4ecb-4349-986c-1087eb16c1be">

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
