### ISSUE TITLE
bug (ETABS) Analytical wall openings missing from Revit

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2981]
Analytical floor with rectangular or circular opening is received to ETABS without opening causing overlapping floor objects in the benchmark model. 

## To replicate

1. Load benchmark or sample model to Etabs

### Sample model

Analytical floor with rectangular opening https://latest.speckle.dev/streams/557ae0024e/commits/269b761b7d

Analytical floor with circular opening https://latest.speckle.dev/streams/557ae0024e/commits/174d19d870

### 2.17 benchmark model

https://latest.speckle.dev/streams/557ae0024e/commits/9602d0f497

More in Notion

https://www.notion.so/speckle/ETABS-Missing-analytical-walls-with-openings-3748c760919447ce9b25494cf7f39582?pvs=4

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
