### ISSUE TITLE
bug (ETABS) Analytical slab opening missing from Revit

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2982]
Analytical floor with rectangular or circular opening is received to ETABS without opening causing overlapping floor objects in the benchmark model. 

## To replicate

1. Load benchmark or sample model to Etabs

### Sample model

Analytical floor with rectangular opening https://latest.speckle.dev/streams/557ae0024e/commits/269b761b7d

Analytical floor with circular opening https://latest.speckle.dev/streams/557ae0024e/commits/174d19d870

### 2.17 benchmark model

https://latest.speckle.dev/streams/557ae0024e/commits/9602d0f497

More in Notion

https://www.notion.so/speckle/ETABS-Slab-opening-not-supported-0de391eb52f6451c9122a44ab63e8469?pvs=4

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
