### ISSUE TITLE
feat (ETABS) Improved analysis results when sending

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2983]
> As a structural engineer, I want to send analysis results from Etabs to Excel for further work and refinement of results.
> 

> As a structural engineer, I want to send only analysis results for beams (columns, …) so I can share them with colleague who works in Excel on section sizes.
> 

> As a structural engineer, I want to send only analysis results for beams (columns, …) so I can send them to Excel for documentation.
> 

> As a structural engineer, I want to send only partial analysis results so I can load them to PowerBI and quickly create data visualisation dashboard.
> 

## Acceptance criteria

Given that a ETABS model contains analysis data, when I send it to Speckle with forceX setting activated, only analysis results for forceX are sent for all elements in the model.

Given that I selected only a few beams and columns, when I send the selection to Speckle, only analysis results for these elements are sent.

Given that I selected only category Floor, when I send floors to Speckle, only analysis results for walls are sent and received to Excel.

More in Notion

https://www.notion.so/speckle/Improved-analysis-results-when-sending-from-ETABS-ee25ab98901d45b8a76796efbfb9f012?pvs=4

**Comment by bimgeek** [comment]
Done: #3028
