### ISSUE TITLE
Revit: Custom Failure Resolution For `DocumentCorruption` 

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#299]
`DocumentCorruption` failures should be bypassed to allow the commit* to continue while skipping the problematic elements instead of rolling back the whole commit. I am not sure the right way to do this as `DocumentCorruption` errors are by definition fatal and require the commit to be rolled back. I attempted using a custom `FailureDefinition` to replace the found failures, but I don't think this was the right avenue as the replacement must also have a severity of `DocumentCorruption`. 

The other option I can think of is to somehow capture and save the ids of the problematic elements, roll back the commit, and re-commit without those elements. This would result in two transactions which I think could be ok, but would like others' input on this. Any other ideas would also be fab!

*commit here is always referring to committing a Revit transaction

UPDATE: try to solve this with subtransactions 

related to #189 and #298

**Comment by teocomi** [comment]
Hey Izzy, here's my 2p:
1. we can check with the ADN if there's any way to resolve those `DocumentCorruption` failures gracefully
2. I like the idea of rolling back and re-trying without the ids of the problematic elements, but it could add a lot of complexity to the connector and we might want to wait to go that way. Ideally, Sentry will help us decide how much needed this is!
3. for now the important bit would just be letting the user understand why the receiving operation failed and how to solve it

**Comment by izzylys** [comment]
thanks for your input!

1. it seems from the docs it's a pretty baked in thing that these failures roll back the commit as they inherently don't have any resolutions:

> DocumentCorruption: Failure that forces Transaction to be rolled back as soon as possible due to known corruption to a document. When failure of this severity is posted, reading of information from a document is not allowed. The current transaction has to be rolled back first in order to work with the document.

but I guess it's worth a shot! I did try manually creating a new failure and adding my own resolution, but they were not respected and `HasResolutions` still returned false.

2. agreed it would require some re-work, but I didn't have a better solution in mind atm!

3. tru at the moment I'm just passing the error back to the user to explain why the commit didn't bake, but the error might not be so clear. eg in the case of claire's error in #189, the error itself is not super helpful ("can't make wall"). I'll try to see if there's something better we can do here to give more info back to the user!

**Comment by OliverEGreen** [comment]
> This would result in two transactions which I think could be ok

Could these possibly be collapsed into a single TransactionGroup?

**Comment by teocomi** [comment]
That's the plan @OliverEGreen ! @izzylys don't spend too much on this, if subtransactions make conversion too slow or don't work we can park it for now :)
