### ISSUE TITLE
bug(CSI): Etabs Update mode deletes objects created within the current receive

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#3001]
Steps to reproduce:
1. Open ETABS and our connector
1. Receive https://latest.speckle.dev/streams/557ae0024e/commits/5cab2c8c71
2. New File without saving
3. Receive https://latest.speckle.dev/streams/557ae0024e/commits/8d3a75fafa

Observe not all objects get created successfully.
Many objects are visually missing, and in the report, these objects appear as "Removed".

Expected
All objects to receive correctly. If you re-receive straight after ^, then all objects come in correctly.

---

The logic in CSI connectors when receiving in Update mode is to delete objects that were previously received that no longer exist in the receiving commit.

It determines if the object exists via the application id. However, deletes based on the `name`

Because of this, if you have objects that share the same name, but different application Ids between two different commits. Then objects will be created and deleted within the same receive operation.

This is easiest to reproduce when creating a new file between receives
I've only tested this case, but perhaps this is also reproduceable without (unsure)

---

At first I thought this was a problem with my pr #2970 
But I can reproduce of current dev.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
