### ISSUE TITLE
Autocad: fix 3d polycurve with arc segments ToNative conversion

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#306]
**Test Info**

Connector: AutoCAD
Testing protocol requirement: receiving geometry
Test Case: 1A
Test stream link: https://staging.speckle.dev/streams/54850b5aff

**Report**

_Failed geometry_
- [ ] polyline::02-5-5.3d
  vertical segments collapsed to 2d

**Comments**
Current polycurve conversions do not support 3d polycurves with nonlinear segments because Autocad does not have a `DBObject` polyline or polycurve class that can be created with polycurve segments. 

Tentative solutions:
- Manually write a `.Join()` method to convert polycurve segments to a single `Spline` before baking created native object
- Convert polycurve segments to separate native objects, bake them, and then use the `Entity.JoinEntities()` method before conversion commit. This would require changing the `ConvertToNative()` method to support returning arrays or lists.

**Comment by didimitrie** [comment]
Quick question: do any of the below unblock this?
- A) from 3d polycurve, just create in acad non-joined individual curves from its segments? 
- B) simply make it a polyline? (might be a bit weird)

**Comment by clairekuang** [comment]
A) requires returning List<Base> from PolycurveToNative(), after that a join wouldn't take much more work
B) requires some parsing to determine if Base Polycurve is 3D, but otherwise easier though less ideal than A)

Currently the conversion behavior is:
C) flatten 3d Polycurves to be xy planar (preserves xy planar arc segments)

**Comment by didimitrie** [comment]
ah, ok! c) sounds like a good compromise for now. should we close this then?

**Comment by clairekuang** [comment]
Sounds good! Will make a note in the docs to convert 3d polycurves with nonlinear segments to spline in sending applications if users want to receive higher fidelity curves in acad
