### ISSUE TITLE
Revit: Column conversion ToSpeckle failing 

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#309]
The unit test passes somehow, but sending the BeamsCols.rvt test file to Speckle produces conversion errors and one of the columns is missing.

commit: https://speckle.xyz/streams/1a9c89d03a/commits/6a6c4b5982
![image](https://user-images.githubusercontent.com/7717434/110622601-98e12680-8193-11eb-83b1-b578bc05fe42.png)

the file:
![image](https://user-images.githubusercontent.com/7717434/110622622-9ed70780-8193-11eb-92f7-ad7e84f0debf.png)

This failure is occurring on a column that doesn't have a baseline (`baseGeometry` is a Point), so creating one is attempted.

```cs
      //make line from point and height
      if (baseLine == null && baseGeometry is Point basePoint)
      {
        var topLevelParam = revitColumn.get_Parameter(BuiltInParameter.FAMILY_TOP_LEVEL_PARAM);
        var elevation = (double)((RevitLevel)ParameterToSpeckle(topLevelParam).value).elevation;
        baseLine = new Line(basePoint, new Point(basePoint.x, basePoint.y, elevation + speckleColumn.topOffset, ModelUnits), ModelUnits);
      }
```

This fails when getting the `elevation` because the `topLevelParam` storage type is `ElementId` (weird?) which is not a handled case in the `ParameterToSpeckle` switch statement. This means `.value` is null and we get a null ref exception and this conversion fails.

**Comment by teocomi** [comment]
If `topLevelParam` is null (which is possible in case the column is `unconnected`) we should instead be taking its `unconnected height` value.  We're doing something similar for walls but the built in parm name might be different (you can use the revit lookup tool to see the correct name).
