### ISSUE TITLE
Enhancement: Integrating material_quantities into the ArchiCAD converter.

### ISSUE THREAD

**Issue by ks-cph** [specklesystems/speckle-sharp#3113]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

ArchiCAD connector

## Is your feature request related to a problem? Please describe.
Quantity extraction of materials is time-consuming, and BIM models often do not provide the info in a standardized way. We have been working on integrating the material_quantities into Speckle. material_quantities include the quantities of each material in an element. So far, the Revit connector is the only connector supporting this feature. As it is a fairly valuable approach, we would appreciate extending the scope of the material_quantities to the ArchiCAD connector. 

## Describe the solution you'd like
Similarly to the Revit connector, the ArchiCAD connector should add the material_quantity information to each element. This would also require to implement the `Objects.Other.Material` element in ArchiCAD. As we have never worked with the ArchiCAD API, we would appreciate support in this matter.

## Describe alternatives you've considered
in Issue #3112, we propose a solution that could partly solve the issue. However, we should still consider converting the materials for purposes beyond rendering (which is the only material information available at the moment.

## Related issues or community discussions
#3112

**Comment by bimgeek** [comment]
Hey @ks-cph ,

Thank you for your report. We will work on adding quantities and user attributes support, so please stay tuned for the next release.

**Comment by bimgeek** [comment]
Hey @ks-cph ,

FYI we have added support for quantities and user attributes in 2.18 release. You can get it from Manager. 

<img width="397" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/51519350/647f3ef6-cdf4-4781-b610-2392afaff5a1">

**Comment by martinromby** [comment]
As of 2.20 this is supported and can be closed @bimgeek
