### ISSUE TITLE
Desktop UI improvements & fixes

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#314]
A few more things came up during our workshop:

- [x] display the version number of the connectors (this is currently being set in the main dll ie `SpeckleConnectorRevit.dll`)
- [x] add Server Name to the account selection pop-up, as with only the e-mail it's not possible to distinguish.
![image](https://user-images.githubusercontent.com/2679513/110648068-4d894100-81b0-11eb-8e6c-fb4c0de0273e.png)
- [x] clear stream stored selection when opening a document that contains streams. This will help prevent accidental user commits.
- [x] When creating a branch, automatically swap to that branch once it's created
- [ ] Commit message experimentation (make it more visible and present!)
- [x] Add Stream By URL
- [x] Add a tooltip to the refresh button as it's not obvious what it does (does it refresh the stream info or the accounts?)

**Comment by izzylys** [comment]
> When creating a branch, automatically swap to that branch once it's created

hmm this is already happening rn. did someone fix this recently?

**Comment by clairekuang** [comment]
Also noticed:
- [ ] update stream commits when opening a file with saved streams (either automatically, or upon UI refresh)

**Comment by teocomi** [comment]
One more:
- [ ] Limit size of stream description (in the future we'll have a short description filed like Github, and that will be used instead)

![image](https://user-images.githubusercontent.com/2679513/110830874-9533c980-8291-11eb-9b0f-074db848af9b.png)

**Comment by teocomi** [comment]
Some of these were addressed in https://github.com/specklesystems/speckle-sharp/pull/321
