### ISSUE TITLE
Connectors: Unify text across the connectors (notifications, errors, tooltips, descriptions, etc)

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#322]
Notifications, error messages, tooltips, etc should use the same language across all the connectors for consistency and clarity. This should probably be done by creating a resource (in Core?) containing all these possible strings which the different connectors can reference. This will keep everything consistent and allow us to change these in all the connectors easily when we do so.

**Comment by AlanRynne** [comment]
One thing we may want to also take into account is trying not to use "platform specific" terms whenever possible, such as `bake` in this case.

![](https://cdn.discordapp.com/attachments/748525435020902480/820972567912382494/Screenshot_2021-03-15_at_11.51.45.png)
