### ISSUE TITLE
SetRelationship (in CommitObjectBuilder) throws "an item with the same key has already been added" exception

### ISSUE THREAD

**Issue by andreaslennartz** [specklesystems/speckle-sharp#3222]
I am currently trying to rebuild the functionality of converting a whole Revit document into speckle objects. 
During the conversion, I got a lot "an item with the same key has already been added" exceptions. 

Specifically, this code throws the exception:

https://github.com/specklesystems/speckle-sharp/blob/9a3e68930367949c15a77370f5c4f83582f05634/Core/Core/Models/CommitObjectBuilder.cs#L74-L97

The logic seems flawed. If the `Converted` dictionary does **not** contain the key, a value will be assigned for this key, else the key and the value are added - shouldn't it be the other way round?
So instead of:
```if (!Converted.ContainsKey(appId))```
the if statement would make more sense to me like this:
```if (Converted.ContainsKey(appId))```

Same for `_nestingInstructions`. 

Let me know if you need more context or more information.

**Comment by JR-Morgan** [comment]
🤔 I think you're right, something's a bit fishy with this if block.

I wonder if we could remove the `ContainsKey` check all together, and simply use `Converted[appId] = conversionResult;`
@connorivy what do you think?

**Comment by andreaslennartz** [comment]
Thanks for looking into this.

Not quite sure if this helps, but after changing the code block to this:
```
if (dict.ContainsKey)
  dict[key] = value;
else 
  dict.Add(key, value)
```
my Revit project which I use for testing is converted much faster as before (because no exceptions are thrown, which added quite a lot of overhead to execution time).  
Also, both parts of the if/else blocks are hit during debugging, so the logic does either add or change values. 
Also, when the method is hit in my tests for the first, the dictionary itself is empty, so assignments won't work until some keys are added. 

But I don't understand what the method is supposed to do at all, or what it's purpose is. Just thought I add this here to support you guys somehow.

**Comment by JR-Morgan** [comment]
If you change your code snippet to just:
```cs
dict[key] = value;
```
with no if check atall, does this still work for you?

**Comment by andreaslennartz** [comment]
@JR-Morgan 
Sorry, my fault. 
I was so used to writing the "if not contains key, then add, else assing" pattern in my own code, that I oversaw that the dictionary already has this build in when you assign a key directly as you proposed. 
You are right, this will also work, sorry for the confusion.

**Comment by JR-Morgan** [comment]
No worries, I think we made the same mistake here.

Would you be comfortable submitting a PR to this repo with the same change?

**Comment by andreaslennartz** [comment]
@JR-Morgan 
Sure, just created a PR for you dev branch.
