### ISSUE TITLE
Support flow for adding accounts that does not reply on Mananger

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#325]
Currently, unless you are a programmer there is no easy way to add accounts and use them with the connectors without relying on Manager.

**Comment by didimitrie** [comment]
To detail the problem a wee bit: to manually set up an account on a local machine, one would need to 
- create an sqlite `Accounts.db` file in `Environment.SpecialFolder.ApplicationData`
- create a table with two columns, `id` and `content`: 

https://github.com/specklesystems/speckle-sharp/blob/456894e1bd8dd465077b71f62cebc9ae36198b66/Core/Core/Transports/SQLite.cs#L89-L94

- insert an serialised account object inside. this is not a per se a complex object: 

https://github.com/specklesystems/speckle-sharp/blob/456894e1bd8dd465077b71f62cebc9ae36198b66/Core/Core/Credentials/Account.cs#L26-L34

Proposed solution: 
- let the account manager read accounts from simple text files containing the necessary fields of an account object in csv/tsv format, from an `%applicationdata%/accounts` folder
