### ISSUE TITLE
feat(archicad): Update connector icon on Mac

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#3269]
## Description
Archicad connector icon under File > Interoperability looks out of place in Mac. Replace it with an speckle cube outline similar to other icons in the same dialog. This should be fairly easy to implement.

## Screenshots
<img width="643" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/51519350/42c81ed3-41f7-455e-a658-572446ae7a30">

**Comment by furtonb** [comment]
Similar icon-related problem on macOS: when you switch between running applications by pressing Cmd+Tab, the Speckle Archicad Connector doesn't have an icon assigned to it. 

I'm running:
- Archicad 27 INT b4060
- Archicad Connector v2.18.3
- OS: macOS Ventura 13.6.4
- HW: M1 Max MBP

Example screenshot:

![speckle_window](https://github.com/specklesystems/speckle-sharp/assets/11893065/b7e7c9a7-d11d-430d-a2b3-055a69d1c986)
