### ISSUE TITLE
Objects: Add interface to distinguish between Geometry and BuiltElems

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#327]
There is no way to know if a `Base` is a BuiltElem or Geometry, I'd suggest adding a `IBuiltElem` interface in **Core** and then implementing it in all our BuiltElems in **Objects**.
This would greatly help with this: https://speckle.community/t/unity-connector-question-about-speckle-data/1222/2
and would let us avoid traversing entire Base objects when not necessary. 

Unfortunately being the interface not available in javascript this would not be usable in the viewer.

**Comment by didimitrie** [comment]
As discussed: it goes in Objects.

**Comment by teocomi** [comment]
We decided for now to just add a `IDisplayMesh` interface to all Objects that have a `displayMesh`, this should be enough to help understand what can be displayed and should not be traversed.
