### ISSUE TITLE
StreamWrapper should inform the user when the URL provided is not valid

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#329]
StreamWrapper should inform the user when the provided URL is malformatted. For instance when `https://my-server.com/streams/1a1fd2f382/branches` is used

**Comment by AlanRynne** [comment]
Nice catch! I added this case to the Grasshopper Exceptions file so we can "test" it. Currently throws this ugly thing:

![Screenshot 2021-03-15 at 10 59 56](https://user-images.githubusercontent.com/2316535/111136198-c1936280-857d-11eb-9162-5878edd8b5db.png)
