### ISSUE TITLE
Annotations get deleted upon receiving data again.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#331]
See the _gif_ for a clearer picture of whats going on.

Offending commit: https://speckle.xyz/streams/119514a3d4/commits/3707f86ae9

How to reproduce:

1. Receive some data un revit (in this case, floors and levels).
2. Create some elevation tags on based on those levels/floors
3. Press the "receive" button again.
4. The elevation tags would disappear.

As far as I'm aware, those elevation tags should stay in the model even after successive data updates.

![2021-03-15 10 32 44](https://user-images.githubusercontent.com/2316535/111132723-f998a680-8579-11eb-8f0e-1a0027d5267c.gif)

**Comment by teocomi** [comment]
Floors do not support being updated, we need to investigate if there are any workarounds.
