### ISSUE TITLE
Receiving duplicated geometry after "undo"

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#332]
May be kind of related to #331, as I only managed to reproduce it starting from the steps of that issue.

See the gifs for a clearer picture of whats going on.

Offending commit: https://speckle.xyz/streams/119514a3d4/commits/3707f86ae9

How to reproduce:

1. Receive some data un revit (in this case, floors and levels).
2. Create some elevation tags on based on those levels/floors
3. Press the "receive" button again.
4. The elevation tags would disappear.

![2021-03-15 10 32 44](https://user-images.githubusercontent.com/2316535/111133380-c1de2e80-857a-11eb-9f48-b65e0c31438b.gif)

5. Press `CTRL+Z` to undo the last step. The elevation tags will appear again.
6. Press receive again.
7. Floors will be duplicated 🤷🏻 

![2021-03-15 10 38 52](https://user-images.githubusercontent.com/2316535/111133429-d1f60e00-857a-11eb-9382-767d8b6a8394.gif)

**Comment by izzylys** [comment]
This is a side effect of the fact that floors have to be deleted and recreated. When you receive, you are creating a new floor with a new id. Undoing the previous action recreates the old floor with the old id which does not exist in the stream, hence this recreated floor is not deleted upon receiving again.
