### ISSUE TITLE
Rhino: develop builtelement ToNative conversions for Revit interop

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#337]
**Test Info**

Connector: Rhino
Testing protocol requirement: receiving geometry
Test Case:  2A, 1C
Test stream link: 
https://latest.speckle.dev/streams/24c3741255/branches/2%20builtelements%20geometry
https://latest.speckle.dev/streams/c544db35f5/branches/1%20standard%20geometry%20%2F%20from%20rhino

**Report**

Currently, Rhino does not support BuiltElements ToNative conversions. This means that base geometry objects that are sent to Revit (Curves, Surfaces, Breps, Meshes) as Model Curves and Direct Shapes cannot be received back into Rhino. Perhaps lower priority for now, but this issue is related to a larger issue around extracting base geometry from BuiltElements (related: #327 ) for full interop.

**Comment by didimitrie** [comment]
Re implementation: add extra check in converter for these elements to see if they have a display mesh, if yes -> output that together with whatever properties we can attach to it from the original object.

**Comment by clairekuang** [comment]
This was actually resolved with PR #363 - ModelCurves are converted as Curves and DirectShapes as meshes
