### ISSUE TITLE
bug(Archicad): Properties of Objects not showing in viewer

### ISSUE THREAD

**Issue by jozseflkiss** [specklesystems/speckle-sharp#3419]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Archicad Connector

## Describe the bug

Properties not showing in the viewer for Archicad Objects

## To Reproduce

1. Place an object element in Archicad
2.  Send it with "Send Properties" and "Send Listing Parameters" turned on
 * <img width="812" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/50739844/9fdbf2e0-1ff0-471e-94a8-f3e63048cca1">
3. Check the result in the viewer, you can not see the properies
 * <img width="907" alt="image" src="https://github.com/specklesystems/speckle-sharp/assets/50739844/ebbedc5e-8911-4f0c-9c14-3b6c789a9451">

## Expected behavior

Properties should be available in the Speckle viewer

### Desktop (please complete the following information):

v2.18.4.
AC26, 27 and both platforms

**Comment by JR-Morgan** [comment]
Confirmed fixed https://latest.speckle.systems/projects/c1faab5c62/models/c8ca2dcbe2
![image](https://github.com/specklesystems/speckle-sharp/assets/45512892/aefd3174-b95b-47c3-8973-f8c4cd3005ec)
