### ISSUE TITLE
Extend Pipe and Structure properties sent from C3D to facilitate mapping in other software (Revit)

### ISSUE THREAD

**Issue by alex-d-richards** [specklesystems/speckle-sharp#3466]
## What package are you referring to?

Civil 3d

## Is your feature request related to a problem? Please describe.

We have been using Speckle to transfer data from C3D and recreating the model in Revit for coordination internally and externally. 

Our intention is to be able to build a native representation in Revit using custom families, pipe systems etc. 
We found the properties exported by default from C3D a little limited and missing key information for this translation.

For example: 

- no network reference
- no indication of structure depth
- etc

We have therefore been using dynamo as a workaround to push the additional properties from C3D to speckle although were finding some barriers to adoption and some pitfalls in the translation of the diaplayMesh. 

However looking at the convertor for AutoCad Civil these additional properties can be added. 

## Describe the solution you'd like

Additional properties added to the base Native to Speckle conversion

## Describe alternatives you've considered

- Using Dynamo for the conversion
- Creating a custom Object Kit with teh additional properties

## Additional context

Default Properties
![Original Object Model](https://github.com/specklesystems/speckle-sharp/assets/69122437/201a1c92-b375-4bb3-ac32-66b4ebd20060)

Additional Properties
![Additional Params](https://github.com/specklesystems/speckle-sharp/assets/69122437/313adcf3-9e37-4408-a1bf-995cc62346d7)

## Related issues or community discussions

Alternative way around though Rvt -> C3d as opposed to C3d -> Rvt 
https://speckle.community/t/revit-family-civil-3d-pipe-network-structure/2928

**Comment by clairekuang** [comment]
Hey @alex-d-richards , could you take a look at [this recent pr](https://github.com/specklesystems/speckle-sharp/pull/3457) that adds `PartData` to pipes and structures? It does contain some of the missing properties you mentioned, but perhaps not all of them. Is the information in `PartData` enough, or do you require all of the properties?

**Comment by alex-d-richards** [comment]
hi @clairekuang thanks for reviewing this. I have pulled a copy the dev branch and from my limited testing so far this looks to provide the parameters that I was expecting. 

Reviewing this same wok flow I do have a few other comments, queries but I think I will add these to the community page later in the week.
