### ISSUE TITLE
Civil3D: Extended pset names overriden while receiving data from Speckle

### ISSUE THREAD

**Issue by bekraft** [specklesystems/speckle-sharp#3597]
Property set names are not handled correctly while sending and receiving data to/from Speckle. They are  sent as internal names and replaced by generic Speckle names on load from Speckle.

To achieve a cross tool communication we need stable and correct pset names.

## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Civil3D Connector Plugin (tested version 2022)

## Describe the bug

- PSet names of extended properties are not submitted correctly while sending using internal names since 2.20.wip
- PSet reflection and names are not handled correclty while receiving (pset names are replaced by generic Speckle names) since 2.19.3 at least.

## To Reproduce

1. Define a custom extended property set in civil 3d.
2. Send the object to Speckle.
3. Receive the object from Speckle.

## Expected behavior

Extended property sets are reassembled correcly after receiving data from Speckle. PSet names are taken as key names to properly reference property data from Speckle.

## Screenshots

(none)

### Desktop (please complete the following information):

- OS: Win 10 (x64), Civil 3D 2022

## Proposed Solution (if any)

- Bugfix https://github.com/il-se/speckle-sharp/tree/bugfix/BIM-20-fixing-pset-name

**Comment by clairekuang** [comment]
Partially fixed (name on send) by : https://github.com/specklesystems/speckle-sharp/pull/3598
