### ISSUE TITLE
Add export without displayValue.

### ISSUE THREAD

**Issue by nickger** [specklesystems/speckle-sharp#3639]
Currently Speckle uses host applications to calculate meshes. 
First, there can be scenarios when people want to extract only alpha-numerical data. 
Second, it is very inconvenient to write a code specifically for each software and keep it updated.
Third, it is a huge time waist and depends on application quality. E.g. Revit sucks.

What we are currently after (and hope it will be implemented in the future in Speckle):
 - we extend geometry kit to cover main surface types from OpenCascade 
 - save data as collections of faces (surfaces with edge curves; curves are fully covered already) 
 -  write a single post-process to calculate Breps and mesh them (if necessary) based on Speckle geometry kit using whole power of OpenCascade. 

Currently in Revit Convertor the method GetElementDisplayValue() is implemented in about 30(!) places. I haven't check other connectors. I presume it could be optimized to quickly turn it off.

**Comment by didimitrie** [comment]
Hi @nickger, we can look at implementing this as a send setting in **Revit** (and maybe other host apps where this would make sense), though it can be a rather counterintuitive for the majority of specklers. 

Regarding meshing breps with opencascade: this is something we've never tried before, but it opens a slippery slope. We currently benefit from not having to mesh things client side/server side and being able to instantly display them! 

I'm going to close this issue, but the first idea - send without display values - is captured in our backlog!

**Comment by nickger** [comment]
Well, currently you mesh things on client's side, moreover, in the host application during sending. This is unnecessary load at least, and for me as developer - huge head ache: if I want to do further geometry processing, I must implement it on client's side as well. Think of exporting BReps as a third export option.

**Comment by didimitrie** [comment]
perhaps we need to understand what you're after better: for us meshing things client side saves a lot of headaches. happy to hear what you're building!
