### ISSUE TITLE
Validate Base dynamic key names

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#37]
### Expected vs. Actual Behavior

You can currently set dynamic props key names to whatever you want them to be, including potentially illegal chars. This is problematic, as there are some caveats that will make things difficult. 

Ie, 
- dots in key names - they nuke postgres jsonb querying. eg: `myCommit["test.the.best.dots"] = etc` should throw an error. 
- too many `@`s. e.g., eg: `myCommit["@@@@@test.the.best.dots"] = etc` - works fine but it's stupid and can cause confusion (@teocomi spotted this)
- slashes in key names? 
- protected fields (e.g., `speckle_type`) 

### Proposed Solution (if any)

Come up with the scenarios that we want to avoid, and implement them as deep as we can in core so we don't need to freak out later! 

There are some that we took care of in 1.0 in the CreateSpeckleObject component, so we could start from there. We also need to investigate other limitations coming from postgres' jsonb column operations this time, as I believe that will be what we'll want to test against.

**Comment by AlanRynne** [comment]
We should track issue #170 along with this one, as whatever is decided there will have to be added/checked here too!
