### ISSUE TITLE
Rhino: Deleting a commit crashes Rhino.

### ISSUE THREAD

**Issue by tsvilans** [specklesystems/speckle-sharp#371]
Deleting a commit while Rhino or Grasshopper is open crashes Rhino.

## Steps:
1. Open Rhino, load a stream
2. Send some stuff around
3. Delete the latest or any earlier commit via Python API (`res = client.commit.delete(stream_id, commit_id)`), i.e. using SpeckleBlender
4. Rhino crashes

**Comment by izzylys** [comment]
Thanks for reporting this Tom! I just merged in a fix for this, so it should be working as expected now. Sorry for the nasty bug!
