### ISSUE TITLE
Revit: Improve `WallByFace` behaviour when creating multiple faces

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#381]
Currently, sending `WallByFace` walls from GH to Revit takes a long time for Revit to actually create the walls, when sending many of them (tested with 600ish and took about 25min)

Not sure it there is anything we can do here, but we should look into optimising the process:

- Finding duplicate surfaces that can use the same family
- Figure out if this can be sped up by parallel tasks? If we're not doing so already.
- Any other ideas....

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
