### ISSUE TITLE
Standardize receive behaviour across connectors using Desktop UI

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#388]
When receiving the same stream multiple times (with changes):

- the Revit connector tries updating previously created elements and deletes elements that have been removed from the stream
- Rhino, Acad, Civil instead always generate new layers with the received geometry

We should consider standardizing this behavior, potentially with a setting on the stream itself.
Something to be discussed!

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
