### ISSUE TITLE
Feat: Add sorting options for streams in DesktopUI

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#397]
From a lovely student of mine:

We should add sorting capabilities to the DesktopUI so that users can easily find and customise the order. Ideally:

- Sort alphabetically
- Sort by last updated
- Sort by "has updates"
- Custom sort (drag and drop)
- Other...

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
