### ISSUE TITLE
Feat Civil3D: scope specific infra conversion requirments

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#404]
- Such as alignemnts etc. 
- TBD: discussion with community

**Comment by didimitrie** [comment]
Updates from @clairekuang's notes: 

> When extracting from Civil, when do we want 2D vs 3D data? A: **3D data.** 

*parameters in italics are civil-specific*

- [ ]  **3D solid** 🚫 ignore

- [ ]  **Surfaces** (different from acad surfaces)**:**
    - [ ]  **TinSurface** (triangulation srf)**:** -> mesh 💚 try to support
    - [ ]  **GridSurface:** surface or mesh; 💚 try to support
    - [ ]  **VolumeSurface**: surface1, surface 2; 🚫 ignore

- [ ]  **Alignment**: name, base curve(acad polyline), *style, label set style, list<point> stations = null* 💚 try to support

- [ ]  **Profile** (vertical alignment): name, alignment, surface or feature line, style
- [ ]  **Subassembly**: 🚫 ignore
- [ ]  **Assembly**: 🚫 ignore
- [ ]  **Corridor**: Alignments, profile, surface, subassemblies (contains 3d geometry), assembly; 🚫 ignore

- [ ]  **Pipe**: name, network, part family, part size filter, base curve, start/endpoint offsets, style, flow direction (bidirection, start/end, slope), flow rate; 💚 try to support as curves with extra metadata

---

Summary: 
- 💚 support alignments, potentially with full built elements schema builder implementation
- 💚 support pipe networks: first step, data extraction (potentially with full built elements schema builder implementation)
- ⌛ surfaces: will require some wider ranging changes, are parked for now, but will not be forgotten

**Comment by clairekuang** [comment]
Creating a new issue for civil3d conversions to close this one out!
