### ISSUE TITLE
Gh Bug: error initializing connector

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#414]
As reported on the forum: https://speckle.community/t/grasshopper-2-0-connector-error/1247/3
Some errors show up and prevent the connector to load properly.

The issue seems to be related to GH in Rhino 7.

**Comment by AlanRynne** [comment]
This one is on-going, I'm waiting on Jeroen to setup a call next week and try to debug it with him.

**Comment by AlanRynne** [comment]
Closing this as it appears the issue has been fixed for now, we can re-open if any other user experiences this.
Many thanks to our community users for the invaluable help!

**Comment by AlanRynne** [comment]
Closing as both users have confirmed they no longer experience the issue! We can re-open if it pops its head again....
