### ISSUE TITLE
Improve surface conversions handling across converters

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#425]
**IDisplayMesh for Surfaces**
Currently `Objects.Geometry.Surface` is not inheriting from `IDisplayMesh`. This so far hasn't caused issues since the main source of surfaces are from Rhino/GH which sends them as breps. However, softwares like Autocad that send surfaces directly will not show in the viewer
- [ ] Add `IDisplayMesh` to `Objects.Geometry.Surface`
- [ ] Add a boolean argument in `SurfaceToSpeckle()` methods to determine whether a surface should be sent with a display mesh
- [ ] When sending Breps to Speckle, make sure the boolean is set to false so surface display meshes are not created

**Surface vs Brep**
Because Rhino surfaces are converted as `Objects.Geometry.Brep`, this could cause issues for interop with softwares that send surfaces as `Objects.Geometry.Surface`: eg a nurbsurface from Autocad sent to Rhino would be sent back as a brep, which is currently an unsupported conversion.
- [ ] Add a Brep.IsSurface() check in the Rhino converter and convert as surface if true

**Knot convention clarification**
This is the same issue we had with Nurbscurves: Rhino uses a unique convention of degree - 1 (instead of degree +1 like most other apps) for curve knots. Surface u and v knots should be switched to the standard convention of degree + 1: this will require surface conversion updates across all converters
- [ ] Add comment in `Objects.Geometry.Surface` to clarify knot convention
- [ ] Rhino: Remove knots in `SurfaceToNative()` and add knots in `SurfaceToSpeckle()` 
- [ ] Other converters: Remove knot adjustments in all surface conversion methods

**Comment by clairekuang** [comment]
@didimitrie @teocomi @AlanRynne discussion on these issues welcome!

**Comment by teocomi** [comment]
Would it be possible to send Breps from Autocad instead of Surfaces?
My understanding here is limited, but if a Brep is a collection of (trimmed and untrimmed) surfaces that should be possible and could make the workflow simpler > we just standardize on the Rhino approach.

But I'll let the resident experts on this have their say :)
