### ISSUE TITLE
Revit: Allow updates from origin file

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#450]
Objects are only cached on receive, meaning objects cannot be updated in the origin file. Eg if I create and send a pipe layout to a stream, someone updates the pipework, then I receive the stream back in that original file, the corresponding Revit elements are not picked up and duplicate elements are created.

Some caching mechanism should be in place to allow the file that originally created the elements to also receive updates to those elements (instead of creating new elements on top).

A slightly related point that only affects Dynamo (since Revit only allows one receiver per stream):
Cache is not shared between receivers, so if you receive data from the same stream from two places, you will receive duplicate objects.

**Comment by teocomi** [comment]
I looked into this and sounds link a quick fix, the assumption though, would be that the user always wants to *update* local elements when the receiving ones have the same ID (so most likely would mean applying old changes).

**Comment by teocomi** [comment]
Update: https://speckle.community/t/revit-api-compare-differences/1324?u=teocomi

**Comment by teocomi** [comment]
![revit-update](https://user-images.githubusercontent.com/2679513/117180157-c7fac980-adcb-11eb-9db5-db306e5455f3.gif)
