### ISSUE TITLE
Rhino: Sending one object does not create "layers" 

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#454]
When sending a single object from Rhino, it seems that the connector does not create a base object with the layer structure. This causes problems down the line, e.g. receiving said commit in grasshopper and "expanding" it - there's nothing to expand. 

 It's a curious exception, but worth looking into!

**Comment by teocomi** [comment]
I think connectors should handle such case, so it's more of a GH issue than Rhino, no?
From Dynamo, if you're sending 1 single object/element it's not nested at all. Same might happen when using the pyhton/c# apis in a scripting environment....

**Comment by clairekuang** [comment]
Tested this and couldn't reproduce - single objects are being sent in a base object with the correct layer container
