### ISSUE TITLE
Rvt: Brep conversions failing again in complex cases

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#470]
As can be seen in the screenshot, receiving the Standard Geometry in Revit fails for many of the complex `breps` which (for the most part) where coming in nicely before.

This may be due to some alignment mismatch from the time we made the switch to `rhino3dm` for brep serialization?

<img width="1149" alt="Screenshot 2021-04-30 at 18 48 42" src="https://user-images.githubusercontent.com/2316535/116730359-b50d8100-a9e8-11eb-9465-b30d0bc577ea.png">

I took the liberty to assign myself to this

**Comment by didimitrie** [comment]
It might be as well because old test breps haven't been updated with new format! PS: we didn't end up using rhino3dm unfortunately - limitations re curve rebuilding on edges :/

**Comment by AlanRynne** [comment]
Ok I'll dig into this! I don't think its because of the test Breps, I did a full test sending from Rhino and receiving in Revit and the result is the screenshot above 👆🏻 .

**Comment by AlanRynne** [comment]
Merged in Rhino-Rhino and partial Rhino-Revit fixes.

All the conversions that were failing in Revit was due to unsupported knot multiplicities, but it's something we don't really have much control about, since some curves cannot be represented any other way.
