### ISSUE TITLE
GH: Brep conversion error

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#478]
Hi guys.

I have a brep fail conversion happening. It's a consistent error since it happens on all 280 volumes.

![image](https://user-images.githubusercontent.com/64929000/117314059-b5919600-ae86-11eb-9384-b145ee3d27db.png)

my master is at this commit 9ddb1fbb061cbabeb5a86109a6be8d193b948691
I attach a ghp with an internalized brep for you to test.

[210506_Mule_Bug.zip](https://github.com/specklesystems/speckle-sharp/files/6435299/210506_Mule_Bug.zip)

**Comment by AlanRynne** [comment]
Hi @iltabe, we're aware of an issue regarding Rhino brep export that we just fixed yesterday, but isn't yet merged. I'm going to do some final checks and will merge it in. If you wan't to test out the fix, you can pull the latest commit from the `alan/brep-fixes` branch

https://github.com/specklesystems/speckle-sharp/tree/alan/brep-fixes

**Comment by iltabe** [comment]
Thanks @AlanRynne I will have a look.

In the meanwhile another problem came up, still with breps. It took me 3h to understand it was speckle! arrghh
![image](https://user-images.githubusercontent.com/64929000/117343806-f4cedf80-aea4-11eb-8dcd-2c2ac75b72fd.png)
The brep is not by both planes.
[210506_Mule_Bug02.zip](https://github.com/specklesystems/speckle-sharp/files/6436712/210506_Mule_Bug02.zip)

**Comment by iltabe** [comment]
But the Sender is sending nothing! aaaah

**Comment by didimitrie** [comment]
I've just given bug_01 a shot:

![image](https://user-images.githubusercontent.com/7696515/117347831-6c9b0b00-aea1-11eb-84f9-602898f74e37.png)

It seems to be working fine! I've tested against several units (meters, feet), and managed to [send ](https://speckle.xyz/streams/e640af6af3/commits/e225943429) and receive! 

Some possible issues: clean and rebuild the entire solution just in case...

**Comment by iltabe** [comment]
@didimitrie did you try to send the one that comes out the selected component?

**Comment by didimitrie** [comment]
Just did - results: 
![image](https://user-images.githubusercontent.com/7696515/117348906-b506f880-aea2-11eb-94f9-c4bd4f4590bd.png)

https://speckle.xyz/streams/e640af6af3/commits/edc9e16ab2

There's some problems (hehe) with the created structure for a reason or another, but i suspect this is due to some unstable changes we discussed with @AlanRynne this morning...

**Comment by iltabe** [comment]
Apparently I have a problem to push a single wrapped objects.
Sorry If I notch, but I have a deadline...

**Comment by didimitrie** [comment]
To join the video meeting, click this link: https://meet.google.com/bvi-vuuq-czn
Otherwise, to join by phone, dial +44 20 3956 7532 and enter this PIN: 386 625 777#
To view more phone numbers, click this link: https://tel.meet/bvi-vuuq-czn?hs=5

**Comment by iltabe** [comment]
Urra! 
Just delivered the model! :) Thanks guys!
@didimitrie I've discovered the object that cause the web viewer to fail: https://speckle.xyz/streams/0355f60d50/objects/4e8f0b403a0e2fa0b6680f552801489a

**Comment by didimitrie** [comment]
Okay, I've raised a new issue for the viewer: https://github.com/specklesystems/speckle-server/issues/231. Thanks for narrowing it down to the main suspect object! I'll close this one now, as it's been "guerrila" debugged. 

Fixes will propagate to releases soon!
