### ISSUE TITLE
Autocad: receive breps and surfaces as mesh in lieu of not supporting direct conversion

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#493]
Currently Autocad doesn't support ToNative surface and brep conversion - receive displaymesh if available instead.
- [x] also fix polycurve segment order issue when sending manually imported rhino dwgs

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
