### ISSUE TITLE
Rhino: Can not install Rhino connector

### ISSUE THREAD

**Issue by eirannejad** [specklesystems/speckle-sharp#499]
I have Rhino 7 and Rhino 8 WIP installed on my machine. The Speckle manager app fails to install Rhino connector. Restarted the app and it did not help

![Screen Shot 2021-05-14 at 9 16 16 AM](https://user-images.githubusercontent.com/8197916/118299070-25aaa800-b495-11eb-8bd5-f8b9d7e621fb.png)

**Comment by eirannejad** [comment]
It started working after a while for no known reason. This might not be an issue. Not sure what fixed it though

**Comment by eirannejad** [comment]
Closing this for now since it started working.

**Comment by teocomi** [comment]
This could have been due to a process running in the background locking one of our dlls. Currently, we're only looking for processes containing "rhino" or "grasshopper" in their names. Let us know if we should be checking for anything else!
