### ISSUE TITLE
Speckle Manager signs out after installing Revit connector

### ISSUE THREAD

**Issue by eirannejad** [specklesystems/speckle-sharp#500]
Used Speckle Manager to install Revit connector. It signed me out after the installation and I had to go sign in again and re-approve the app using google sign on.

**Comment by eirannejad** [comment]
This also started working when installing Grasshopper and Rhino connectors. I can see it logs out and logs back in automatically. The first time it failed to log back in though. Not sure why.

**Comment by eirannejad** [comment]
Closing this for now since it started working.

**Comment by teocomi** [comment]
It's a small glitch when installing connectors, we've fixed it and will be shipped in the next manager release :)
Thanks for reporting it!
