### ISSUE TITLE
Revit: Committing changes from Imperial model fails

### ISSUE THREAD

**Issue by eirannejad** [specklesystems/speckle-sharp#501]
Revit 2020

[SpeckleTest_V20.rvt.zip](https://github.com/specklesystems/speckle-sharp/files/6479995/SpeckleTest_V20.rvt.zip)

![Screen Shot 2021-05-14 at 9 21 34 AM](https://user-images.githubusercontent.com/8197916/118299743-fc3e4c00-b495-11eb-9234-96895cbd1ab0.png)

**Comment by didimitrie** [comment]
Is this by any chance **fractional feet**?

**Comment by didimitrie** [comment]
sorry, was too jumpy. it is, and unfortunately it's a known problem (see https://github.com/specklesystems/speckle-sharp/issues/482). we'll fix asap!

**Comment by eirannejad** [comment]
Same as #482
