### ISSUE TITLE
Dynamo Connector Testing Failures

### ISSUE THREAD

**Issue by OliverEGreen** [specklesystems/speckle-sharp#507]
A few bugs I noticed while testing the latest Dynamo (v2.6.1) Connector beta in Revit (v2021.1.3).

1. Connected to the [RevitTestStream standard geometry/filters branch](https://latest.speckle.dev/streams/c544db35f5/branches/1%20standard%20geometry%20%2F%20filters) , used Receive node to retrieve the data, got "Stream is Invalid" message on the node. No data coming through.

2. Connected to the [AutoCADTestStream on the standard geometry branch](https://latest.speckle.dev/streams/3ed8357f29/branches/1%20standard). Able to retrieve data ok but unable to send data back to another stream. I noticed ApplicationID is null - maybe something to do with this?

![image](https://user-images.githubusercontent.com/29973601/118516517-49d4e600-b72e-11eb-8cc0-25021412e2d1.png)

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
