### ISSUE TITLE
Extend Speckle Object not working with SchemaBuilder classes

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#518]
To be investigated.

Details: https://speckle.community/t/grasshopper-custom-properties-to-revit-object/1362

**Comment by AlanRynne** [comment]
Several issues are at play here, but I managed to pinpoint the `Create Schema Object` issue when adding new keys.

https://github.com/specklesystems/speckle-sharp/blob/56259e7ec9024a8bc126cf9944018154823eb00a/ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs#L268

If you add custom keys, the parameter list is bigger than the cParams, so we get out of range exceptions.

The `Extend Speckle Object` does work fine for Schema objects, but it seems the `Send` node gets stuck when handling one of these.

**Comment by AlanRynne** [comment]
Merged in #522!
