### ISSUE TITLE
Receiving + Sending object issue

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-sharp#526]
**Test code:**

```
            String test_strean = "07428c1cc8";
            String test_obj = "89b5968820b9e0ae0e44cdfd5e7891fa";

            var account = Speckle.Core.Credentials.AccountManager.GetDefaultAccount();
            var transport = new ServerTransport(account, test_strean);
            var destinationTransport = new ServerTransport(account, "853cf73be1");

            var obj = await Operations.Receive(test_obj, remoteTransport: transport);

            var objectId = await Operations.Send(obj, new List<ITransport>() { destinationTransport } );

            var client = new Client(account);
            var commitId = await client.CommitCreate(new CommitCreateInput()
            {
                streamId = destinationTransport.StreamId,
                branchName = "main",
                objectId = objectId,
                message = "test"
            });
```

**Links to streams:**
Source stream: https://speckle.xyz/streams/07428c1cc8
Destination stream: https://speckle.xyz/streams/853cf73be1

**Expected behaviour:**
Destination stream to contain the same object as the source stream

**Current behaviour:**
- The viewer displays the warning `No displayable objects found in object 2cdc8eb613f360d255ae4e22e6ba6537.`
- The root object has `452` children in the destination stream, and `462` children in the source stream

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
