### ISSUE TITLE
GQL Api Calls Cleanup - StreamGet breakdown

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#53]
### Expected vs. Actual Behavior

It's a bit messy at the moment! The `StreamGet` query returns too many things, and at the same time not enough things - or some things that are needed are not there yet 🙃

Where this started from: currently, to get the latest commit in a stream, regardless of branch, i have to search through all the branches returned by the original `StreamGet`, and then dig inside all of their commits. There's a different field in the schema, the stream's commits, that... just returns the latest commits. 

### Proposed Solution (if any)

I propose we break this down a bit, and add a few extra calls that will be more on point. 

- [ ] StreamGet: gets the stream basic info, total branches count, and total commit count (basically the current query, sans the branches part, or, at least without the branches.commits part)
- [x] (collection query) StreamGetCommits: gets the stream's commits. I need this to easily check which is the latest commit in the case of stream bound receivers. 
- [x] (collection query)  StreamGetBranches: the current branches subquery, more or less
- [x] (item query) StreamGetBranch - gets the branch as it is now.
- [x] (item query) CommitGet - gets the full info of a specific commit (already implemented) 

#### Optional: Affected Projects

It's an open questions for all the connector implementations!

**Comment by izzylys** [comment]
@didimitrie quick question: what's the reasoning for naming `StreamGetBranch` and `CommitGet` differently? would it not be more user friendly for them to have a similar naming convention (eg either `StreamGetBranch` & `StreamGetCommit` or `BranchGet` & `CommitGet`)?

**Comment by didimitrie** [comment]
No reason, just sloppy code. Pick the easiest way forward (or the one you prefer most 😎 ) and 🚀
