### ISSUE TITLE
Revit 2022: The current Unit System is unsupported.

### ISSUE THREAD

**Issue by vinnividivicci** [specklesystems/speckle-sharp#531]
Hello,

In Revit 2022, I select 1 Air Terminal, hit send and I get this:
![image](https://user-images.githubusercontent.com/591242/119892199-e43fe100-bf07-11eb-99f9-366554ec7073.png)

Is Revit 2022 fully supported yet? I ask because Revit 2022 changed the units system in the API again...

**Comment by vinnividivicci** [comment]
May be linked to this: https://github.com/specklesystems/speckle-sharp/issues/482 and this: https://speckle.community/t/support-feet-and-fractional-inches-units-in-revit/1344/3

**Comment by vinnividivicci** [comment]
Switching the project to Decimal Feet temporarily solves the issue so it does seem like the same problem as #482 . Looking forward to that update 😃

**Comment by teocomi** [comment]
Hi @vinnividivicci this has been fixed already and will be included in the next release, due in a few days!
Thanks for the feedback :)
