### ISSUE TITLE
Getting specific commits from a branch

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#533]
Coming out from a convo with @aussieBIMguru: 

"latest is usually what wed want, but might be handy to be able to draw on versions prior, maybe indexing backwards from latest so current as 0, then -1,-2,-3. Mainly just so a user has an un/redo or the ability to grab data from x commits prior". 

This would mean some extra legwork in the stream wrapper class to allow for urls that are shaped like `stream/{streamId}/branch/{branchName}/{offsetBackwards}`, where `offsetBackwards` can be 0 for the latest, -1 for one prior, -n for n prior commits. 

Why? Less context switching when in full on power mode inside grasshopper/dynamo and wanting to grab/look at previous versions.

**Comment by teocomi** [comment]
Another solution could be implementing this: https://github.com/specklesystems/speckle-sharp/issues/479
Specifically, the addition of a node to list the commits of a branch/stream as it would easily allow to specify which "offset" commit to pick and receive

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
