### ISSUE TITLE
Revit: block scaling issue when converting between imperial/metric

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#538]
Due to using the default metric template for generic models, blocks coming in imperial units are not scaled correctly

**Comment by teocomi** [comment]
Good find! When addressing this we should also add generic model rfa for the various revit versions we support

**Comment by clairekuang** [comment]
Determined that the incorrectly scaled blocks were coming from Rhino, when blocks created in one unit system do not have their props updated when the user converts to a different unit system. Closing this with an update in the docs for now, may reopen later if there's a way to address this via rhino api
