### ISSUE TITLE
Rhino: Downgrade required Grasshopper and RhinoCommon versions to 6.28.20199.17141

### ISSUE THREAD

**Issue by tsvilans** [specklesystems/speckle-sharp#541]
Hi,
Using the latest RhinoCommon and Grasshopper versions causes problems for institutional Rhino installations that aren't completely up-to-date. Compiling `GrasshopperAsyncComponent` and `ConnectorGrasshopper` with Grasshopper and RhinoCommon version `6.28.20199.17141` doesn't seem to cause any issues and would help with broader compatibility for those of us with slower update cycles :)

**Comment by teocomi** [comment]
I don't see blockers to this, it's been raised before too!

**Comment by AlanRynne** [comment]
On the way to get this merged today! Should be out in the next release
