### ISSUE TITLE
Investigate support for Dynamo Solids

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#546]
Famous last words: would it be easy to support sending solids out as meshes from Dynamo? See this [conversation on linkedin](https://www.linkedin.com/feed/update/urn:li:activity:6806432782181638145?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6806432782181638145%2C6806463034144407552%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6806432782181638145%2C6807080743672573952%29) for reference. 

![image](https://user-images.githubusercontent.com/7696515/120922554-c4f04300-c6c1-11eb-9e10-128e148ded3d.png)
(thanks to Søren Villadsen for the image)

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.

**Comment by teocomi** [comment]
This one just came in from the forum: https://speckle.community/t/cant-visualize-dynamo-solids-in-the-viewer/2075/7
Up to @AlanRynne if we should re-open it!
