### ISSUE TITLE
Create Speckle Object Optional Input Parameter Error 

### ISSUE THREAD

**Issue by haitheredavid** [specklesystems/speckle-sharp#580]
Discovered an issue with the **CreateSpeckleObject** node potentially not using the `Optional` input parameter correctly. When I passed a `Base`  object created from that node that contained an empty `Optional` parameter, the conversion process that happens in the **Sender** node gets stuck on conversion process. 

To replicate:
- Use **CreateSpeckleObject** and set an input parameter as `Optional` 
- Leave optional parameter empty 
- Pass created object into sender node and try sending to stream, it should throw an error saying that there is empty data trying to be converted

**Comment by AlanRynne** [comment]
oh! Thanks David! I'll check it out on Monday, it seems like the sender is swallowing the error and not resetting properly. Should be a quick fix! :)

**Comment by AlanRynne** [comment]
Hey @haitheredavid! Just closed this a minute ago. If you're building your own connectors, you can pull the latest changes in `main` and build the GH one. The sender should no longer get stuck (plus if there's any problem, it will properly display the message).

If you're using the released version of the connectors, you'll see this in the next release.

Thanks for reporting this! 🙌🏼 ⭐️

**Comment by haitheredavid** [comment]
@AlanRynne woot woot! got the update 🥇  thanks for the ping 👍🏻
