### ISSUE TITLE
Revit: Overlapping lines warning not getting swallowed by error eater

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#590]
All of these popups should be om nom nomed and resolved by the error eater, but this one seems to have slipped thorough.

![the offending warning](https://user-images.githubusercontent.com/7717434/123838026-6b1b1b80-d903-11eb-966c-010420440107.png)

Occurs when receiving std geometry from the Rhino Test Stream.

**Comment by didimitrie** [comment]
1h task: if it's solved in 1h, close this issue, if not, close it anyway 😎
