### ISSUE TITLE
GH: Receiver does not receive the desired commit

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#603]
Hi!

I'm trying to receive a specific commit, but the ghp receiver component always get me another commit.
![image](https://user-images.githubusercontent.com/64929000/124735059-f9039180-df15-11eb-8308-84559ba22449.png)

This is the commit I would like to get:
`https://speckle.xyz/streams/0355f60d50/commits/13465df9c5`
and this is the one I get (actually the output object is empty...)
`https://speckle.xyz/streams/0355f60d50/commits/0579d631cf`
which is the last commit in the `master` branch.

You should have the access to the project, in case it's needed.
The workaround is to grab the wrapped object url inside the commit. That works.

I'm a bit behind with master, since it's stable and I'm at the end of the project... So it might be that the problem is solved already. In case can you let me know?
I'm at `2.1.19-beta`
Thanks! <3

**Comment by didimitrie** [comment]
afaik, yep - @AlanRynne fixed this in a previous release. He'll follow up with the specific commit (we know you're building your own!).

**Comment by AlanRynne** [comment]
Correct! It wasn't fixed long ago though... You can find the code changes in this PR, in case you're not in the latest version:

https://github.com/specklesystems/speckle-sharp/pull/595/commits/f92afd690178f180772cf2d63df3a0020fcbb263

**Comment by iltabe** [comment]
Thanks guys!
