### ISSUE TITLE
Desktop UI Usability Problems (Pinning)

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#604]
I don't think pinning in the current implementation works. Some quips: 
- If i minimize the main window (eg. rhino), why does it still stay on top? I'm obvs not going to use speckle rhino if i minized rhino. 
- Alt-tabbing to Rhino doesn't bring Speckle back up, I need to manually un-minize it (or alt-tab again to show it up)
- If pinned, it ALWAYS stays on top, regardless of wether i switch to a different software. As I write, my browser window is 1/3rd covered by Speckle's Desktop UI. 

A quick vid to flex Github's CDN: 

https://user-images.githubusercontent.com/7696515/124750773-c493d380-df1d-11eb-8216-4e485b0ade46.mp4

I know some people hate the way the Gh window behaves, but honestly - this is a wee bit worse. It triggers some deep resentful feelings towards Speckle in me (e.g., "can u pls leave me do my rhino tut imgs in affinity now").  

![image](https://user-images.githubusercontent.com/7696515/124751545-a8446680-df1e-11eb-94b7-54ab8ad53d25.png)

Bernie seems to propose a solution. The code is there, in some past commits.

**Comment by izzylys** [comment]
i'll do dis for u

![ok dude](https://media.giphy.com/media/XAahcVQAyGeBdDKNFO/giphy.gif)
