### ISSUE TITLE
Revit: issue with displaymesh conversions inside generic family document

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#608]
Noticed when trying to convert blocks with breps from rhino into revit, which does so in a generic model family document. These brep meshes convert fine when not sent as a block.

Breps that correctly fall back to display mesh conversion fail when being converted in the family context, where the tesselated shape builder fails to build the mesh:

[https://speckle.xyz/streams/5dfbeb49c9/commits/22e9c409cc](https://speckle.xyz/streams/5dfbeb49c9/commits/22e9c409cc)

Stack:
TessellatedShapeBuilder failed to build the requested geometry.
   at Autodesk.Revit.DB.TessellatedShapeBuilder.Build()
   at Objects.Converter.Revit.ConverterRevit.MeshToNative(Mesh mesh, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback)

**Comment by didimitrie** [comment]
We're tempted to park this issue, unless it's not an edge case! Can we reproduce with more mesh types?

**Comment by clairekuang** [comment]
I've tried this with a few different breps, they all fail on displaymesh conversion :(

**Comment by izzylys** [comment]
Also affects blocks with more complex mesh geometry eg from SketchUp

**Comment by izzylys** [comment]
I just tried receiving the geo outside of blocks but from within a family doc and it does not work. All this geo does get received fine in a project doc. I don't know enough about this to guess what the issue is, but maybe should we consider falling back to non-blocks? Like if the `BlockToNative` mesh conversion fails, create a direct shape that isn't a block for each block instance?

**Comment by clairekuang** [comment]
Conclusion from bloq squad meeting this morning: **use groups instead of generic model families** for block conversions.
Couldn't figure out why TessellatedShapeBuilder.Build() was failing on meshes inside the family context, and Revit groups function more or less like blocks.
