### ISSUE TITLE
DesktopUI: Feedback / comments submit directly from the UI

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#609]
- make it as easy as poss to submit stuff
- can attach errors, warnings, suid, and hook up to sentry to make it easier for us to investigate

**Comment by izzylys** [comment]
@teocomi was thinking something a lot simpler - just a popup message box that you can submit comments/questions/feedback that'll just send us a msg w it (poss via sentry a la @AlanRynne's suggestion). however, am open to exploring a richer solution if we think we need it...thoughs?

**Comment by teocomi** [comment]
So, went for the lazy option of adding a button that opens the forum Help section! We can keep something like fider good for later, but now it'd just add an additional system to manage and fragmentation ;)
