### ISSUE TITLE
GH: Run T4 Templates on every build 

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#618]
It would be good to run our T4 templates on very build, or at least during CI. This would help onboard new developers working on Objects, and would prevent us from forgetting to run them before a release.

See some convos here: https://stackoverflow.com/questions/1646580/get-visual-studio-to-run-a-t4-template-on-every-build

**Note: currently I couldn't get them to run on VS, they only worked in Rider.**

**Comment by AlanRynne** [comment]
Gone around in circles with this for a day this week with no success. Current problem is that:
- When i manage to make it work in the command line it breaks in Rider
- It never actually works in VS, no matter what I try.
- We have a weird circular dependency between the connector project and the t4 template that forces me to do a "double-build" to ensure we'll always have the latest changes everywhere.
    - `ConnectorGrasshopper` contains a class called `CSOUtils` which is required to do reflection on the `T4` template too.

## Proposed solution

I kinda ran out of options here. Only solution I can find is to extract `CSOUtils` into its own project, that we can then build before `ConnectorGrasshopper`. This ensures that the `dll` we need to use in the `T4` template exists, and should compile properly either using the `t4 cli` or passing the `/p:TransformAll` parameter in MSBuild

**Comment by teocomi** [comment]
So it turns out that the t4 fails in VS 2019 since it's only 32 bit and its t4 processor can't import Core. Installing VS 2022 (pre), the template runs without issues.
