### ISSUE TITLE
"Object" Class conflicts with ES methods

### ISSUE THREAD

**Issue by barisbs** [specklesystems/speckle-sharp#628]
Hi everyone,

"Object" class defined in namespace Speckle.Core.Api conflicts with ES  *Object**.defineproperty(exports, "__esmodule", { value: true });   and causes circular dependency problem.

You can reproduce the issue by generating a typescript client which contains an endpoint with stream response(which contains "Object" as a property" and by using following compiler options in tsc:

```
"compilerOptions": {
    "strict": false,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es6",
     ....
```
 If you try to import your typescript client in another typescript file or any vue component.
 
  You will get ES reference error :
  
 Cannot access 'X' before initialization in following line:
 
` **Object**.defineproperty(exports, "__esmodule", { value: true }); `
 
 I renamed "Object" class as "SpeckleObject" to solve issue locally.

**Comment by teocomi** [comment]
Hey @barisbs thanks for this!
I'm not a typescript expert so I have a couple of questions for now until the rest of the team will back me up:
- we don't have a `Speckle.Core.Api.Object` class definition, we do have an `Objects` namespace (notice the **s**), but that's outside Core. So I'm not sure where that error is originating from! Maybe It's somehow referring to the C# `Object` type?
- could you give us a bit more context around what you're building? I'd help us understand how to better improve our codebase and SDks

Thanks!

**Comment by barisbs** [comment]
Hey @teocomi 

> * we don't have a `Speckle.Core.Api.Object` class definition, we do have an `Objects` namespace (notice the **s**), but that's outside Core. So I'm not sure where that error is originating from! 

Actually you have in .NET SDK:

https://github.com/specklesystems/speckle-sharp/blob/master/Core/Core/Api/GraphQL/Models.cs line 171

We have our own ASP .Net Core Server for leaDE on the front of Speckle server and some of endpoints produces some response types like `Stream` which has `Object `class (line 171)  as a property:

Please see https://github.com/specklesystems/speckle-sharp/blob/master/Core/Core/Api/GraphQL/Models.cs line 115.

We have also a Vue application and we generate a typescript client from swagger definition of our ASP. Net Core Server which generates also this "Object" class. Compiled js defines `export` in the first line of the files as below:

`Object`.defineproperty(exports, "__esmodule", { value: true });`

 So the browser can't understand the difference between js `Object` and speckle `Object` and throws an error on the first line of the files as above and means that we may not access `Object` which is not initialized yet. 

We thank you :)

**Comment by teocomi** [comment]
Gotcha, I missed that!
I think it's very sensible to rename it, it's should be a minor change on our side and it'd remove a potential confusion in C#-lang as well. I'll discuss it internally and get back to you!

**Comment by teocomi** [comment]
Fixed! If you're relying on our nugets, we'll publish new ones tomorrow or on monday.
Thanks for the report!
