### ISSUE TITLE
Migrate `master` to `main`

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#632]
We're tripping each other when switching from web to sharp :D Bonus gifs:

![GUVi5bCixZ](https://user-images.githubusercontent.com/7696515/126621486-8cf65224-85a8-4454-bd93-b3de423a7bd1.gif)

**Comment by didimitrie** [comment]
Note: coordinate with @teocomi and @AlanRynne re CI integrations (famous last words from teo: "find and replace master in the yaml files with main")

**Comment by izzylys** [comment]
done & dusted - ci is tag based, so no need to update any ci files 😎

added to changelog as well. ppl just needa run the following the update local refs 

```shell
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
