### ISSUE TITLE
Allow for disabling automatic kit loading in Core

### ISSUE THREAD

**Issue by barisbs** [specklesystems/speckle-sharp#642]
Hello everyone,

I have docker container of the speckle server running locally. For the test purposes, I had to install Revit connector also which installs converters and "Objects.dll" in the following path 

`%AppData%\Roaming\Speckle\Kits\Objects`

There is another folder in same directory which contains also "Objects.dll"

`AppData\Roaming\Speckle\Kits\Speckle.Objects`

If I use .NET SDK in our  .net core server, I get an System.IO.FileLoadException here

[KitManager.cs](https://github.com/specklesystems/speckle-sharp/blob/main/Core/Core/Kits/KitManager.cs) line 169.

If I delete  `%AppData%\Roaming\Speckle\Kits\Objects`, which is needed for Revit connector, it works.

Actually the assembly should be loaded from `%AppData%\Roaming\Speckle\Kits\Speckle.Objects`, but in the method, all assemblies in `%AppData%\Roaming\Speckle\Kits` folder and in its subfolders are loaded. 

The assembly versions are different.  

Is there a way to use both Revit connector and .NET SDK at the same time?

Cheers
Baris

**Comment by didimitrie** [comment]
> Actually the assembly should be loaded from %AppData%\Roaming\Speckle\Kits\Speckle.Objects

The place for kits is actually in the other folder, namely `%AppData%\Roaming\Speckle\Kits\Objects`! I think the error you're getting might be coming from you trying to load the same assembly, from two different origins, in the same app domain. 

Do you have a direct reference to the Objects kit inside your .NET Core server project?

**Comment by barisbs** [comment]
Hey Dimitrie,

Yes. As you said, we had a direct reference the Objects assembly, since we are using "Mesh" object. However, I have replaced the reference with nuget packages and the problem has been solved.

But I get NullReferenceException now, if I send objects from Speckle Revit connector and try to get commit in the subscription handler in our .net Core server. 

**Commit Info:**
![commit](https://user-images.githubusercontent.com/86973814/127219721-6ddc208a-0d05-4ecf-b6d5-f53c0ed2e335.JPG)

**Referenced object id of commit**
![image](https://user-images.githubusercontent.com/86973814/127219641-c452884a-a327-481a-928a-0b5245a783a2.png)

**Exception**
![nullReference](https://user-images.githubusercontent.com/86973814/127219812-a74e68b9-c322-4e84-9591-163906414749.JPG)

Client.Account is server:admin

The assembly versions of Objects in the nuget package and in Revit connector are different. The version %AppData%\Roaming\Speckle\Kits\Objects\Objects.dll is not same with the nuget package as well. Maybe that could be the reason?

**Comment by didimitrie** [comment]
It's quite difficult to debug locally two applications at the same time :/ Could you dig in the exception and show us a bit more where it happens? (e.g. callstack)

> EDIT: The problem occurs if we reference Speckle.Objects and Speckle.Core in same project. We would probably extract the display meshes by using dynamic objects to solve issue.

This smells of dll hell, but not entirely sure. You could force the kit manager to initialise from a specific location during debugging, but unsure wether this would help. 

We could schedule a quick 15 min call if you want so we can click in that exception and figure out if there's any way around this - let us know by email!

**Comment by didimitrie** [comment]
closing as there's no new updates :)

**Comment by didimitrie** [comment]
Notes: this resurfaced again in the forum, and a solution/workaround is explained there: https://speckle.community/t/net-api-object-losing-its-viewmodel/2345/8?u=dimitrie

**Comment by didimitrie** [comment]
As per the discussion in the forum, it would be great if we had a way to disable automatic kit loading in Core. This is useful in contexts where `Objects.dll` and/or other kits are referenced programatically (e.g., via nuget) and Core doesn't need to swoop in any potentially local kits.

**Comment by AlanRynne** [comment]
Hey @barisbs! I'm closing this as stale but let us know if you still have this issue and we'll be happy to re-open it
