### ISSUE TITLE
GH: align receive node output  

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#643]
When receiving a commit with objects that are all supported, the receive node outputs a list of converted geometry. When receiving a commit with unsupported conversions, the receive node outputs a base.
![4GhIleNNeU](https://user-images.githubusercontent.com/16748799/127105026-ef1b12a4-19bc-42da-ab78-5959bfe3d167.png)

Not sure if this behavior was by design, but it is confusing

**Comment by AlanRynne** [comment]
So for a bit of context (mostly for future me...):

The main reason for this difference is that, right now, any information sent from `GH` or `Dynamo` will be converted to a set of nested lists. These nested lists are assigned to the `data` property of the object referenced in the commit.

To make life easier for GH<->GH users (and Dyn<->Dyn / Gh<->Dyn) we **unwrap** that data property if the object has only one property and that property is called `data`. This is save the user from an extra `Expand Speckle Object` node.

Granted, this makes it weird if you send data to the same stream/branch from different connectors, as the gh definition would be a bit unpredictable.

**Possible options here**:

- [ ] go for the 1.0 route, and have the sender expand outputs as needed.
- [ ] Stop unwrapping the GH commit objects

**I don't really like any of these options TBH**

**Comment by AlanRynne** [comment]
After a quick chat with Matteo, we've decided to leave the current behaviour as is, but document better towards the user what is happening.

So we opt in favour of keeping Gh<->Gh functionality working with no extra steps, and having to extend the received object for any other connector.

TODO:

- [ ] Add info bubble explaining that the received object needs to be expanded.
