### ISSUE TITLE
GH: Consider the possibility of hiding/disabling BIM tabs

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#679]
Some user's may not want or ever need the Speckle BIM capabilities in Grasshopper and, although I would keep them active by default, I also understand why someone would not want to have 2 extra tabs if they don't use them.

This could be done by either:
- Adding a toggle on our top menu
- Adding our own settings on the GH_Settings UI panel (just discovered you can do this last weekend)

This way, it could be active by default and also allow users to hide them at will (may require a restart)

This was raised by Soroush Garivani.

**Comment by teocomi** [comment]
How cramped would it be adding all in one tab?
