### ISSUE TITLE
Autocad adidtional conversions

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#680]
Seems that model curves and meshes sent from Revit are not yet supported, they should probably be prioritized.

**Comment by clairekuang** [comment]
Closing this for now, as mesh to native conversions are disabled due to instability (will crash app on receive for some large meshes)

**Comment by teocomi** [comment]
Reopening this to just check if mesh conversions are resolved after the deserialization updates.

**Comment by clairekuang** [comment]
> Reopening this to just check if mesh conversions are resolved after the deserialization updates.

Nope, but will ping @cristi8 to look at this issue anyways
