### ISSUE TITLE
DesktopUI: receive fmultiple different branches of same stream in Revit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#692]
In Revit the state is preserved per stream, this means that if you receive from branch A and then branch B everything that came from A is deleted automatically. We should let users receive from multiple branches of the same stream.
Possible solutions:
- let users add the same stream more than once in DesktopUI
- add an option to use or not the state when receiving (basically disabling/enabling the update feature in Revit)

**Comment by zhukoven** [comment]
That's a great idea! Thinking of some subtle changes in the model, I would prefer to update an existing stream with changes than push the whole stream.

**Comment by teocomi** [comment]
Closing this as it'll be fixed in DUI2
