### ISSUE TITLE
GH: Split converter broke the Mac build

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#724]
The recent split between Rhino 6 and 7 Converters broke the GH build :(

Reinstating the missing mac postbuild event should do the trick

**Comment by teocomi** [comment]
This should be fixed now, can you confirm @AlanRynne ?

**Comment by AlanRynne** [comment]
The root of the issue is fixed and nearly ready to merge in #727.

Only blocker is Rhino build files `Rhinocommon.dll` etc. Are being copied to the build folder (which should not be happening), and I got stuck there on Friday. I added some commands to delete them but didn't seem to work well. I'll have it sorted out today for sure
