### ISSUE TITLE
🐛 ModelCurve loses its Revit UniqueId after send

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#73]
When sending everything in the standard structural sample model, everything sends to the server fine for the initial commit. However, there is a  _single_ `ModelCurve` that loses its `applicationId` which causes `SendStream` to fail when trying to update the stream.

Skipping the element for now, but needa figure out how it's escaping 🕵️‍♀️

**Comment by didimitrie** [comment]
@izzylys, this does not look like a critical issue - if it didn't show up again, go ahead and close it!
