### ISSUE TITLE
Areas and volumes

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#734]
None of the connectors currently seem to reliably populate object areas or volumes. This is particularly important for volumes of built elements / display meshes in order to do calculations. 

Will require properly converting square / cubic units which I don't think we currently do.

EDIT: Revit attaches them as a param so nvm. We still prob would want some sort of reliable vol or are coming from Rhino

**Comment by AlanRynne** [comment]
Closing, we can reopen when we tackle this back
