### ISSUE TITLE
↕ Receiving streams and diffing the updates with the file state 

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#75]

**Comment by didimitrie** [comment]
Just an update on this one: it requires a few extra spins on the conversion side of things. Started scaffolding functionality in [core](https://github.com/specklesystems/speckle-sharp/blob/master/Core/Core/Kits/ISpeckleConverter.cs#L76), [revit converter ](https://github.com/specklesystems/speckle-sharp/blob/master/Objects/Converters/ConverterRevit/ConverterRevit/ConverterRevit.cs#L43-L45) and [revit](https://github.com/specklesystems/speckle-sharp/blob/master/ConnectorRevit/ConnectorRevit/UI/ClientOperations.cs#L310) to get this going.

**Comment by didimitrie** [comment]
I thunk this is closed.
