### ISSUE TITLE
😈 Handle failed conversions

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#77]
Currently a list is created of all the Revit elements that failed to convert...then it goes poof bc idk what to do with it.

Decide on a strategy for this. Do we write to local logs in addition to sending to our error tracking? Think having local logs printed would be useful for individual debugging.

At a minimum, we'd want a popup in DesktopUI that displays raw text of the errors with maybe a button to export a txt or something.

**Comment by teocomi** [comment]
I think the current message component works fine!
