### ISSUE TITLE
DesktopUI2 on OSX overrides Rhino's application bar menu

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#772]
Spent quite a lot of time on this and could not find a solution, I believe a workaround is possible but would need more time.
Currently, when Speckle is launched on Rhino for OSX the Avalonia app bar menu takes over the Rhino one.
It also seems that the Avalonia app lifecycle gets mixed with the Rhino one, so when the MainWindow is closed, Rhino shuts down too.

I've tried using `MonoMac.Avalonia` to play with the `NSApplication` and `NSMenu` to no avail: I can hide the Avalonia app bar menu, but this also hides the Rhino one. I have also tried to change the way in which the app is launched but to no avail.

Opened an issue in the Avalonia repo here: https://github.com/AvaloniaUI/Avalonia/issues/6699

**Comment by AlanRynne** [comment]
Related to #989

**Comment by teocomi** [comment]
Btw this has been fixed in my sample project: https://github.com/specklesystems/desktopui2

To apply it you'd need to:
- add these nuget sources https://nuget.avaloniaui.net/repository/avalonia-all/index.json and https://aka.ms/skiasharp-eap/index.json
- select the avalonia build 0.10.999-cibuild0017233-beta 
- use this flag new `MacOSPlatformOptions { DisableNativeMenus = true }` [see](https://github.com/specklesystems/desktopui2/blob/main/SpeckleRhino/SpeckleRhinoCommand.cs#L39)

The avalonia team will include this fix in their coming release `0.10.12`
