### ISSUE TITLE
Rvt: Handle curves in DirectShape elements better.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#775]
Right now, curves are not supported in the Revit conversion for DirectShapes, **only** Breps and Meshes are allowed in Revit.

If by any chance a `Curve` get's sent as part of a `DirectShape`, the conversion will stop when it encounters the unsupported geometry and will finish the conversion ahead of time. Which may leave some geometries out of the resulting element.

There's 2 ways we could go about this:

- Add `Curve` as one of the supported geometries in our `DirectShape` class
- Ignore curves in the `ToNative` conversion (instead of throwing an error), which would result in all other geometries being converted.

**Comment by paloknapo** [comment]
@AlanRynne please review and close if needed

**Comment by paloknapo** [comment]
Closing as stale.
