### ISSUE TITLE
Partial Fixtures Structural class

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#779]
ETABS has two different sets of releases for partial fixtures and end releases

**Comment by Reynold-Chan** [comment]
This requires modifying the structural objects quite a bit , it's confusing and doesn't reconcile nicely currently with our object model. Supporting only one for now.

**Comment by Reynold-Chan** [comment]
These two different sets of end releases results in a compounded effect of release fixtures ontop of another . We need to be careful when sending/receiving in terms of which effect we are aiming for.

**Comment by paloknapo** [comment]
Closing as stale.
