### ISSUE TITLE
Objects: Support for n-gons

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#780]
Support n-gons or triangulation of them in mesh conversions on receive using the `n` as the first item in the polygon index array.

Once we have more complete support across connectors, we can consider using `3`/`4` indicators for outgoing faces in ToSpeckle conversion.
Currently, we are still using `0` and `1` for backwards/cross compatibility.

### Support for 3/4 faces
 - [X] Revit
 - [x] Viewer - see https://github.com/specklesystems/speckle-server/pull/486
 - [x] Rhino
 - [x] Blender
 - [x] Unreal
 - [x] Unity 
 - [x] Sketchup
 - [x] AutoCad/Civil3D
 - [x] Bentley
    
### Support n-gon ToNative conversion
 - [x] Revit - see https://github.com/specklesystems/speckle-sharp/pull/831
 - [x] Viewer - see https://github.com/specklesystems/speckle-server/pull/508
 - [x] Rhino - see https://github.com/specklesystems/speckle-sharp/pull/818
 - [x] Blender - see https://github.com/specklesystems/speckle-blender/pull/66
 - [x] Unreal - see https://github.com/specklesystems/speckle-unreal/pull/24
 - [x] Unity - see https://github.com/specklesystems/speckle-unity/pull/55
 - [x] Sketchup
 - [x] AutoCad/Civil3D - see https://github.com/specklesystems/speckle-sharp/pull/949
 - [x] [Bentley](https://github.com/specklesystems/speckle-sharp/issues/1061)
 
### Documentation
- [ ] Document n-gon support across connectors, and detail limitations/lossy conversions.

**Comment by JR-Morgan** [comment]
Faces supported Pre PR:
0 (tris) and 1 (quads)
![image](https://user-images.githubusercontent.com/45512892/141192377-e35ad5a2-0fb3-4966-8f43-e4a12f3d03b9.png)

Post PR:
0 - 1, n
![image](https://user-images.githubusercontent.com/45512892/141192397-2cf2bd0f-3627-4f63-b899-40b8cb61d840.png)

**Comment by JR-Morgan** [comment]
The Viewer, Unity, and AutoCad don't support N-gons/face triangulation natively, and so we would have to triangulate them during ToNative conversion.

I propose creating a triangulation function to be added to the `Objects` namespace. Then the AutoCad and Unity connectors can both use this function.
This function (or a similar one) can be created in JS to be used by the viewer.

Ideally, this function should be able to deal with concave and non-planar faces.
