### ISSUE TITLE
VisualARQ: Receiving creates normal Rhino Blocks

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#790]
Reported in the forum: https://speckle.community/t/visualarq-objects/1325/10

It was my understanding that VisualArq objects were just Rhino blocks with custom metadata, so we may be missing to set some information either when sending or receiving.

If this turns out to be something related to VisualArq itself, we may not be able to fix it though...

**Comment by filipejsbrandao** [comment]
According to Enric Marquès to retrieve the VisualArq objects and not plain Rhino blocks with metadata you would need to use VisualArq API. 
As discussed here: [(https://discourse.mcneel.com/t/visualarq-objects-on-speckle/123321/3)]

**Comment by teocomi** [comment]
We could use reflection and try invoking that method if the VisualARQ dlls are loaded...

**Comment by filipejsbrandao** [comment]
That does seem the best solution. I was afraid a new conector would be needed

**Comment by filipejsbrandao** [comment]
So it seems that a new connector for VisualArq is needed. But VisualArq is a plugin for Rhino which has its own connector. So how should this be approached? How does the grasshopper connector addresses this?

**Comment by teocomi** [comment]
Hi @filipejsbrandao, GH is a separate connector on its own; since it has a plugin-based architecture, it's quite simple to have it load its Speckle connector with or without the Rhino one.

In the case of VisualArq, [as dim suggests](https://discourse.mcneel.com/t/visualarq-objects-on-speckle/123321/5), we would just need to write a converter and not a whole new connector.

If you're planning to take on this challenge, let us know and we can schedule a quick call to discuss it.

**Comment by filipejsbrandao** [comment]
Hello @teocomi! Understood. I have been familiarizing myself with object kits. I have cleared a load of stuff of my table and I have some time available to work on this. Tell me when you can schedule that call.

**Comment by teocomi** [comment]
Fantastic, and sorry for the slow reply, we're in the midst of a release :)
Let's try with this: https://calendly.com/d/gpr-2yt-9nc/30-min-chat

**Comment by filipejsbrandao** [comment]
Hello @AlanRynne! As agreed I created 2 streams, each with one project. I ran into issues sending both of them to Speckle. In both cases the sending process hangs or never completes if I select all the objects in the model. I can send you the files so you can replicate the issue. I tried with multiple selections, and it only works if I exclude section, tags and element layers. These layers contain objects created by VisualArq styles (the equivalent to families in Revit), which automatically places instances of styles in those layers. The first two object styles are part of the documentation and the later contains objects such as sinks or people.

**Comment by filipejsbrandao** [comment]
Hello @AlanRynne! Have you had the chance to look at this issue?

**Comment by paloknapo** [comment]
Closing as stale.
