### ISSUE TITLE
Consolidate Texture Coordinate Conversion

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-sharp#797]
Currently, sending texture coordinates from certain connectors causes problems when receiving in certain connectors. This is because of issues in the format of sending texture coordinates. Many connectors also don't include texture coordinates in their conversions.

- [x] Scope the native formats that different connectors use for texture coordinates and document
- [x] Decide on which format Speckle will use in Objects kit
- [ ] Update Texture-coordinate conversion on connectors
    - [x] <strike>Revit</strike> Won't Fix For now (texture coordinates not exposed through normal API, but apparently are through a custom exporter. [See discussion](https://forums.autodesk.com/t5/revit-api-forum/obtaining-texture-uv-coordinates/td-p/3933391). May look into this again if there is more demand)
    - [x] Rhino - see https://github.com/specklesystems/speckle-sharp/pull/818
    - [ ] Viewer
    - [x] Blender - see https://github.com/specklesystems/speckle-blender/pull/59
    - [x] Unreal - see https://github.com/specklesystems/speckle-unreal/pull/21
    - [x] Unity - see https://github.com/specklesystems/speckle-unity/pull/55
    - [ ] Sketchup
    - [ ] AutoCAD/Civil3D
    - [ ] Bentley

See #785, https://github.com/specklesystems/speckle-unreal/issues/17 https://github.com/specklesystems/speckle-blender/issues/54

**Comment by AlanRynne** [comment]
Closing as all relevant parts in speckle-sharp seem to be implemented. @paloknapo will move the rest to the ideas table

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
