### ISSUE TITLE
Free form elements receive issue

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#810]
Sending  multiple Free Form Elements (using only one component), created in Grasshopper, to Revit does not work properly. Only 1 FFE is received.

Let's do a quick investigation and if it's a substantial bug, we'll tackle it next sprint.

https://speckle.community/t/freeform-elements-from-gh-to-revit/1923

**Comment by AlanRynne** [comment]
This is definitely an issue in the latest release although I could not fully replicate it.

**Sending multiple `FreeformElement`s** seems to fail to convert every single Brep, and falls back to it's mesh representation. This though, doesn't happen consistently and some boxes are missing when the receive operation has finished. The missing boxes may vary ⏬

![Screenshot 2021-11-08 at 09 07 30](https://user-images.githubusercontent.com/2316535/140705751-27d3628d-db97-4d3b-80fc-fcc701183a98.png)
![Screenshot 2021-11-08 at 09 09 41](https://user-images.githubusercontent.com/2316535/140706057-58ece1c0-8b82-42cb-94ee-7173c6e14528.png)

I can reproduce the exact behaviour that was reported with `BREPs` (only one direct shape is generated)

![Sending multiple breps receives just one in Revit](https://user-images.githubusercontent.com/2316535/140705427-edb92993-03de-46e8-936e-c89d67f41fb9.png)

Currently looking into reasons of this happening. I've found several things "wrong":

- The data sent from GH includes `Breps` with a `SpeckleSchema` property. The schema object should not contain a reference to the object, but it does.
- Brainstorming with Dim we theorised it may have something to do with the Project base point change we made recently, although i'm not sure yet.
