### ISSUE TITLE
Civil3d 2021 connector needs support for the unit "USSurveyFeet"

### ISSUE THREAD

**Issue by shashwatmott** [specklesystems/speckle-sharp#827]
While building the Civil3d 2021 connector from source, it fails to send items if the units for the file are "USSurveyFeet" while it does fine with other units.

To reproduce the error, change the Insertion Scale Drawing Units for the file to US Survey Feet and try to send an alignment from Civil 2021 to the server.

The problem seems to stem from Unit.cs in speckle-sharp/Core/Core/Kits

![image](https://user-images.githubusercontent.com/83594960/140994970-accbc08f-0598-465b-a00d-bf5ea5062551.png)

![image](https://user-images.githubusercontent.com/83594960/140995013-83b2d0e1-d611-4e12-bb32-f450cd1c291a.png)

**Comment by clairekuang** [comment]
Thanks for reporting this! Should be a quick fix, will try to squeeze it in for our next release coming up soon 👍

**Comment by shashwatmott** [comment]
Thank you so much! Looking forward to it.
