### ISSUE TITLE
GH: Expand component by KVP not working as expected

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#837]
Hi!

I have 5 Zones objects which I want to extend using the `Extend Speckle Object By Key/Value".
I want to add a "Solid" property.
![image](https://user-images.githubusercontent.com/64929000/141275036-5ee10d78-4257-457e-a0f7-328c69a82cd3.png)

I have 5 branches (1 each object) for both objects and the solids.
I expect that `Expand` would work with only 1 key as well as 1 key for each item.
Instead, the first solid is assigned to all the zone objects.

![image](https://user-images.githubusercontent.com/64929000/141275647-0cbf673e-fb5f-4c28-8c4b-86e402b4ea9b.png)

The python component does what I expect: 

![image](https://user-images.githubusercontent.com/64929000/141275526-26678939-45f1-464b-94a9-6fab879aa791.png)

Do you agree or any reason why the component is working like this?
Thanks!
I'm on speckle again!

**Comment by didimitrie** [comment]
Hi @iltabe - quickly discussed this @AlanRynne: we hate this component so much that we want to deprecate it. It's very difficult for us to ensure a consistent behaviour for it. For your use case, could you not just use the extend speckle object ZUI component? 

Alan is following up right now :)

**Comment by AlanRynne** [comment]
Hi there!

Try the `Extend Speckle Object`. It should work as you expect (and you have total control over list values).

Key/Value components exist to create a wide range of different simple objects at once, and they work in weird misterious ways... 😓 😅 

<img width="675" alt="Screenshot 2021-11-12 at 13 26 34" src="https://user-images.githubusercontent.com/2316535/141466960-f81963cd-d999-43a5-9f53-648559324449.png">

**Comment by iltabe** [comment]
uh, yeah! I forgot I could use the other Extend component. I actually have used it already.
Anyways, I hope the report of the k/v component was useful to make a decision ;)
Thanks!
