### ISSUE TITLE
GUIDs serialisation fail

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#838]
Seems like we don't support the type. We probably should 😺  Offending lines are [here](https://github.com/specklesystems/speckle-sharp/blob/16d5bbd81212b32a9710a838bd7804a7a3a56a20/Core/Core/Serialisation/ValueConverter.cs#L12) I guess, but this is @cristi8's turf now :D 

Thanks to @iltabe for reporting!

**Comment by cristi8** [comment]
Will also look into DateTime and Colors
