### ISSUE TITLE
.bundle format for Revit addin

### ISSUE THREAD

**Issue by thoffeller** [specklesystems/speckle-sharp#861]
Hello Specklers,
we use in our company the .bundle approach to publish  addins to the users machine. This makes the deployment much easier, because all is packaged in one folder. So, installation is more or less a copy only.
For development it is nice, too, because you don't have to find old files in addin folders across all Revit versions, it is one location only ;-)

We can implement this, if you like and send a pull request. What do you think?

**Comment by teocomi** [comment]
Hey Tim, thanks for the nice offer, but we currnetly still prefer deployment via Manager.
There'are a few reasons why:

- we can make sure users have created an account /  logged in before they actually use the connector
- all the connectors (almost) are installed in the same way
- users can receive notifications when new updates are released
- we have more freedom to set custom installation paths etc which is not possible using the store bundles

Hope it makes sense!

**Comment by thoffeller** [comment]
Hi Matteo,
my intention is not to change your installer process and switch to the matket place from adesk.
Only the format would be changed, that is pushed to the clients machine. Currently you have to deploy the addin to different folders in Addin/20xx. This would be one root and then separation inside for all supported releases. Here's a sample from one of our tools:
![image](https://user-images.githubusercontent.com/8693405/142663391-44466ffa-b4f1-49b6-8f62-f57f811dc536.png)

So, I don't want to change your app to user strategy, because this is perfect as it is ;-)

**Comment by teocomi** [comment]
Gotcha! This makes sense indeed, and would simplify some of our installer code as well :)
My only concern would be potential conflicts with the current strategy: if we do not correctly remove previously installed versions correctly and introduce this logic, people could end up with duplicates...
If you'd like, feel free to make a PR, but I'm afraid we'd only be able to update or CI/CD and carry out proper testing only in the new year.

**Comment by teocomi** [comment]
Closing this as it's stagnant, happy to re-open if it becomes relevant again!
