### ISSUE TITLE
GH: Improve erased property when connected as output

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#863]
Hi!

I had a property called "@ Name" which I have connected to a panel to visualize the output.
Then I changed the Speckle object and removed the "@" to make `Name` not detached.
![image](https://user-images.githubusercontent.com/64929000/142447459-685292ab-d410-4dd4-a493-8aa5db184df9.png)
The component is smart enough (as we discussed while ago) to don't disconnect the followers components if a property does not exists anymore. Although it would be nice that it informs the user that a specific connected property as output does not exist anymore.
Can you stroke the output property TextLable? That would be awesome.

**Comment by AlanRynne** [comment]
Interesting suggestion @iltabe, I honestly have no idea what control do we have over the text rendering of the property names, but I agree it could be nice.

We've currently improved the way these work. So now it's "slightly smarter":

If only **one property has been modified**, we assumed you've renamed that specific input. You can see it in action here:
![2021-11-18 17 45 06](https://user-images.githubusercontent.com/2316535/142459065-89093d4d-f409-498b-a763-cf5b63bcaeaa.gif)

If any more than 1 property has been renamed, then the behavior is just like you described above.

Anyway, I do agree it could be nice to flag in some way the deleted ones, so I'll do some digging in the Grasshopper API

**Comment by AlanRynne** [comment]
Closing this as @iltabe did not complain about our solution 😉  Do re-open if it doesn't meet all your needs and we can discuss this further!
