### ISSUE TITLE
List of ETABS Requirements to finish Alpha phase 

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#868]
Each of these tasks should be big tasks
- [x] #869
- [ ] #871
- [ ] Extensive amount of documentation 
- [x] #872
- [x] #870
- [ ] Section profile reconciliation with all software ~ coordinate with jenessa
- [x] #873

**Comment by teocomi** [comment]
Might be closed now?

**Comment by Reynold-Chan** [comment]
not sure. I've been keeping ETABS and the structural connector on alpha out of caution. We support geometry based workflows decently well now with ETABS but we need to still drive a lot of analytical based workflows which are missing.

**Comment by Reynold-Chan** [comment]
We're missing quite a bit of work in terms of updating elements still here. In addition to that, analysis results aren't really being used that much. So until those two things are resolved, ETABS + other CSI products should still be in Alpha.

**Comment by paloknapo** [comment]
closing as stale
