### ISSUE TITLE
Add basic MEP objects

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#87]
The current objects mainly tackle general geometry and some structural elements. We can't forget about MEP!

A tentative list of basic objects to start:
- [x] ducts
- [ ] pipes
- [ ] connectors / fittings (eg terminals, elbows, transitions)
- [ ] more . . .

Feel free to add to the list 🖋

**Comment by teocomi** [comment]
Focus on cool workflows with schema builder!
