### ISSUE TITLE
Rhino: Handle UserDictionaries when sending and receiving

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#902]
For context, see the discussion on the forum [here](https://speckle.community/t/i-need-help-with-saving-rhino-objects-user-dictionary/2078/7).

In short, when sending, we should capture the data held in user dictionaries too. We also need to implement setting it back out again when receiving, which is a bit of a larger problem:

Rhino allows for two ways of storing user data on objects, namely user strings and user dictionaries - when do we set one or the other? For reference, in speckle v1 we relied solely on user dictionaries. Afterwards, Rhino got a nice UI panel for storing user strings, so in speckle v2, we're relying on those when coming to schema builder stuff 🙃 

The simplest way would be to simply store user dictionary data in a special prop, e.g. `userDictionary`, that we handle solely in Rhino at the connector level (not converter, as it complicates things). 

As a task list:
- [x] implement sending of UserDictionaries
- [x] implement receiving of UserDictionaries (setting them on objects post-conversion)

**Comment by clairekuang** [comment]
This should be easy enough, some notes:

- Should consider alignment with Autocad block instance attributes: these have been recently changed to be dictionaries assigned to `attributes`
- Already attaching and setting rhino user strings (`obj.Attributes.GetUserStrings()`) in the connector as separate `keyvalue` props - consider packaging these into a `userStrings` dictionary as well
- User dictionary is retrieved via `obj.Attributes.UserDictionary`, this shouldn't conflict with user strings for both sending and receiving
