### ISSUE TITLE
Rhino: include open viewport views in Project Info when sending

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#919]
From this thread in our community forum: https://speckle.community/t/send-the-views-from-reno-grasshopper-to-the-web-version/2109/6

**Comment by Mehdi-Lucas** [comment]
Hi, can I take this ? I made a prototype for sending the standard views from Rhino to Speckle, would gladly propose it/discuss it

![standardViewSending](https://user-images.githubusercontent.com/71726210/216553595-322b0e01-c4b4-43d2-97a2-3f0f24354eac.gif)

**Comment by clairekuang** [comment]
@Mehdi-Lucas yes this looks great, prs are always welcome! You can target our latest release branch (currently 2.12) and add me as a reviewer ✌️

**Comment by Mehdi-Lucas** [comment]
@clairekuang Done but It seems I can't add you as reviewer 😅
PR is here: https://github.com/specklesystems/speckle-sharp/pull/2118#issue-1572602833
