### ISSUE TITLE
Set Avalonia window owner across all connectors

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#950]
Let's apply [this snippet](https://github.com/specklesystems/speckle-sharp/commit/ee0d60abe4362eb5f153ebbfee3866c31841baa8) across all connectors. 
This will enable a more natural user experience and relationship between DUI2 and the host software window.

Thanks @grokys for the fix!

**Comment by clairekuang** [comment]
- [ ] autocad
- [ ] rhino
- [ ] bentley
- [ ] etabs
- [ ] tekla
