### ISSUE TITLE
Avaolnia Strongly Typed : System.Numerics.Vector 

### ISSUE THREAD

**Issue by Reynold-Chan** [specklesystems/speckle-sharp#951]
SAP2000 problems with references

**Comment by teocomi** [comment]
For context: this is an issue we're getting in SAP2000 at startup when the avalonia windows is initialized, same setup doesn't cause problems in ETABS.

I don't the environment to repro, but it seems related to:
https://stackoverflow.com/questions/61323996/could-not-load-file-or-assembly-system-numeric-vectors-in-ml-net
https://github.com/dotnet/runtime/issues/26370
