### ISSUE TITLE
Build warning when including the Speckle.DesktopUI package in x64 application

### ISSUE THREAD

**Issue by crypto-rsa** [specklesystems/speckle-sharp#954]
When the `Speckle.DesktopUI` package is referenced from an application which targets x64, build warning [CS1607](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1607) is raised.
There is also a related [issue](https://github.com/dotnet/roslyn/issues/3733) in the Roslyn repo.

I _think_ the problem would go away if `DesktopUI` was built as a class library (`.dll`) instead of a Windows application (`.exe`). Is there any reason to build it as an application? I don't think it is intended to be run separately.

**Comment by teocomi** [comment]
Hey @crypto-rsa thanks for the report!
We are soon deprecating DesktopUI in favor of a [new cross-platform UI](https://speckle.guide/user/ui2.html), we don't have NuGets for it yet but they should come out in a couple of weeks.

I'm going to close this for now then.

PS
I think it was set to create an exe simply so we could test it standalone :)
