### ISSUE TITLE
DesktopUI2: UI Window Not Parented to Host Application

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#967]
In the old UI, the window is parented by the host application so you could never have say the Revit UI on top of a Rhino document. This is not the case with DUI2 which is a bit annoying and can easily lead to mistaken commits.

![image](https://user-images.githubusercontent.com/7717434/148983368-a44f6875-d280-4474-b1d0-4bf7c71203bc.png)

**Comment by teocomi** [comment]
Yup, this is fixed in Revit already and just needs to be implemented in the other connectors.
Dupe of: https://github.com/specklesystems/speckle-sharp/issues/950

**Comment by izzylys** [comment]
oh my bad! didn't see the issue in my quick search. closing this now 👍
