### ISSUE TITLE
Revit: investigate pipe misalignment and pipe fitting rotation bugs

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#977]
Reported on the forum here: [https://speckle.community/t/problem-receiving-mep-elements-in-revit-from-revit/2128](https://speckle.community/t/problem-receiving-mep-elements-in-revit-from-revit/2128)

![499a532288ae21f5aed2b9cc5db6acaaa29471fe](https://user-images.githubusercontent.com/16748799/150341368-ff3da252-c098-4335-ba6e-844f2eadc94d.png)

**Comment by AlanRynne** [comment]
Closing this as it was left open but PR was merged
