### ISSUE TITLE
Grasshopper Connector - Duplicate SchemaInfo keys cause error for Create Schema Object component

### ISSUE THREAD

**Issue by kroovers** [specklesystems/speckle-sharp#978]
Hi Speckle,

There seem to be some duplicate SchemaInfo keys in the current Object model:

- Revit > Freeform element
- ETABS > LinearSpring
- ETABS > PointSpring

The Create Schema Object component in Grasshopper is unhappy about this:
![image](https://user-images.githubusercontent.com/77381918/150346690-8a80d945-01f0-4757-ae52-4cbec1dff483.png)

Suggestions: either perform a check on duplicate keys to avoid them, or make sure that the Create Schema Object component can handle these duplicate keys.

Thanks for the good work!
Kelvin

**Comment by didimitrie** [comment]
Thanks for reporting Kelvin! We'll dig into this. It might be purely a gh issue rather than an object model problem (we're doing some shenanigans re ids in there).

**Comment by AlanRynne** [comment]
Hey @kroovers, thanks for reporting this! I'm about to merge in a fix for the issue. It was definitely something to fix on the GH side.

**Comment by AlanRynne** [comment]
Closing this as it was left open after merging.
